Repository elastic/docs-builder, pull requests merged in 2025-08, with the labels that each got.

#1663 Couple of updates / fixes for the Image Carousel
  docs/syntax/images.md
  src/Elastic.Documentation.Site/Assets/image-carousel.ts
  src/Elastic.Documentation.Site/Assets/markdown/image-carousel.css
  src/Elastic.Markdown/Myst/Directives/DirectiveHtmlRenderer.cs
  src/Elastic.Markdown/Myst/Directives/Image/ImageCarouselBlock.cs
  src/Elastic.Markdown/Myst/Directives/Image/ImageCarouselView.cshtml
  src/Elastic.Markdown/Myst/Directives/Image/ImageCarouselViewModel.cs
  tests/Elastic.Markdown.Tests/Directives/ImageCarouselTests.cs
Labels: fix

#1682 Update legacy-url-mappings.yml
  config/legacy-url-mappings.yml
Labels: fix

#1687 Update ECE current version in versions.yml
  config/versions.yml
Labels: documentation

#1686 Add "View as markdown" link
  src/Elastic.Markdown/HtmlWriter.cs
  src/Elastic.Markdown/Layout/_TableOfContents.cshtml
  src/Elastic.Markdown/MarkdownLayoutViewModel.cs
  src/Elastic.Markdown/Page/Index.cshtml
  src/Elastic.Markdown/Page/IndexViewModel.cs
Labels: feature

#1697 Add back semantic Elasticsearch indexing through `semantic` exporter
  src/Elastic.Documentation/Exporter.cs
  src/Elastic.Documentation/Search/DocumentationDocument.cs
  src/tooling/Elastic.Documentation.Tooling/Arguments/ExportOption.cs
  src/tooling/Elastic.Documentation.Tooling/Exporters/ElasticsearchMarkdownExporter.cs
Labels: fix

#1693 Check redirect rules on CI preview builds
  .github/workflows/preview-build.yml
  src/tooling/docs-builder/Cli/DiffCommands.cs
  src/tooling/docs-builder/Tracking/IRepositoryTracker.cs
  src/tooling/docs-builder/Tracking/IntegrationGitRepositoryTracker.cs
  src/tooling/docs-builder/Tracking/LocalGitRepositoryTracker.cs
Labels: feature

#1699 disable diff validate for non docs-builder repos
  .github/workflows/preview-build.yml
Labels: fix

#1684 Bumping stack version to 9.1.1 in versions.yml
  config/versions.yml
Labels: documentation

#1701 Add diff-validate action and minor fixes
  actions/diff-validate/action.yml
  docs-builder.sln
  src/tooling/docs-builder/Cli/DiffCommands.cs
  src/tooling/docs-builder/Tracking/IntegrationGitRepositoryTracker.cs
Labels: feature

#1706 Update substitutions.md
  docs/syntax/substitutions.md
Labels: fix

#1700 Fix some versions in legacy mappings
  config/legacy-url-mappings.yml
Labels: documentation

#1729 config/legacy-url-mappings: bump apm/agent/python to latest release
  config/legacy-url-mappings.yml
Labels: chore

#1730 Revert "Add ElasticsearchGateway and UI adjustments"
  Directory.Packages.props
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/AskAi/AskAiSuggestions.tsx
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/Search/SearchResults.tsx
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/Search/useSearchQuery.ts
  src/Elastic.Documentation/Search/DocumentationDocument.cs
  src/Elastic.Markdown/DocumentationGenerator.cs
  src/Elastic.Markdown/Exporters/IMarkdownExporter.cs
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/api/Elastic.Documentation.Api.Core/Search/SearchUsecase.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Adapters/AskAi/LlmGatewayAskAiGateway.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Adapters/Search/ElasticsearchGateway.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Adapters/Search/ElasticsearchOptions.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Adapters/Search/MockSearchGateway.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Aws/LocalParameterProvider.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Elastic.Documentation.Api.Infrastructure.csproj
  src/api/Elastic.Documentation.Api.Infrastructure/MappingsExstension.cs
  src/api/Elastic.Documentation.Api.Infrastructure/ServicesExtension.cs
  src/tooling/Elastic.Documentation.Tooling/Exporters/ElasticsearchMarkdownExporter.cs
Labels: bug

#1732 Only execute diff validate if there are redirects
  .github/workflows/preview-build.yml
Labels: bug

#1734 Make diff validate return 0 if redirect file does not exist
  .github/workflows/preview-build.yml
  src/tooling/docs-builder/Cli/DiffCommands.cs
Labels: fix

#1736 Add Search/AI Assistant to dev enviroment.
  config/assembler.yml
  src/tooling/docs-builder/Http/DocumentationWebHost.cs
  src/tooling/docs-builder/Http/StaticWebHost.cs
  tests-integration/Elastic.Assembler.IntegrationTests/AssembleFixture.cs
  tests-integration/Elastic.Documentation.Aspire/AppHost.cs
Labels: chore

#1735 Add format note in the footer
  src/Elastic.Documentation.Site/Layout/_Footer.cshtml
Labels: chore

#1738 ECS 9.1 bump
  config/assembler.yml
Labels: chore

#1614 Add best practices for `applies_to`
  docs/_docset.yml
  docs/_redirects.yml
  docs/_snippets/applies_to-key.md
  docs/_snippets/applies_to-lifecycle.md
  docs/_snippets/applies_to-version.md
  docs/configure/site/versions.md
  docs/contribute/_snippets/docs-intro.md
  docs/contribute/add-repo.md
  docs/contribute/branching-strategy.md
  docs/contribute/cumulative-docs.md
  docs/contribute/cumulative-docs/_snippets/content-patterns-list.md
  docs/contribute/cumulative-docs/badge-placement.md
  docs/contribute/cumulative-docs/example-scenarios.md
  docs/contribute/cumulative-docs/guidelines.md
  docs/contribute/cumulative-docs/images/admonition-correct.png
  docs/contribute/cumulative-docs/images/definition-list-entire-item.png
  docs/contribute/cumulative-docs/images/definition-list-item-incorrect.png
  docs/contribute/cumulative-docs/images/definition-list-portion-correct.png
  docs/contribute/cumulative-docs/images/example-code-block-callout.png
  docs/contribute/cumulative-docs/images/example-code-block-tabs.png
  docs/contribute/cumulative-docs/images/example-lifecycle-changed.png
  docs/contribute/cumulative-docs/images/example-multiple-patch.png
  docs/contribute/cumulative-docs/images/example-not-one-section.png
  docs/contribute/cumulative-docs/images/example-one-section.png
  docs/contribute/cumulative-docs/images/example-removed-unversioned-exception.png
  docs/contribute/cumulative-docs/images/example-unversioned-added-different.png
  docs/contribute/cumulative-docs/images/example-unversioned-added-same-exception.png
  docs/contribute/cumulative-docs/images/example-workflow-tabs.png
  docs/contribute/cumulative-docs/images/heading-correct.png
  docs/contribute/cumulative-docs/images/heading-incorrect.png
  docs/contribute/cumulative-docs/images/list-correct.png
  docs/contribute/cumulative-docs/images/list-misc-correct.png
  docs/contribute/cumulative-docs/images/reader-experience.png
  docs/contribute/cumulative-docs/images/table-entire-row-correct.png
  docs/contribute/cumulative-docs/images/table-entire-row-incorrect.png
  docs/contribute/cumulative-docs/images/table-one-cell-correct.png
  docs/contribute/cumulative-docs/images/table-part-of-cell-correct.png
  docs/contribute/cumulative-docs/images/workflow-inline.png
  docs/contribute/cumulative-docs/index.md
  docs/contribute/cumulative-docs/reference.md
  docs/contribute/index.md
  docs/contribute/locally.md
  docs/migration/versioning.md
  docs/syntax/_snippets/stack-serverless-lifecycle-example.md
  docs/syntax/applies.md
  docs/syntax/quick-ref.md
  docs/versions/_snippets/content-patterns-list.md
  docs/versions/content-patterns.md
  docs/versions/index.md
Labels: documentation, DO NOT MERGE

#1704 Run integration tests on bigger runner
  .github/workflows/ci.yml
  config/assembler.yml
Labels: chore

#1752 Fix "unavailable" tooltip text missing in applicability badges
  src/Elastic.Markdown/Myst/Components/ApplicableToComponent.cshtml
Labels: fix

#1755 Move Updatecli to .github folder
  .github/updatecli/updatecli.d/versions.yml
  .github/updatecli/values.d/scm.yml
  .github/workflows/updatecli.yml
Labels: chore

#1756 Allow specifying custom path locally in assembler.yml
  .github/workflows/ci.yml
  aspire/AppHost.cs
  aspire/Properties/launchSettings.json
  aspire/README.md
  aspire/ResourceNames.cs
  aspire/appsettings.Development.json
  aspire/appsettings.json
  aspire/aspire.csproj
  aspire/management-ui.png
  aspire/service-graph.png
  docs-builder.sln
  src/Elastic.Documentation.Configuration/Assembler/AssemblyConfiguration.cs
  src/Elastic.Documentation.Configuration/Assembler/Repository.cs
  src/Elastic.Documentation.Configuration/ConfigurationFileProvider.cs
  src/Elastic.Documentation/GlobalCommandLine.cs
  src/tooling/Elastic.Documentation.Tooling/ExternalCommands/ExternalCommandExecutor.cs
  src/tooling/docs-assembler/AssembleSources.cs
  src/tooling/docs-assembler/Cli/RepositoryCommands.cs
  src/tooling/docs-assembler/Navigation/GlobalNavigationFile.cs
  src/tooling/docs-assembler/Sourcing/RepositorySourcesFetcher.cs
  tests-integration/Elastic.Assembler.IntegrationTests/AssembleFixture.cs
  tests-integration/Elastic.Assembler.IntegrationTests/Elastic.Assembler.IntegrationTests.csproj
  tests-integration/Elastic.Documentation.Aspire/AppHost.cs
  tests-integration/Elastic.Documentation.Aspire/Elastic.Documentation.Aspire.csproj
Labels: chore

#1762 Fix typo guidelines.md
  docs/contribute/cumulative-docs/guidelines.md
Labels: documentation

#1749 Adds table to dynamic tag logic explanation
  docs/contribute/_snippets/tag-processing.md
Labels: documentation

#1741 Add stack version bumps
  .github/updatecli/updatecli.d/versions.yml
  .github/workflows/updatecli.yml
  .updatecli-version
Labels: documentation

#1776 Revert "Update versions.yml for 9.1.3"
  config/versions.yml
Labels: chore

#1763 Add --delete-threshold to `deploy plan` with some sane defaults.
  src/tooling/docs-assembler/Cli/DeployCommands.cs
  src/tooling/docs-assembler/Deploying/AwsS3SyncPlanStrategy.cs
  src/tooling/docs-assembler/Deploying/DocsSync.cs
  tests/docs-assembler.Tests/src/docs-assembler.Tests/DocsSyncTests.cs
Labels: fix

#1784 Remove `Fetch` from CrossLinkResolver, enforce eager fetching of crosslinks
  docs-builder.sln.DotSettings
  src/Elastic.Documentation.Configuration/Builder/TableOfContentsConfiguration.cs
  src/Elastic.Documentation.Configuration/TableOfContents/ITocItem.cs
  src/Elastic.Markdown/DocumentationGenerator.cs
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/IO/Navigation/CrossLinkNavigationItem.cs
  src/Elastic.Markdown/IO/Navigation/DocumentationGroup.cs
  src/Elastic.Markdown/IO/Navigation/NavigationCrossLinkValidator.cs
  src/Elastic.Markdown/Links/CrossLinks/CrossLinkFetcher.cs
  src/Elastic.Markdown/Links/CrossLinks/CrossLinkResolver.cs
  src/Elastic.Markdown/Links/CrossLinks/DocSetConfigurationCrossLinkFetcher.cs
  src/Elastic.Markdown/Links/InboundLinks/LinkIndexCrossLinkFetcher.cs
  src/Elastic.Markdown/Links/InboundLinks/LinkIndexLinkChecker.cs
  src/tooling/docs-assembler/AssembleSources.cs
  src/tooling/docs-assembler/Building/AssemblerBuilder.cs
  src/tooling/docs-assembler/Building/AssemblerCrossLinkFetcher.cs
  src/tooling/docs-assembler/Building/SitemapBuilder.cs
  src/tooling/docs-assembler/Cli/ContentSourceCommands.cs
  src/tooling/docs-assembler/Cli/RepositoryCommands.cs
  src/tooling/docs-assembler/Links/NavigationPrefixChecker.cs
  src/tooling/docs-assembler/Navigation/AssemblerDocumentationSet.cs
  src/tooling/docs-assembler/Navigation/GlobalNavigation.cs
  src/tooling/docs-assembler/Navigation/GlobalNavigationFile.cs
  src/tooling/docs-builder/Cli/Commands.cs
  src/tooling/docs-builder/Http/DocumentationWebHost.cs
  src/tooling/docs-builder/Http/ReloadGeneratorService.cs
  src/tooling/docs-builder/Http/ReloadableGeneratorState.cs
  tests/Elastic.Markdown.Tests/Directives/DirectiveBaseTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlneBaseTests.cs
  tests/Elastic.Markdown.Tests/TestCrossLinkResolver.cs
  tests/authoring/Framework/CrossLinkResolverAssertions.fs
  tests/authoring/Framework/TestCrossLinkResolver.fs
Labels: fix

#1785 Revert "Reapply #1708 Add ElasticsearchGateway and UI adjustments""
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Directory.Packages.props
  build/Targets.fs
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/AskAi/AskAiSuggestions.tsx
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/Search/SearchResults.tsx
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/Search/useSearchQuery.ts
  src/Elastic.Documentation/Search/DocumentationDocument.cs
  src/Elastic.Markdown/DocumentationGenerator.cs
  src/Elastic.Markdown/Exporters/IMarkdownExporter.cs
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/api/Elastic.Documentation.Api.Core/Search/SearchUsecase.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Adapters/AskAi/LlmGatewayAskAiGateway.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Adapters/Search/ElasticsearchGateway.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Adapters/Search/ElasticsearchOptions.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Adapters/Search/MockSearchGateway.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Aws/LocalParameterProvider.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Elastic.Documentation.Api.Infrastructure.csproj
  src/api/Elastic.Documentation.Api.Infrastructure/MappingsExstension.cs
  src/api/Elastic.Documentation.Api.Infrastructure/ServicesExtension.cs
  src/tooling/Elastic.Documentation.Tooling/Exporters/ElasticsearchMarkdownExporter.cs
Labels: chore

#1786 Revert "Revert "Reapply #1708 Add ElasticsearchGateway and UI adjustments"""
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Directory.Packages.props
  build/Targets.fs
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/AskAi/AskAiSuggestions.tsx
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/Search/SearchResults.tsx
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/Search/useSearchQuery.ts
  src/Elastic.Documentation/Search/DocumentationDocument.cs
  src/Elastic.Markdown/DocumentationGenerator.cs
  src/Elastic.Markdown/Exporters/IMarkdownExporter.cs
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/api/Elastic.Documentation.Api.Core/Search/SearchUsecase.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Adapters/AskAi/LlmGatewayAskAiGateway.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Adapters/Search/ElasticsearchGateway.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Adapters/Search/ElasticsearchOptions.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Adapters/Search/MockSearchGateway.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Aws/LocalParameterProvider.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Elastic.Documentation.Api.Infrastructure.csproj
  src/api/Elastic.Documentation.Api.Infrastructure/MappingsExstension.cs
  src/api/Elastic.Documentation.Api.Infrastructure/ServicesExtension.cs
  src/tooling/Elastic.Documentation.Tooling/Exporters/ElasticsearchMarkdownExporter.cs
Labels: feature

#1787 Set `DOCKER_NO_PUBLISH` env variable to conditionally skip container publishing.
  .github/workflows/ci.yml
  build/Targets.fs
Labels: fix

#1778 Update current stack version to 9.1.3
  config/versions.yml
Labels: chore
