Repository elastic/docs-builder, pull requests merged in 2025-09, with the labels that each got.

#1811 Adjust delete threshold logic in `AwsS3SyncPlanStrategy`
  src/tooling/docs-assembler/Cli/DeployCommands.cs
  src/tooling/docs-assembler/Deploying/AwsS3SyncPlanStrategy.cs
  src/tooling/docs-assembler/Deploying/DocsSync.cs
  tests/docs-assembler.Tests/src/docs-assembler.Tests/DocsSyncTests.cs
Labels: fix

#1819 Only render SearchOrAskAI bar if the user has access to the api endpoint
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/SearchOrAskAiButton.tsx
  src/api/Elastic.Documentation.Api.Infrastructure/MappingsExstension.cs
Labels: feature

#1823 Use environment aware elasticsearch index names
  src/tooling/Elastic.Documentation.Tooling/Arguments/ExportOption.cs
  src/tooling/Elastic.Documentation.Tooling/Exporters/ElasticsearchMarkdownExporter.cs
  src/tooling/docs-assembler/Building/AssemblerBuilder.cs
  src/tooling/docs-assembler/Cli/RepositoryCommands.cs
Labels: feature

#1797 Add initial stub of agents file
  AGENTS.md
Labels: documentation

#1825 Enable SearchOrAskAI feature flag in staging
  config/assembler.yml
Labels: chore

#1831 Fix API lambda workflow permissions
  .github/workflows/deploy-api-lambda-edge.yml
  .github/workflows/deploy-api-lambda-prod.yml
  .github/workflows/deploy-api-lambda-staging.yml
Labels: automation

#1833 Change API root endpoint to GET method
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/SearchOrAskAiButton.tsx
  src/api/Elastic.Documentation.Api.Infrastructure/MappingsExstension.cs
Labels: fix

#1851 Use boolean query DSL
  src/api/Elastic.Documentation.Api.Infrastructure/Adapters/Search/ElasticsearchGateway.cs
Labels: fix

#1853 Use POST request to check if the API is available
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/SearchOrAskAiButton.tsx
  src/api/Elastic.Documentation.Api.Infrastructure/MappingsExtensions.cs
Labels: fix

#1854 Deploy API lambda to staging during release
  .github/workflows/deploy-api-lambda-staging.yml
  .github/workflows/release.yml
Labels: automation

#1852 Enable SEARCH_OR_ASK_AI feature flag on prod
  config/assembler.yml
Labels: feature

#1858 Add link to internal feedback issue template
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/SearchOrAskAiModal.tsx
Labels: feature

#1867 Fix/preview workflow branch validate
  .github/workflows/preview-build.yml
Labels: fix

#1878 Refactor applies_to
  src/Elastic.Markdown/Myst/Components/ApplicabilityItem.cs
  src/Elastic.Markdown/Myst/Components/ApplicabilityMappings.cs
  src/Elastic.Markdown/Myst/Components/ApplicabilityRenderer.cs
  src/Elastic.Markdown/Myst/Components/ApplicableToComponent.cshtml
  src/Elastic.Markdown/Myst/Components/ApplicableToViewModel.cs
  tests/authoring/Applicability/ApplicableToComponent.fs
Labels: chore

#1871 Add nav and assembler changes for EDOT docs move
  config/navigation.yml
Labels: documentation

#1877 Bump EDOT CF AWS version
  config/versions.yml
Labels: chore

#1890 Restore nested nav
  config/navigation.yml
Labels: feature

#1827 Edit landing and nav tests for new Get Started
  src/Elastic.Documentation.Site/Layout/_SecondaryNav.cshtml
  src/Elastic.Markdown/Layout/_LandingPage.cshtml
  tests/docs-assembler.Tests/src/docs-assembler.Tests/GlobalNavigationTests.cs
Labels: documentation

#1893 Add a procedure for creating a redirect that passes CI checks
  docs/contribute/redirects.md
Labels: documentation

#1895 Fix appearance of multiple API calls in console codeblock
  NOTICE.txt
  docs/syntax/code.md
  docs/testing/index.md
  src/Elastic.Documentation.Site/Assets/markdown/code.css
  src/Elastic.Markdown/Myst/CodeBlocks/Code.cshtml
  src/Elastic.Markdown/Myst/CodeBlocks/CodeViewModel.cs
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlock.cs
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockHtmlRenderer.cs
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockParser.cs
  src/Elastic.Markdown/Myst/Components/ApplicableToViewModel.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveHtmlRenderer.cs
  tests/Elastic.Markdown.Tests/CodeBlocks/ConsoleCodeBlockTests.cs
Labels: fix

#1903 Force to use KubernetesClient 17.0.14
  Directory.Packages.props
Labels: fix

#1922 Fix typo in AssemblyConfiguration.cs
  src/Elastic.Documentation.Configuration/Assembler/AssemblyConfiguration.cs
Labels: bug

#1929 Add SemVer filter for EDOT Collector (Elastic Agent) version detection in UpdateCLI
  .github/updatecli/updatecli.d/versions.yml
Labels: enhancement

#1933 Include proxy only in DEBUG builds not in publish artifacts
  src/tooling/docs-builder/Http/DocumentationWebHost.cs
  src/tooling/docs-builder/Http/StaticWebHost.cs
  src/tooling/docs-builder/docs-builder.csproj
Labels: fix

#1937 ExceptionFilter should only explicitly set exit code in catch not finally
  src/tooling/Elastic.Documentation.Tooling/Filters/CatchExceptionFilter.cs
Labels: fix

#1875 Improve configuration initialization
  aspire/AppHost.cs
  src/Elastic.Documentation.Configuration/ConfigurationFileProvider.cs
  src/Elastic.Documentation.ServiceDefaults/AppDefaultsExtensions.cs
  src/Elastic.Documentation/ConfigurationSource.cs
  src/Elastic.Documentation/GlobalCommandLine.cs
  src/services/Elastic.Documentation.Assembler/Configuration/ConfigurationCloneService.cs
  src/services/Elastic.Documentation.Assembler/Sourcing/GitFacade.cs
  src/services/Elastic.Documentation.Assembler/Sourcing/RepositorySourcesFetcher.cs
  src/tooling/Elastic.Documentation.Tooling/DocumentationTooling.cs
  src/tooling/Elastic.Documentation.Tooling/Filters/InfoLoggerFilter.cs
  src/tooling/docs-assembler/Cli/RepositoryCommands.cs
  src/tooling/docs-assembler/Program.cs
  src/tooling/docs-builder/Commands/Assembler/ConfigurationCommands.cs
  src/tooling/docs-builder/Filters/CheckForUpdatesFilter.cs
  src/tooling/docs-builder/Filters/ReplaceLogFilter.cs
  src/tooling/docs-builder/Program.cs
  tests/Elastic.ApiExplorer.Tests/Elastic.ApiExplorer.Tests.csproj
  tests/Elastic.ApiExplorer.Tests/TestHelpers.cs
  tests/Elastic.Markdown.Tests/TestHelpers.cs
  tests/Elastic.Markdown.Tests/TestLogger.cs
  tests/authoring/Framework/Setup.fs
  tests/docs-assembler.Tests/src/docs-assembler.Tests/AssemblerConfigurationTests.cs
  tests/docs-assembler.Tests/src/docs-assembler.Tests/TestHelpers.cs
Labels: feature

#1940 Ensure diff validate returns no error if redirects.yml is not found
  src/authoring/Elastic.Documentation.Refactor/Tracking/LocalChangesService.cs
Labels: fix

#1935 Add landing page changes from #1827
  src/Elastic.Markdown/Layout/_LandingPage.cshtml
Labels: fix

#1943 Fix preview builds
  src/Elastic.Documentation.Configuration/ConfigurationFileProvider.cs
Labels: fix

#1941 Applies switch compontent
  docs/_docset.yml
  docs/syntax/applies-switch.md
  src/Elastic.Documentation.Site/Assets/applies-switch.ts
  src/Elastic.Documentation.Site/Assets/main.ts
  src/Elastic.Documentation.Site/Assets/markdown/applies-switch.css
  src/Elastic.Documentation.Site/Assets/open-details-with-anchor.ts
  src/Elastic.Documentation.Site/Assets/styles.css
  src/Elastic.Markdown/Elastic.Markdown.csproj
  src/Elastic.Markdown/Myst/Components/ApplicableToComponent.cshtml
  src/Elastic.Markdown/Myst/Components/ApplicableToViewModel.cs
  src/Elastic.Markdown/Myst/Directives/AppliesSwitch/AppliesItemView.cshtml
  src/Elastic.Markdown/Myst/Directives/AppliesSwitch/AppliesItemViewModel.cs
  src/Elastic.Markdown/Myst/Directives/AppliesSwitch/AppliesSwitchBlock.cs
  src/Elastic.Markdown/Myst/Directives/AppliesSwitch/AppliesSwitchView.cshtml
  src/Elastic.Markdown/Myst/Directives/AppliesSwitch/AppliesSwitchViewModel.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveBlockParser.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveHtmlRenderer.cs
  tests/Elastic.Markdown.Tests/Directives/ApplicabilitySwitchTests.cs
Labels: feature

#1947 Remove STAGING_ELASTIC_NAV feature flag from edge
  config/assembler.yml
Labels: chore

#1951 [ci] Use same drive as checkouts for TMP on Windows
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: fix

#1949 Add `:applies_to:` prop to dropdown directive
  docs/syntax/dropdowns.md
  src/Elastic.Documentation.Site/Assets/markdown/dropdown.css
  src/Elastic.Markdown/Myst/Directives/Admonition/AdmonitionBlock.cs
  src/Elastic.Markdown/Myst/Directives/Admonition/AdmonitionViewModel.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveBlockParser.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveHtmlRenderer.cs
  src/Elastic.Markdown/Myst/Directives/Dropdown/DropdownView.cshtml
  tests/Elastic.Markdown.Tests/Directives/AdmonitionTests.cs
Labels: feature

#1961 Add `:applies_to:` prop to admonitions
  docs/syntax/admonitions.md
  src/Elastic.Documentation.Site/Assets/markdown/admonition.css
  src/Elastic.Markdown/Myst/Directives/Admonition/AdmonitionBlock.cs
  src/Elastic.Markdown/Myst/Directives/Admonition/AdmonitionView.cshtml
  src/Elastic.Markdown/Myst/Directives/DirectiveBlock.cs
  src/Elastic.Markdown/Myst/Renderers/LlmMarkdown/LlmBlockRenderers.cs
  tests/Elastic.Markdown.Tests/Directives/AdmonitionTests.cs
  tests/authoring/Blocks/Admonitions.fs
  tests/authoring/Container/DefinitionLists.fs
  tests/authoring/LlmMarkdown/LlmMarkdownOutput.fs
Labels: feature

#1963 Fix admonition tests
  tests/authoring/Blocks/Admonitions.fs
  tests/authoring/Container/DefinitionLists.fs
Labels: chore

#1964 Add more logging to CLI invocations on CI and ensure CLI invocations have timeouts on CI
  src/Elastic.Documentation/ExternalCommands/ExternalCommandExecutor.cs
  src/authoring/Elastic.Documentation.Refactor/Tracking/LocalChangesService.cs
  src/authoring/Elastic.Documentation.Refactor/Tracking/LocalGitRepositoryTracker.cs
  src/services/Elastic.Documentation.Assembler/Deploying/Redirects/AwsCloudFrontKeyValueStoreProxy.cs
  src/services/Elastic.Documentation.Assembler/Sourcing/GitFacade.cs
  src/services/Elastic.Documentation.Assembler/Sourcing/RepositorySourcesFetcher.cs
Labels: fix

#1971 Remove uppercase from admonition titles
  src/Elastic.Documentation.Site/Assets/markdown/admonition.css
Labels: fix
