Repository elastic/docs-builder, pull requests merged in 2025-03, with the labels that each got.

#662 Add mobile navigations
  docs/index.md
  src/Elastic.Markdown/Assets/copybutton.css
  src/Elastic.Markdown/Assets/markdown/code.css
  src/Elastic.Markdown/Assets/markdown/dropdown.css
  src/Elastic.Markdown/Assets/markdown/list.css
  src/Elastic.Markdown/Assets/markdown/tabs.css
  src/Elastic.Markdown/Assets/markdown/typography.css
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Assets/theme.css
  src/Elastic.Markdown/Slices/Layout/_Breadcrumbs.cshtml
  src/Elastic.Markdown/Slices/Layout/_Header.cshtml
  src/Elastic.Markdown/Slices/Layout/_PagesNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_PrevNextNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_PrimaryNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_PrimaryNavDropdownItem.cshtml
  src/Elastic.Markdown/Slices/Layout/_SecondaryNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_TableOfContents.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
Labels: feature

#666 Add extension hook points to all special usecases to inject themselves into docs build process
  .editorconfig
  docs/_docset.yml
  docs/configure/content-set/extensions.md
  src/Elastic.Markdown/BuildContext.cs
  src/Elastic.Markdown/Elastic.Markdown.csproj
  src/Elastic.Markdown/Extensions/DetectionRules/DetectionRule.cs
  src/Elastic.Markdown/Extensions/DetectionRules/DetectionRuleFile.cs
  src/Elastic.Markdown/Extensions/DetectionRules/DetectionRulesDocsBuilderExtension.cs
  src/Elastic.Markdown/Extensions/DetectionRules/DetectionRulesReference.cs
  src/Elastic.Markdown/Extensions/IDocsBuilderExtension.cs
  src/Elastic.Markdown/IO/Configuration/ConfigurationFile.cs
  src/Elastic.Markdown/IO/Configuration/EnabledExtensions.cs
  src/Elastic.Markdown/IO/Configuration/FeatureFlags.cs
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/IO/Navigation/DocumentationGroup.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveHtmlRenderer.cs
  src/Elastic.Markdown/Myst/MarkdownParser.cs
  src/Elastic.Markdown/Slices/_ViewModels.cs
  src/docs-builder/Http/DocumentationWebHost.cs
Labels: feature

#669 Re-enable inbound links validation on publish
  .github/workflows/preview-build.yml
Labels: ci

#668 feature/publish links index lamdba
  Directory.Build.props
  docs-builder.sln
  src/Elastic.Markdown/SourceGenerationContext.cs
  src/docs-lambda-index-publisher/Program.cs
  src/docs-lambda-index-publisher/README.md
  src/docs-lambda-index-publisher/aws-lambda-tools-defaults.json
  src/docs-lambda-index-publisher/docs-lambda-index-publisher.csproj
  src/docs-lambda-index-publisher/lambda.DockerFile
Labels: feature

#663 Add landing page feature flag
  docs/_docset.yml
  src/Elastic.Markdown/Assets/copybutton.css
  src/Elastic.Markdown/Assets/copybutton.ts
  src/Elastic.Markdown/Assets/markdown/code.css
  src/Elastic.Markdown/Assets/pages-nav.ts
  src/Elastic.Markdown/Elastic.Markdown.csproj
  src/Elastic.Markdown/Helpers/Htmx.cs
  src/Elastic.Markdown/IO/Configuration/FeatureFlags.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Layout/_Breadcrumbs.cshtml
  src/Elastic.Markdown/Slices/Layout/_Header.cshtml
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
  src/Elastic.Markdown/Slices/Layout/_PrimaryNavDropdownItem.cshtml
  src/Elastic.Markdown/Slices/Layout/_SecondaryNav.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
  src/Elastic.Markdown/_static/community-logo.png
  tests/Elastic.Markdown.Tests/Inline/AnchorLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/DirectiveBlockLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineAnchorTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineLinkTests.cs
Labels: feature

#673 Disable `primary-nav` and `landing-page` feature in docs-builder
  docs/_docset.yml
Labels: fix

#674 Fix links in landing page
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
Labels: fix

#675 Fix local file serving
  src/docs-builder/Http/DocumentationWebHost.cs
Labels: fix

#678 Fix scroll-margin-top
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Slices/Layout/_PagesNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_PrimaryNav.cshtml
Labels: fix

#677 [docs] Update custom anchor links section in heading syntax docs
  docs/syntax/headings.md
Labels: documentation

#679 Refactor file serving algorithm
  src/docs-builder/Http/DocumentationWebHost.cs
Labels: chore

#682 Fix image styling
  src/Elastic.Markdown/Assets/markdown/images.css
  src/Elastic.Markdown/Assets/styles.css
Labels: fix

#665 Add support for screenshot class
  docs/syntax/images.md
  src/Elastic.Markdown/Assets/markdown/images.css
  src/Elastic.Markdown/Myst/Directives/DirectiveHtmlRenderer.cs
  src/Elastic.Markdown/Myst/Directives/ImageBlock.cs
  src/Elastic.Markdown/Slices/Directives/Image.cshtml
  src/Elastic.Markdown/Slices/Directives/_ViewModels.cs
  tests/Elastic.Markdown.Tests/Directives/ImageTests.cs
Labels: enhancement

#683 Add clarification to redirects.md
  docs/contribute/redirects.md
Labels: documentation

#689 Use default font for definition lists
  src/Elastic.Markdown/Assets/markdown/definition-list.css
  src/Elastic.Markdown/Assets/markdown/typography.css
Labels: fix

#687 Adjust heading font sizes
  docs/syntax/headings.md
  src/Elastic.Markdown/Assets/markdown/typography.css
Labels: fix

#686 Fix rendering of code blocks with callouts and a block in between
  docs/syntax/code.md
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockHtmlRenderer.cs
  tests/Elastic.Markdown.Tests/CodeBlocks/CallOutTests.cs
Labels: fix

#685 Allow substitutions in code blocks from global docset variables.
  docs/syntax/substitutions.md
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockParser.cs
Labels: enhancement

#676 Add layout system and NotFound layout
  docs/404.md
  docs/_docset.yml
  src/Elastic.Markdown/Assets/main.ts
  src/Elastic.Markdown/Elastic.Markdown.csproj
  src/Elastic.Markdown/Helpers/Htmx.cs
  src/Elastic.Markdown/Myst/FrontMatter/FrontMatterParser.cs
  src/Elastic.Markdown/Myst/YamlSerialization.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Layout/_Head.cshtml
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
  src/Elastic.Markdown/Slices/Layout/_NotFound.cshtml
  src/Elastic.Markdown/Slices/Layout/_PrimaryNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_SecondaryNav.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
  src/docs-builder/Http/DocumentationWebHost.cs
Labels: feature

#696 Revert "Refactor file serving algorithm"
  src/docs-builder/Http/DocumentationWebHost.cs
Labels: fix

#697 Fix navigation
  src/Elastic.Markdown/Slices/Layout/_PrimaryNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_PrimaryNavDropdownItem.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
Labels: fix

#698 Fix `scrollTop` when navigating through pages
  docs/_docset.yml
  src/Elastic.Markdown/Assets/main.ts
Labels: fix

#702 Fix scroll position when opening a link with an anchor
  src/Elastic.Markdown/Assets/pages-nav.ts
  src/Elastic.Markdown/Assets/styles.css
Labels: fix

#510 Remove UseSoftlineBreakAsHardlineBreak from MarkdownParser
  docs/configure/content-set/navigation.md
  src/Elastic.Markdown/IO/Configuration/ConfigurationFile.cs
  src/Elastic.Markdown/Myst/MarkdownParser.cs
  tests/Elastic.Markdown.Tests/Inline/SubstitutionTest.cs
  tests/authoring/Container/DefinitionLists.fs
  tests/authoring/Inline/CrossLinksRedirects.fs
  tests/authoring/Inline/Substitutions.fs
Labels: fix

#707 Skip the navigation item if the parent group points to the same file
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
Labels: fix

#695 Allow comments between code blocks and callouts
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockHtmlRenderer.cs
  tests/Elastic.Markdown.Tests/CodeBlocks/CallOutTests.cs
Labels: enhancement

#713 Initial version of sourcing repositories for assembly
  src/docs-assembler/AssembleContext.cs
  src/docs-assembler/Cli/RepositoryCommands.cs
  src/docs-assembler/Configuration/AssemblyConfiguration.cs
  src/docs-assembler/Sourcing/RepositoryCloner.cs
  src/docs-assembler/assembler.yml
  src/docs-assembler/conf.yml
  src/docs-assembler/docs-assembler.csproj
Labels: feature

#699 Add ability to set code block arguments
  docs/syntax/code.md
  docs/syntax/substitutions.md
  src/Elastic.Markdown/Myst/CodeBlocks/CodeBlockArguments.cs
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockParser.cs
  tests/Elastic.Markdown.Tests/CodeBlocks/CodeBlockArgumentsTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlneBaseTests.cs
  tests/Elastic.Markdown.Tests/Inline/SubstitutionTest.cs
Labels: feature

#714 Allow to open link in a new tab when pressing the modifier key (ctrl or cmd)
  src/Elastic.Markdown/Assets/main.ts
  src/Elastic.Markdown/package-lock.json
  src/Elastic.Markdown/package.json
Labels: fix

#715 Allow substitutions in external links
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  tests/Elastic.Markdown.Tests/Inline/InlineLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlneBaseTests.cs
Labels: enhancement

#716 Embedd assembler.yml in binary temporarily before its homed in docs-content
  src/docs-assembler/AssembleContext.cs
  src/docs-assembler/docs-assembler.csproj
Labels: fix

#717 Move base image for assembly over to jammy to ensure git is available
  build/Targets.fs
Labels: fix

#719 AOT compile assembler
  build/Targets.fs
  src/docs-assembler/docs-assembler.csproj
Labels: fix

#723 Use https remotes for assembler clones
  build/Targets.fs
  src/Elastic.Documentation.Tooling/Diagnostics/Console/GithubAnnotationOutput.cs
  src/docs-assembler/Sourcing/RepositoryCloner.cs
Labels: fix

#725 Initial v0 of docs-assembler repos build-all command.
  src/Elastic.Markdown/BuildContext.cs
  src/docs-assembler/AssembleContext.cs
  src/docs-assembler/Building/AssemblerBuilder.cs
  src/docs-assembler/Cli/RepositoryCommands.cs
  src/docs-assembler/Configuration/AssemblyConfiguration.cs
  src/docs-assembler/Configuration/Repository.cs
  src/docs-assembler/Sourcing/Checkout.cs
  src/docs-assembler/Sourcing/RepositoryCloner.cs
  src/docs-assembler/Sourcing/RepositorySourcesFetcher.cs
  src/docs-builder/Cli/Commands.cs
Labels: feature

#727 Fix Exec() not passing name so git clone no longer works in assembler
  src/docs-assembler/Sourcing/RepositorySourcesFetcher.cs
Labels: fix

#726 Assembler share single crosslink resolver over all the builds
  src/docs-assembler/Building/AssemblerBuilder.cs
  src/docs-assembler/Building/AssemblerCrossLinkFetcher.cs
  src/docs-assembler/Configuration/Repository.cs
  src/docs-assembler/assembler.yml
Labels: feature

#729 Fix links to content pattern examples
  docs/versions/content-patterns.md
Labels: documentation

#731 Update CODEOWNERS
  .github/CODEOWNERS
Labels: ci

#730 Fix code copying in Console blocks
  src/Elastic.Markdown/Assets/copybutton.ts
Labels: bug

#728 Introduce IUriEnvironmentResolver to resolve crosslinks based on deployment environment
  .editorconfig
  src/Elastic.Markdown/CrossLinks/CrossLinkResolver.cs
  src/Elastic.Markdown/CrossLinks/IUriEnvironmentResolver.cs
  src/docs-assembler/Building/AssemblerBuilder.cs
  src/docs-assembler/Building/PublishEnvironmentUriResolver.cs
  src/docs-assembler/Cli/RepositoryCommands.cs
  src/docs-assembler/Configuration/AssemblyConfiguration.cs
  src/docs-assembler/assembler.yml
  tests/Elastic.Markdown.Tests/TestCrossLinkResolver.cs
  tests/authoring/Framework/TestCrossLinkResolver.fs
Labels: feature

#733 Skip security-docs in assembler while we wait for move to detection-rules
  src/docs-assembler/assembler.yml
Labels: chore

#735 Remove hardcoded links to link references, use advertised path from the registry
  docs/testing/cross-links.md
  src/Elastic.Markdown/CrossLinks/ConfigurationCrossLinkFetcher.cs
  src/Elastic.Markdown/CrossLinks/CrossLinkFetcher.cs
  src/Elastic.Markdown/CrossLinks/CrossLinkResolver.cs
  src/Elastic.Markdown/CrossLinks/IUriEnvironmentResolver.cs
  src/Elastic.Markdown/InboundLinks/LinkIndexCrossLinkFetcher.cs
  src/Elastic.Markdown/InboundLinks/LinkIndexLinkChecker.cs
  src/docs-assembler/Building/AssemblerCrossLinkFetcher.cs
  tests/Elastic.Markdown.Tests/TestCrossLinkResolver.cs
  tests/authoring/Framework/TestCrossLinkResolver.fs
Labels: fix

#721 Add global elastic.co nav
  src/Elastic.Markdown/Assets/main.ts
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Assets/theme.css
  src/Elastic.Markdown/Extensions/DetectionRules/DetectionRulesDocsBuilderExtension.cs
  src/Elastic.Markdown/Extensions/IDocsBuilderExtension.cs
  src/Elastic.Markdown/IO/Configuration/ConfigurationFile.cs
  src/Elastic.Markdown/IO/Configuration/ITocItem.cs
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/Elastic.Markdown/IO/Navigation/DocumentationGroup.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Layout/_Breadcrumbs.cshtml
  src/Elastic.Markdown/Slices/Layout/_Header.cshtml
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
  src/Elastic.Markdown/Slices/Layout/_PagesNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_SecondaryNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_TableOfContents.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTree.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
Labels: feature

#739 Add the notion of documentation file exporters.
  .github/workflows/preview-build.yml
  action.yml
  src/Elastic.Markdown/DocumentationGenerator.cs
  src/Elastic.Markdown/Exporters/DocumentationFileExporter.cs
  src/Elastic.Markdown/Exporters/NoopDocumentationFileExporter.cs
  src/Elastic.Markdown/IO/State/GenerationState.cs
  src/docs-builder/Cli/Commands.cs
  tests/authoring/Framework/Setup.fs
Labels: feature

#740 Add shift and modifier key handling again
  src/Elastic.Markdown/Assets/main.ts
Labels: fix

#741 Ensure we pass along metadata-only in preview-build to docs-builder action
  .github/workflows/preview-build.yml
Labels: ci

#743 Free disk space is no longer needed for asciidocalypse
  .github/workflows/preview-build.yml
Labels: ci

#738 Adjust path resolution to enable Windows support.
  src/Elastic.Markdown/BuildContext.cs
  src/Elastic.Markdown/DocumentationGenerator.cs
  src/Elastic.Markdown/Extensions/DetectionRules/DetectionRulesDocsBuilderExtension.cs
  src/Elastic.Markdown/IO/Configuration/ConfigurationFile.cs
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/docs-builder/Http/DocumentationWebHost.cs
Labels: fix

#746 Landing page changes
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
  src/Elastic.Markdown/_static/icon-dashboards-64-color.svg
  src/Elastic.Markdown/_static/icon-graph-64-color.svg
  src/Elastic.Markdown/_static/icon-infra-64-color.svg
  src/Elastic.Markdown/_static/icon-three-people-64-color.svg
Labels: fix

#745 Control allow index per environment, default to false
  src/docs-assembler/Building/AssemblerBuilder.cs
  src/docs-assembler/Configuration/AssemblyConfiguration.cs
  src/docs-assembler/assembler.yml
Labels: fix

#747 Typography adjustments
  src/Elastic.Markdown/Assets/markdown/typography.css
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Slices/Layout/_Breadcrumbs.cshtml
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
Labels: fix

#750 Landing page adjustments pt2
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
Labels: fix

#751 Sidebar nav styling changes
  src/Elastic.Markdown/Slices/Layout/_TableOfContents.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTree.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
Labels: fix

#753 Remove tj-actions usage, eventhough we had it pinned as gitref
  .github/workflows/preview-build.yml
  src/docs-assembler/Sourcing/RepositorySourcesFetcher.cs
Labels: ci

#752 Fix table of contents progress indicator
  src/Elastic.Markdown/Assets/toc-nav.ts
  src/Elastic.Markdown/Slices/Layout/_TableOfContents.cshtml
Labels: fix

#758 Add content hash as query string to static file paths
  src/Elastic.Markdown/IO/EmbeddedOrPhysicalFileProvider.cs
  src/Elastic.Markdown/IO/StaticFileContentHashProvider.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Index.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
  src/docs-builder/Http/DocumentationWebHost.cs
Labels: enhancement

#755 User friendly table design
  src/Elastic.Markdown/Assets/markdown/table.css
Labels: enhancement

#756 Fix git information lookup folder, fixes incremental compilation.
  src/Elastic.Markdown/BuildContext.cs
  src/Elastic.Markdown/IO/Discovery/GitCheckoutInformation.cs
  tests/authoring/Generator/LinkReferenceFile.fs
Labels: fix

#761 Add favicon tags
  src/Elastic.Markdown/Slices/Layout/_Favicon.cshtml
  src/Elastic.Markdown/Slices/Layout/_Head.cshtml
Labels: feature

#762 Add support for diagnostic hints and track unused substitution keys
  src/Elastic.Documentation.Tooling/Diagnostics/Console/ConsoleDiagnosticsCollector.cs
  src/Elastic.Documentation.Tooling/Diagnostics/Console/ErrataFileSourceRepository.cs
  src/Elastic.Documentation.Tooling/Diagnostics/Console/GithubAnnotationOutput.cs
  src/Elastic.Documentation.Tooling/Diagnostics/Log.cs
  src/Elastic.Markdown/Diagnostics/DiagnosticsChannel.cs
  src/Elastic.Markdown/DocumentationGenerator.cs
  src/Elastic.Markdown/Helpers/Interpolation.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockParser.cs
  tests/Elastic.Markdown.Tests/Interpolation/InterpolationTests.cs
Labels: feature

#763 Skip preview jobs on fork repositories
  .github/workflows/preview-build.yml
  .github/workflows/preview-cleanup.yml
Labels: enhancement

#765 Preload fonts in use as per CSS definitions
  src/Elastic.Markdown/Helpers/Preloader.cs
  src/Elastic.Markdown/Slices/Layout/_Head.cshtml
Labels: feature

#767 Restrict docset.yml configs that define toc.yml sections to ONLY link to sub toc.yml files
  docs/_docset.yml
  src/Elastic.Markdown/IO/Configuration/ConfigurationFile.cs
  src/Elastic.Markdown/IO/Configuration/ITocItem.cs
  src/Elastic.Markdown/IO/Configuration/TableOfContentsConfiguration.cs
Labels: feature

#772 Fix layout and horizontal scrollable tables
  src/Elastic.Markdown/Assets/markdown/table.css
  src/Elastic.Markdown/Helpers/Htmx.cs
  src/Elastic.Markdown/Slices/Layout/_PagesNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_TableOfContents.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTree.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
  tests/Elastic.Markdown.Tests/Inline/AnchorLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/DirectiveBlockLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineAnchorTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineLinkTests.cs
Labels: fix

#770 feature/assembler global toc
  docs-builder.sln
  src/Elastic.Documentation.Tooling/Diagnostics/Console/ConsoleDiagnosticsCollector.cs
  src/Elastic.Markdown/BuildContext.cs
  src/Elastic.Markdown/CrossLinks/CrossLinkResolver.cs
  src/Elastic.Markdown/CrossLinks/IUriEnvironmentResolver.cs
  src/Elastic.Markdown/Diagnostics/DiagnosticsChannel.cs
  src/Elastic.Markdown/Diagnostics/ProcessorDiagnosticExtensions.cs
  src/Elastic.Markdown/DocumentationGenerator.cs
  src/Elastic.Markdown/IO/Configuration/ConfigurationFile.cs
  src/Elastic.Markdown/IO/Configuration/RedirectFile.cs
  src/Elastic.Markdown/IO/Configuration/TableOfContentsConfiguration.cs
  src/Elastic.Markdown/IO/Configuration/YamlStreamReader.cs
  src/Elastic.Markdown/IO/Discovery/GitCheckoutInformation.cs
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Index.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
  src/docs-assembler/AssembleContext.cs
  src/docs-assembler/Building/AssemblerBuilder.cs
  src/docs-assembler/Building/AssemblerCrossLinkFetcher.cs
  src/docs-assembler/Building/PublishEnvironmentUriResolver.cs
  src/docs-assembler/Cli/RepositoryCommands.cs
  src/docs-assembler/Configuration/AssemblyConfiguration.cs
  src/docs-assembler/Configuration/Repository.cs
  src/docs-assembler/Navigation/GlobalNavigation.cs
  src/docs-assembler/Navigation/GlobalNavigationFile.cs
  src/docs-assembler/Sourcing/RepositorySourcesFetcher.cs
  src/docs-assembler/YamlStaticContext.cs
  src/docs-assembler/assembler.yml
  src/docs-assembler/docs-assembler.csproj
  src/docs-assembler/navigation.yml
  src/docs-builder/Cli/Commands.cs
  src/docs-builder/Http/StaticWebHost.cs
  tests/Elastic.Markdown.Tests/OutputDirectoryTests.cs
  tests/Elastic.Markdown.Tests/TestCrossLinkResolver.cs
  tests/authoring/Framework/Setup.fs
  tests/authoring/Framework/TestCrossLinkResolver.fs
  tests/authoring/Framework/TestValues.fs
  tests/docs-assembler.Tests/src/docs-assembler.Tests/GlobalNavigationTests.cs
  tests/docs-assembler.Tests/src/docs-assembler.Tests/docs-assembler.Tests.csproj
Labels: feature

#775 Fix/font preload static path
  src/Elastic.Markdown/Helpers/Preloader.cs
  src/Elastic.Markdown/Slices/Layout/_Head.cshtml
Labels: fix

#781 Refactor navigation to be more anemic.
  src/Elastic.Markdown/Extensions/DetectionRules/DetectionRulesDocsBuilderExtension.cs
  src/Elastic.Markdown/Extensions/IDocsBuilderExtension.cs
  src/Elastic.Markdown/Helpers/Htmx.cs
  src/Elastic.Markdown/IO/Configuration/ITocItem.cs
  src/Elastic.Markdown/IO/Configuration/TableOfContentsConfiguration.cs
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/IO/Navigation/DocumentationGroup.cs
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  src/Elastic.Markdown/Myst/MarkdownParser.cs
  src/Elastic.Markdown/Myst/Renderers/HtmxLinkInlineRenderer.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Index.cshtml
  src/Elastic.Markdown/Slices/Layout/_Breadcrumbs.cshtml
  src/Elastic.Markdown/Slices/Layout/_Header.cshtml
  src/Elastic.Markdown/Slices/Layout/_PagesNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_PrevNextNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_PrimaryNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_PrimaryNavDropdownItem.cshtml
  src/Elastic.Markdown/Slices/Layout/_SecondaryNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTree.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
  tests/Elastic.Markdown.Tests/Inline/AnchorLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/DirectiveBlockLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineAnchorTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineLinkTests.cs
Labels: feature

#766 Revert "Remove tj-actions usage, eventhough we had it pinned as gitref"
  .github/workflows/preview-build.yml
Labels: fix

#776 Add ability to set canonical base url
  src/Elastic.Markdown/BuildContext.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Index.cshtml
  src/Elastic.Markdown/Slices/Layout/_Head.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
  src/docs-builder/Cli/Commands.cs
Labels: feature

#778 Add ability to set description meta tag
  src/Elastic.Markdown/Assets/main.ts
  src/Elastic.Markdown/DocumentationGenerator.cs
  src/Elastic.Markdown/Myst/FrontMatter/FrontMatterParser.cs
  src/Elastic.Markdown/Slices/DescriptionGenerator.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Index.cshtml
  src/Elastic.Markdown/Slices/Layout/_Head.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
Labels: feature

#784 Move meta charset up
  src/Elastic.Markdown/Slices/Layout/_Head.cshtml
Labels: fix

#789 Fix table styling
  docs/syntax/tables.md
  src/Elastic.Markdown/Assets/markdown/table.css
Labels: fix

#786 Update frontmatter docs
  docs/syntax/frontmatter.md
Labels: documentation

#785 Add og meta tags
  src/Elastic.Markdown/Slices/Layout/_Head.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
Labels: SEO, feature

#787 Fix pages navigation appearance
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Layout/_TocTree.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
Labels: fix

#791 Refactor to use `WorkingDirectoryRoot` over `Root`.
  src/Elastic.Markdown/BuildContext.cs
  src/Elastic.Markdown/IO/Discovery/GitCheckoutInformation.cs
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/Elastic.Markdown/IO/Paths.cs
  src/Elastic.Markdown/InboundLinks/LinkIndexLinkChecker.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/docs-assembler/AssembleContext.cs
  src/docs-assembler/Cli/InboundLinkCommands.cs
  src/docs-assembler/Sourcing/RepositorySourcesFetcher.cs
  src/docs-builder/Cli/Commands.cs
  src/docs-builder/Cli/InboundLinkCommands.cs
  src/docs-builder/Http/ParcelWatchService.cs
  src/docs-builder/Http/StaticWebHost.cs
  tests/Elastic.Markdown.Tests/Directives/DirectiveBaseTests.cs
  tests/Elastic.Markdown.Tests/DocSet/LinkReferenceTests.cs
  tests/Elastic.Markdown.Tests/DocSet/NavigationTestsBase.cs
  tests/Elastic.Markdown.Tests/Inline/InlneBaseTests.cs
  tests/Elastic.Markdown.Tests/OutputDirectoryTests.cs
  tests/Elastic.Markdown.Tests/SettingsInclusion/IncludeTests.cs
  tests/authoring/Framework/Setup.fs
  tests/authoring/Generator/LinkReferenceFile.fs
Labels: fix

#792 Only show "Edit this page" link if the url is not `null`
  src/Elastic.Markdown/Slices/Layout/_TableOfContents.cshtml
Labels: fix

#794 Add support for custom GitCheckoutInformation in BuildContext
  src/Elastic.Markdown/BuildContext.cs
  src/Elastic.Markdown/IO/Discovery/GitCheckoutInformation.cs
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/docs-assembler/Building/AssemblerBuilder.cs
  src/docs-assembler/Navigation/GlobalNavigation.cs
Labels: fix

#796 Ensure we fallback to the embedded navigation.yml for the assembler build
  src/docs-assembler/AssembleContext.cs
Labels: fix

#795 Fix pages nav behaviour
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
Labels: fix

#798 Rename assembler environment from `production` to `prod`
  src/docs-assembler/assembler.yml
  tests/docs-assembler.Tests/src/docs-assembler.Tests/GlobalNavigationTests.cs
Labels: chore

#790 Fix "Edit This File" path
  .github/workflows/preview-build.yml
  src/Elastic.Markdown/IO/Discovery/GitCheckoutInformation.cs
Labels: fix

#799 Includes GITHUB_PR_REF_NAME as a job-level environment variable.
  .github/workflows/preview-build.yml
Labels: fix

#800 Fix pages nav behaviour attempt 2
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
Labels: fix

#801 Add beats/extend folder to assembler navigation
  src/docs-assembler/navigation.yml
Labels: fix

#793 Open external links in another tab
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  src/Elastic.Markdown/Myst/Renderers/HtmxLinkInlineRenderer.cs
  tests/Elastic.Markdown.Tests/Inline/InlineLinkTests.cs
Labels: feature

#802 Add simple header for `IsPrimaryNavEnabled==false`
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Index.cshtml
  src/Elastic.Markdown/Slices/Layout/_Header.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
  src/Elastic.Markdown/_static/logo-elastic-glyph-color.svg
Labels: enhancement

#805 Fix HTMX head changes
  src/Elastic.Markdown/Slices/Layout/_Head.cshtml
Labels: fix

#808 Add google tag manager
  src/Elastic.Markdown/Assets/main.ts
  src/Elastic.Markdown/BuildContext.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Index.cshtml
  src/Elastic.Markdown/Slices/Layout/_Head.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
  src/docs-assembler/Building/AssemblerBuilder.cs
  src/docs-assembler/Configuration/AssemblyConfiguration.cs
  src/docs-assembler/assembler.yml
Labels: feature

#806 Allow extensions to inject IDocumentationFileExporter and control the relative path published in links.json
  src/Elastic.Markdown/DocumentationGenerator.cs
  src/Elastic.Markdown/Exporters/DocumentationFileExporter.cs
  src/Elastic.Markdown/Exporters/NoopDocumentationFileExporter.cs
  src/Elastic.Markdown/Extensions/DetectionRules/DetectionRule.cs
  src/Elastic.Markdown/Extensions/DetectionRules/DetectionRuleFile.cs
  src/Elastic.Markdown/Extensions/DetectionRules/DetectionRulesDocsBuilderExtension.cs
  src/Elastic.Markdown/Extensions/DetectionRules/RuleDocumentationFileExporter.cs
  src/Elastic.Markdown/Extensions/IDocsBuilderExtension.cs
  src/Elastic.Markdown/IO/DocumentationFile.cs
  src/Elastic.Markdown/IO/State/LinkReference.cs
Labels: fix

#809 Detect variables as they are parsed in the AST
  src/Elastic.Markdown/Myst/Substitution/SubstitutionParser.cs
Labels: fix

#810 New pages nav experience
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Slices/Layout/_PagesNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_TableOfContents.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTree.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
Labels: enhancement

#811 Swap Elastic products and How-to guides in landing page
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
Labels: enhancement

#813 Remove custom spacing of lists
  src/Elastic.Markdown/Assets/markdown/list.css
Labels: fix, design

#812 Refactor and optimize htmx attributes
  src/Elastic.Markdown/Helpers/Htmx.cs
  src/Elastic.Markdown/Myst/Renderers/HtmxLinkInlineRenderer.cs
  src/Elastic.Markdown/Slices/Layout/_PrevNextNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTree.cshtml
  tests/Elastic.Markdown.Tests/Inline/AnchorLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/DirectiveBlockLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineAnchorTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineLinkTests.cs
Labels: enhancement

#820 Fix secondary nav htmx attributes
  src/Elastic.Markdown/Helpers/Htmx.cs
  src/Elastic.Markdown/Slices/Layout/_SecondaryNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTree.cshtml
Labels: fix

#821 Remove custom dataLayer push
  src/Elastic.Markdown/Assets/main.ts
Labels: fix

#824 Add footer and fix landing page layout
  src/Elastic.Markdown/Slices/Layout/_Footer.cshtml
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
  src/Elastic.Markdown/_static/logo-elastic-horizontal-white.svg
Labels: feature

#818 Update release notes nav
  src/docs-assembler/navigation.yml
Labels: documentation, changelog:skip

#822 Assembler: Inject global navigation into the build
  src/Elastic.Markdown/Assets/main.ts
  src/Elastic.Markdown/CrossLinks/CrossLinkResolver.cs
  src/Elastic.Markdown/DocumentationGenerator.cs
  src/Elastic.Markdown/IO/Configuration/ConfigurationFile.cs
  src/Elastic.Markdown/IO/Configuration/ITocItem.cs
  src/Elastic.Markdown/IO/Configuration/TableOfContentsConfiguration.cs
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/IO/Navigation/DocumentationGroup.cs
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  src/Elastic.Markdown/Myst/Renderers/HtmxLinkInlineRenderer.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Layout/_Breadcrumbs.cshtml
  src/Elastic.Markdown/Slices/Layout/_PrevNextNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTree.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
  src/docs-assembler/AssembleContext.cs
  src/docs-assembler/AssembleSources.cs
  src/docs-assembler/Building/AssemblerBuilder.cs
  src/docs-assembler/Building/PublishEnvironmentUriResolver.cs
  src/docs-assembler/Cli/RepositoryCommands.cs
  src/docs-assembler/Navigation/AssemblerDocumentationSet.cs
  src/docs-assembler/Navigation/GlobalNavigation.cs
  src/docs-assembler/Navigation/GlobalNavigationFile.cs
  src/docs-assembler/Navigation/GlobalNavigationHtmlWriter.cs
  src/docs-assembler/Navigation/GlobalNavigationPathProvider.cs
  src/docs-assembler/Sourcing/Checkout.cs
  src/docs-assembler/Sourcing/RepositorySourcesFetcher.cs
  src/docs-assembler/assembler.yml
  src/docs-assembler/navigation.yml
  src/docs-builder/Cli/Commands.cs
  tests/Elastic.Markdown.Tests/TestCrossLinkResolver.cs
  tests/authoring/Framework/Setup.fs
  tests/authoring/Framework/TestCrossLinkResolver.fs
  tests/docs-assembler.Tests/src/docs-assembler.Tests/GlobalNavigationTests.cs
Labels: feature

#827 Refine TOC validation logic and error messaging.
  src/Elastic.Markdown/IO/Configuration/TableOfContentsConfiguration.cs
Labels: fix

#828 Implement sitemap
  src/docs-assembler/Building/SitemapBuilder.cs
  src/docs-assembler/Cli/RepositoryCommands.cs
Labels: feature

#780 Update `navigation.yml`
  src/docs-assembler/AssembleSources.cs
  src/docs-assembler/Cli/RepositoryCommands.cs
  src/docs-assembler/Navigation/GlobalNavigationFile.cs
  src/docs-assembler/Navigation/GlobalNavigationHtmlWriter.cs
  src/docs-assembler/Navigation/GlobalNavigationPathProvider.cs
  src/docs-assembler/assembler.yml
  src/docs-assembler/navigation.yml
Labels: enhancement

#829 Adjust sitemap publish path
  src/docs-assembler/Building/SitemapBuilder.cs
Labels: fix

#831 Add ability to run workflow manually
  .github/workflows/preview-build.yml
Labels: automation

#832 Also add workflow_dispatch to link index steps
  .github/workflows/preview-build.yml
Labels: automation

#823 Fix anchor within details for non Chrome browsers
  src/Elastic.Markdown/Assets/main.ts
  src/Elastic.Markdown/Assets/open-details-with-anchor.ts
Labels: fix

#835 GlobalNavigationPathProvider: change definition for the newRelativePath
  src/docs-assembler/Navigation/GlobalNavigationPathProvider.cs
Labels: fix

#836 Quick cleanup: Address compiler hints
  src/Elastic.Markdown/BuildContext.cs
  src/Elastic.Markdown/Extensions/DetectionRules/DetectionRule.cs
  src/Elastic.Markdown/Extensions/DetectionRules/DetectionRulesDocsBuilderExtension.cs
  src/Elastic.Markdown/Helpers/Htmx.cs
  src/Elastic.Markdown/Helpers/Preloader.cs
  src/Elastic.Markdown/Myst/CodeBlocks/CodeBlockArguments.cs
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockHtmlRenderer.cs
  src/Elastic.Markdown/Myst/MarkdownParser.cs
  src/Elastic.Markdown/Myst/Renderers/HtmxLinkInlineRenderer.cs
  src/Elastic.Markdown/Slices/Layout/_Header.cshtml
  src/Elastic.Markdown/Slices/Layout/_PagesNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_SecondaryNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTree.cshtml
  src/docs-assembler/AssembleSources.cs
  src/docs-assembler/Building/AssemblerBuilder.cs
  src/docs-assembler/Cli/RepositoryCommands.cs
  src/docs-assembler/Configuration/AssemblyConfiguration.cs
  src/docs-assembler/Navigation/GlobalNavigationFile.cs
  src/docs-assembler/Navigation/GlobalNavigationHtmlWriter.cs
  src/docs-assembler/Sourcing/Checkout.cs
  src/docs-assembler/Sourcing/RepositorySourcesFetcher.cs
  src/docs-lambda-index-publisher/Program.cs
  tests/Elastic.Markdown.Tests/DocSet/LinkReferenceTests.cs
  tests/docs-assembler.Tests/src/docs-assembler.Tests/GlobalNavigationTests.cs
Labels: fix

#819 SEO optimized title
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Index.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
Labels: SEO, enhancement

#838 Also close pages switcher when clicking on the active item
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
  src/Elastic.Markdown/Slices/Layout/_SecondaryNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTree.cshtml
Labels: fix

#839 Reorder after reinjecting tree into global navigation
  src/docs-assembler/Navigation/GlobalNavigation.cs
  tests/docs-assembler.Tests/src/docs-assembler.Tests/GlobalNavigationTests.cs
Labels: fix

#817 Introduce a "Report an issue" link on documentation pages.
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Index.cshtml
  src/Elastic.Markdown/Slices/Layout/_TableOfContents.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
  src/docs-builder/Cli/Commands.cs
  src/docs-builder/Http/DocumentationWebHost.cs
Labels: feature

#840 Add Lambda build and release jobs to CI workflows
  .github/workflows/pr.yml
  .github/workflows/release.yml
  docs-builder.sln
  src/docs-assembler/Cli/LinkRegistryCommands.cs
  src/docs-assembler/Program.cs
  src/infra/docs-lambda-index-publisher/Program.cs
  src/infra/docs-lambda-index-publisher/README.md
  src/infra/docs-lambda-index-publisher/aws-lambda-tools-defaults.json
  src/infra/docs-lambda-index-publisher/docs-lambda-index-publisher.csproj
  src/infra/docs-lambda-index-publisher/lambda.DockerFile
Labels: ci

#842 Ensure we checkout before build/releasing our lamdba binary
  .github/workflows/release.yml
Labels: ci

#843 Protect against asciidoc headers
  src/Elastic.Markdown/IO/MarkdownFile.cs
Labels: fix

#844 Path prefix duplication detection in navigation.yml
  src/docs-assembler/Cli/PathPrefixCollisionCommand.cs
  src/docs-assembler/Cli/RepositoryCommands.cs
  src/docs-assembler/Navigation/GlobalNavigationFile.cs
  tests/docs-assembler.Tests/src/docs-assembler.Tests/GlobalNavigationTests.cs
Labels: fix

#849 Add local prefix validation action to solution
  actions/validate-path-prefixes-local/action.yml
  docs-builder.sln
Labels: ci

#856 404: Make clear it's linking to the docs home page
  src/Elastic.Markdown/Slices/Layout/_NotFound.cshtml
Labels: enhancement

#855 Remove image from landing page
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
Labels: enhancement

#850 Extend navigation validate command to check publish links
  .github/workflows/pr.yml
  src/Elastic.Markdown/DocumentationGenerator.cs
  src/Elastic.Markdown/Links/CrossLinks/ConfigurationCrossLinkFetcher.cs
  src/Elastic.Markdown/Links/CrossLinks/CrossLinkFetcher.cs
  src/Elastic.Markdown/Links/CrossLinks/CrossLinkResolver.cs
  src/Elastic.Markdown/Links/InboundLinks/LinkIndexCrossLinkFetcher.cs
  src/Elastic.Markdown/Links/InboundLinks/LinkIndexLinkChecker.cs
  src/Elastic.Markdown/Links/LinkNamespaces/LinkGlobalNamespaceChecker.cs
  src/docs-assembler/Building/AssemblerCrossLinkFetcher.cs
  src/docs-assembler/Building/PublishEnvironmentUriResolver.cs
  src/docs-assembler/Cli/NavigationCommands.cs
  src/docs-assembler/Links/NavigationPrefixChecker.cs
  src/docs-assembler/Navigation/GlobalNavigationFile.cs
  src/docs-assembler/assembler.yml
  src/docs-builder/Http/ReloadableGeneratorState.cs
  tests/Elastic.Markdown.Tests/Directives/DirectiveBaseTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlneBaseTests.cs
  tests/Elastic.Markdown.Tests/TestCrossLinkResolver.cs
  tests/authoring/Framework/TestCrossLinkResolver.fs
Labels: feature

#858 Add a modal for images to expand to upon being clicked instead of leaving the current page
  src/Elastic.Markdown/Assets/modal.css
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Slices/Directives/Image.cshtml
  src/Elastic.Markdown/Slices/Directives/_ViewModels.cs
Labels: enhancement

#860 Fix page switcher dropdown on safari
  src/Elastic.Markdown/Assets/styles.css
Labels: fix

#862 Keep track of navigation source on markdown files for easier root navigation lookups in assembler
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/IO/Navigation/DocumentationGroup.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/docs-assembler/Navigation/GlobalNavigationHtmlWriter.cs
Labels: fix

#861 Fix relative links
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  tests/authoring/Inline/RelativeLinks.fs
Labels: fix

#864 Optimize hljs
  docs/syntax/code.md
  src/Elastic.Markdown/Assets/hljs.ts
  src/Elastic.Markdown/Myst/CodeBlocks/SupportedLanguages.cs
  src/Elastic.Markdown/package-lock.json
  src/Elastic.Markdown/package.json
Labels: enhancement

#868 Add landing overview page for detection rules.
  src/Elastic.Markdown/Extensions/DetectionRules/DetectionRule.cs
  src/Elastic.Markdown/Extensions/DetectionRules/DetectionRuleFile.cs
  src/Elastic.Markdown/Extensions/DetectionRules/DetectionRulesDocsBuilderExtension.cs
  src/Elastic.Markdown/Extensions/DetectionRules/DetectionRulesReference.cs
  src/Elastic.Markdown/Extensions/IDocsBuilderExtension.cs
  src/Elastic.Markdown/IO/Configuration/TableOfContentsConfiguration.cs
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/Elastic.Markdown/IO/Navigation/DocumentationGroup.cs
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
Labels: feature

#867 Add anchors in landing page
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
Labels: enhancement

#871 Update landing page links
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
Labels: fix

#872 Set up eslint
  .github/workflows/pr.yml
  src/Elastic.Markdown/Assets/copybutton.css
  src/Elastic.Markdown/Assets/copybutton.ts
  src/Elastic.Markdown/Assets/hljs-merge-html-plugin.js
  src/Elastic.Markdown/Assets/hljs.ts
  src/Elastic.Markdown/Assets/main.ts
  src/Elastic.Markdown/Assets/tabs.ts
  src/Elastic.Markdown/eslint.config.mjs
  src/Elastic.Markdown/package-lock.json
  src/Elastic.Markdown/package.json
Labels: chore

#857 Add elastic/detection-rules to assembler navigation.yml
  src/Elastic.Markdown/Extensions/DetectionRules/DetectionRuleFile.cs
  src/Elastic.Markdown/Extensions/DetectionRules/DetectionRulesDocsBuilderExtension.cs
  src/Elastic.Markdown/Extensions/DetectionRules/DetectionRulesReference.cs
  src/Elastic.Markdown/IO/Configuration/TableOfContentsConfiguration.cs
  src/Elastic.Markdown/IO/Navigation/DocumentationGroup.cs
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
  src/docs-assembler/AssembleSources.cs
  src/docs-assembler/Building/PublishEnvironmentUriResolver.cs
  src/docs-assembler/Navigation/GlobalNavigationFile.cs
  src/docs-assembler/Navigation/GlobalNavigationPathProvider.cs
  src/docs-assembler/assembler.yml
  src/docs-assembler/navigation.yml
  tests/docs-assembler.Tests/src/docs-assembler.Tests/GlobalNavigationTests.cs
Labels: fix

#870 Pin dependencies and configure dependabot
  .github/dependabot.yml
  src/Elastic.Markdown/package-lock.json
  src/Elastic.Markdown/package.json
Labels: chore

#882 Correct landing page wording for the cloud account section
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
Labels: fix

#883 Set up prettier
  .editorconfig
  .github/workflows/pr.yml
  src/Elastic.Markdown/.prettierignore
  src/Elastic.Markdown/.prettierrc
  src/Elastic.Markdown/Assets/copybutton.css
  src/Elastic.Markdown/Assets/copybutton.ts
  src/Elastic.Markdown/Assets/fonts.css
  src/Elastic.Markdown/Assets/hljs-merge-html-plugin.js
  src/Elastic.Markdown/Assets/hljs.ts
  src/Elastic.Markdown/Assets/main.ts
  src/Elastic.Markdown/Assets/markdown/admonition.css
  src/Elastic.Markdown/Assets/markdown/code.css
  src/Elastic.Markdown/Assets/markdown/definition-list.css
  src/Elastic.Markdown/Assets/markdown/dropdown.css
  src/Elastic.Markdown/Assets/markdown/images.css
  src/Elastic.Markdown/Assets/markdown/list.css
  src/Elastic.Markdown/Assets/markdown/table.css
  src/Elastic.Markdown/Assets/markdown/tabs.css
  src/Elastic.Markdown/Assets/markdown/typography.css
  src/Elastic.Markdown/Assets/modal.css
  src/Elastic.Markdown/Assets/open-details-with-anchor.ts
  src/Elastic.Markdown/Assets/pages-nav.ts
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Assets/tabs.ts
  src/Elastic.Markdown/Assets/theme.css
  src/Elastic.Markdown/Assets/toc-nav.ts
  src/Elastic.Markdown/eslint.config.mjs
  src/Elastic.Markdown/package-lock.json
  src/Elastic.Markdown/package.json
Labels: chore

#884 Fix sub-path resolution in DiagnosticLinkInlineParser
  .github/workflows/smoke-test.yml
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
Labels: fix

#885 Only filter out detection rules that are within an '_deprecated' folder
  src/Elastic.Markdown/Extensions/DetectionRules/DetectionRulesDocsBuilderExtension.cs
Labels: fix

#888 Add extension method for relative path trimming when using ReadOnlySpan<char>
  src/docs-assembler/Building/PublishEnvironmentUriResolver.cs
  src/docs-assembler/Extensions/SpanExtensions.cs
  src/docs-assembler/Navigation/GlobalNavigationPathProvider.cs
Labels: fix
