Repository elastic/docs-builder, pull requests merged in 2025-01, with the labels that each got.

#144 Make .git folder optional so tool can be run on any folder
  src/Elastic.Markdown/IO/GitConfiguration.cs
Labels: bug

#165 Introduce toc.yml, allows toc's to be split one directory deep
  docs-builder.sln.DotSettings
  docs/source/development/index.md
  docs/source/development/toc.yml
  docs/source/docset.yml
  src/Elastic.Markdown/IO/ConfigurationFile.cs
  src/Elastic.Markdown/IO/DocumentationFolder.cs
  src/Elastic.Markdown/IO/ITocItem.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  tests/Elastic.Markdown.Tests/DocSet/BreadCrumbTests.cs
  tests/Elastic.Markdown.Tests/DocSet/LinkReferenceTests.cs
  tests/Elastic.Markdown.Tests/DocSet/NavigationTests.cs
  tests/Elastic.Markdown.Tests/DocSet/NavigationTestsBase.cs
  tests/Elastic.Markdown.Tests/DocSet/NestedTocTests.cs
Labels: authoring

#204 Fix _static folder required during release builds
  README.md
  actions/publish/github-pages.png
  docs-builder.sln
  docs/source/_static/examples/example-xpack.actions.customHostSettings.asciidoc.md
  docs/source/_static/templates/settings.jinja
  docs/source/_static/yaml/settings.yaml
  docs/source/syntax/images.md
  docs/source/syntax/img/apm.png
  docs/source/syntax/img/observability.png
  src/Elastic.Markdown/Myst/Directives/DirectiveBlockParser.cs
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  src/docs-builder/Http/DocumentationWebHost.cs
  tests/Elastic.Markdown.Tests/Directives/MermaidTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineImageTest.cs
Labels: fix

#206 Add "strict" mode to treat warnings as errors
  action.yml
  actions/publish/action.yml
  src/docs-builder/Cli/Commands.cs
Labels: bug

#205 Allow to manually trigger release-drafter
  .github/workflows/release-drafter.yml
Labels: ci

#200 Add reusable workflow and usage example
  .github/workflows/comment-on-asciidoc-changes.yml
  docs/source/migration/freeze/gh-action.md
Labels: ci

#207 Add update-link-index action
  actions/update-link-index/README.md
  actions/update-link-index/action.yml
Labels: feature

#212 Don't validate commented links
  docs/source/testing/index.md
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  tests/Elastic.Markdown.Tests/Inline/InlineLinkTests.cs
Labels: fix

#213 support private repository publishes
  actions/publish/action.yml
Labels: fix

#209 Support unique callouts for enhanced code blocks
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlock.cs
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockHtmlRenderer.cs
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockParser.cs
  tests/Elastic.Markdown.Tests/CodeBlocks/CallOutTests.cs
Labels: fix

#248 Fix update-link-index-action
  actions/update-link-index/action.yml
Labels: fix

#251 Add "Automation" section in release-drafter
  .github/release-drafter.yml
Labels: changelog:skip

#250 Add macos-latest-large runner to release
  .github/workflows/release.yml
Labels: automation

#252 Change target path of update-link-index action
  actions/update-link-index/action.yml
Labels: fix

#257 Keep navigation position when clicking through the documentation
  src/Elastic.Markdown/_static/shibuya.js
Labels: enhancement

#258 Add support for "previous" and "next" document navigation
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/IO/Navigation/DocumentationGroup.cs
  src/Elastic.Markdown/IO/State/LinkReference.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Index.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
Labels: fix

#264 Add `--allow-indexing` option for the generate command
  src/Elastic.Markdown/BuildContext.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Index.cshtml
  src/Elastic.Markdown/Slices/Layout/_Head.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
  src/docs-builder/Cli/Commands.cs
Labels: feature

#260 Fix link appearance in code
  src/Elastic.Markdown/_static/custom.css
Labels: fix

#259 Elastic docs v3 edits
  docs/source/migration/engineering.md
  docs/source/migration/freeze/gh-action.md
  docs/source/migration/freeze/index.md
  docs/source/migration/ia.md
  docs/source/migration/index.md
  docs/source/migration/syntax.md
  docs/source/migration/versioning.md
Labels: documentation

#273 add more pre-migrated content sets
  docs/source/migration/guide/index.md
Labels: documentation

#272 Fix "Full Changelog" link
  .github/release-drafter.yml
Labels: automation

#267 Fix README.md links
  README.md
Labels: documentation

#275 Add support for plain admonitions
  docs/source/syntax/admonitions.md
  src/Elastic.Markdown/Myst/Directives/AdmonitionBlock.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveBlockParser.cs
  src/Elastic.Markdown/_static/custom.css
  tests/Elastic.Markdown.Tests/Directives/AdmonitionTests.cs
  tests/Elastic.Markdown.Tests/Directives/AdmonitionUnsupportedTests.cs
Labels: feature

#276 Advertise docs-builder updates when running from command line
  src/docs-builder/Cli/CheckForUpdatesFilter.cs
  src/docs-builder/Cli/Commands.cs
  src/docs-builder/Program.cs
Labels: feature

#278 Refactor TOC processing to handle excluded and unreachable files
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/IO/Navigation/DocumentationGroup.cs
Labels: fix

#279 Add preview workflow
  .github/actions/aws-auth/action.yml
  .github/workflows/pr.yml
  .github/workflows/preview-cleanup.yml
  .github/workflows/preview.yml
Labels: automation

#332 Fix preview-cleanup
  .github/workflows/preview-cleanup.yml
Labels: automation

#333 Fix preview-cleanup
  .github/workflows/preview-cleanup.yml
Labels: automation

#334 Fix preview-cleanup pt3
  .github/workflows/preview-cleanup.yml
Labels: automation

#331 Add support for inline anchors in Markdown parsing
  docs/syntax/links.md
  src/Elastic.Markdown/Helpers/SlugExtensions.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/Myst/InlineParsers/HeadingBlockWithSlugParser.cs
  src/Elastic.Markdown/Myst/InlineParsers/InlineAnchorParser.cs
  src/Elastic.Markdown/Myst/MarkdownParser.cs
  src/Elastic.Markdown/Myst/SectionedHeadingRenderer.cs
  tests/Elastic.Markdown.Tests/Inline/InlineAnchorTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlneBaseTests.cs
Labels: feature

#290 Fix inline code in left navigation and h1 rendering
  src/Elastic.Markdown/Helpers/Markdown.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Index.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
Labels: fix

#340 Fix code snippet
  docs/migration/freeze/gh-action.md
Labels: documentation

#341 Caseinsensitive anchor link check
  src/Elastic.Markdown/IO/MarkdownFile.cs
Labels: fix

#342 Add custom UseHardBreaks extension
  src/Elastic.Markdown/Myst/InlineParsers/HardBreakParser.cs
  src/Elastic.Markdown/Myst/MarkdownParser.cs
  tests/Elastic.Markdown.Tests/Inline/HardBreakTests.cs
Labels: feature

#345 Fix indentation when code block is in a list
  docs/testing/index.md
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockHtmlRenderer.cs
Labels: fix

#344 New test project to make specification tests easier to write for developers
  docs-builder.sln
  docs-builder.sln.DotSettings
  tests/Elastic.Markdown.Tests/Inline/DirectiveBlockLinkTests.cs
  tests/authoring/Framework/ErrorCollectorAssertions.fs
  tests/authoring/Framework/HtmlAssertions.fs
  tests/authoring/Framework/Setup.fs
  tests/authoring/Framework/TestValues.fs
  tests/authoring/Inline/Comments.fs
  tests/authoring/Inline/InlineAnchors.fs
  tests/authoring/Inline/InlineImages.fs
  tests/authoring/Inline/Substitutions.fs
  tests/authoring/authoring.fsproj
Labels: ci

#346 Render callouts in code block
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockHtmlRenderer.cs
  src/Elastic.Markdown/Slices/Layout/_Scripts.cshtml
  src/Elastic.Markdown/_static/custom.css
  src/Elastic.Markdown/_static/hljs.js
Labels: fix

#348 Add support for vertical definition lists
  src/Elastic.Markdown/Myst/MarkdownParser.cs
  tests/authoring/Container/DefinitionLists.fs
  tests/authoring/authoring.fsproj
Labels: feature

#360 Fix rootFolder if `--path` is not defined
  src/Elastic.Markdown/BuildContext.cs
Labels: fix

#355 Allow multiple classic callouts in one line
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlock.cs
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockHtmlRenderer.cs
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockParser.cs
  src/Elastic.Markdown/_static/copybutton.js
  src/Elastic.Markdown/_static/custom.css
  tests/Elastic.Markdown.Tests/CodeBlocks/CallOutTests.cs
Labels: fix

#359 Add tests for nested and indented inline anchors
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/IO/Navigation/DocumentationGroup.cs
  src/Elastic.Markdown/Myst/MarkdownParser.cs
  tests/authoring/Framework/ErrorCollectorAssertions.fs
  tests/authoring/Framework/HtmlAssertions.fs
  tests/authoring/Framework/MarkdownDocumentAssertions.fs
  tests/authoring/Framework/TestValues.fs
  tests/authoring/Inline/InlineAnchors.fs
  tests/authoring/authoring.fsproj
Labels: fix

#338 Add basic content on what's needed to build docs with docs-builder
  docs/configure/content-set/attributes.md
  docs/configure/content-set/file-structure.md
  docs/configure/content-set/index.md
  docs/configure/content-set/navigation.md
  docs/configure/index.md
  docs/configure/page.md
  docs/configure/site/content.md
  docs/configure/site/index.md
  docs/configure/site/landing-page.md
  docs/configure/site/redirects.md
  docs/configure/site/shared-attributes.md
  docs/docset.yml
  docs/migration/guide/automated.md
  docs/migration/guide/bug-bash.md
  docs/migration/guide/index.md
  docs/migration/guide/tooling.md
  docs/syntax/frontmatter.md
  docs/syntax/line_breaks.md
  docs/syntax/titles.md
Labels: documentation

#365 Update comment-on-asciidoc-changes.yml
  .github/workflows/comment-on-asciidoc-changes.yml
  docs/migration/freeze/index.md
Labels: documentation

#357 Add error exit code if there are changes for the asciidoc comment workflow
  .github/workflows/comment-on-asciidoc-changes.yml
Labels: automation

#367 Optimize comment-on-asciidoc-changes.yml
  .github/workflows/comment-on-asciidoc-changes.yml
Labels: automation

#350 Make preview workflow reusable for other repositories
  .github/workflows/preview-cleanup.yml
  .github/workflows/preview.yml
Labels: feature

#368 Add repository input to checkout action in comment-on-asciidoc-changes workflow
  .github/workflows/comment-on-asciidoc-changes.yml
Labels: fix

#369 Update preview.yml
  .github/workflows/preview.yml
Labels: automation

#361 Allow _docset.yml and _toc.yml as configuration filenames
  src/Elastic.Markdown/BuildContext.cs
  src/Elastic.Markdown/IO/Configuration/ConfigurationFile.cs
  tests/authoring/Framework/Setup.fs
Labels: feature

#370 Add support for gif & jpeg images
  docs/syntax/images.md
  docs/syntax/img/alerts.svg
  docs/syntax/img/timeslider.gif
  src/Elastic.Markdown/IO/DocumentationSet.cs
Labels: feature

#371 Navigation: Set expand depth to 0
  src/Elastic.Markdown/Slices/Layout/_TocTree.cshtml
  src/Elastic.Markdown/_static/custom.css
Labels: enhancement

#374 Use GitHub API instead of git to check diff
  .github/workflows/comment-on-asciidoc-changes.yml
Labels: automation

#375 Support `console` family of code highlighters.
  docs/syntax/code.md
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlock.cs
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockHtmlRenderer.cs
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockParser.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveHtmlRenderer.cs
  src/Elastic.Markdown/Slices/Directives/Code.cshtml
  src/Elastic.Markdown/Slices/Directives/_ViewModels.cs
  src/Elastic.Markdown/Slices/Layout/_Scripts.cshtml
  src/Elastic.Markdown/_static/custom.css
  src/Elastic.Markdown/_static/custom.js
Labels: feature

#381 Add support for hidden files in documentation TOC
  docs/configure/content-set/navigation.md
  docs/developer-notes.md
  docs/docset.yml
  src/Elastic.Markdown/IO/Configuration/ConfigurationFile.cs
  src/Elastic.Markdown/IO/Configuration/ITocItem.cs
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/IO/Navigation/DocumentationGroup.cs
  src/Elastic.Markdown/IO/State/LinkReference.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Layout/_TocTree.cshtml
Labels: feature

#379 Add support for single paragraph between code and list
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockHtmlRenderer.cs
  tests/Elastic.Markdown.Tests/CodeBlocks/CallOutTests.cs
Labels: fix

#376 Add `docs-builder mv` command
  docs-builder.sln
  docs/docset.yml
  docs/testing/mover/first-page.md
  docs/testing/mover/second-page.md
  src/docs-builder/Cli/Commands.cs
  src/docs-builder/docs-builder.csproj
  src/docs-mover/Move.cs
  src/docs-mover/docs-mover.csproj
  tests/Elastic.Markdown.Tests/DocSet/NavigationTestsBase.cs
  tests/Elastic.Markdown.Tests/Elastic.Markdown.Tests.csproj
  tests/Elastic.Markdown.Tests/Mover/MoverTests.cs
Labels: feature

#382 Fix root links
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
Labels: fix

#377 Add warnings when a codeblock tries to use an unsupported language
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockParser.cs
  src/Elastic.Markdown/Myst/CodeBlocks/SupportedLanguages.cs
  tests/authoring/Blocks/CodeBlocks/CodeBlocks.fs
  tests/authoring/Framework/ErrorCollectorAssertions.fs
  tests/authoring/authoring.fsproj
Labels: fix

#383 Add move to target folder support to `mv` command
  src/docs-builder/Cli/Commands.cs
  src/docs-builder/Program.cs
  src/docs-mover/Move.cs
  tests/Elastic.Markdown.Tests/Mover/MoverTests.cs
Labels: feature

#384 Fix root links pt2
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
Labels: fix

#386 Glob against relative path, not filename
  src/Elastic.Markdown/IO/DocumentationSet.cs
Labels: fix

#385 Implement whole folder moves to the `mv` command
  src/docs-mover/Move.cs
  tests/Elastic.Markdown.Tests/Mover/MoverTests.cs
Labels: feature

#387 Refactor DiagnosticLinkInlineParser
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  tests/Elastic.Markdown.Tests/Inline/InlineLinkTests.cs
Labels: chore
