Repository elastic/docs-builder, pull requests merged in 2025-06, with the labels that each got.

#1227 Support cross-repository redirects and specialized anchor scenarios
  docs/contribute/redirects.md
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/Elastic.Markdown/Links/CrossLinks/CrossLinkResolver.cs
  src/Elastic.Markdown/Links/InboundLinks/LinkIndexLinkChecker.cs
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  src/Elastic.Markdown/Myst/Renderers/HtmxLinkInlineRenderer.cs
  tests/Elastic.Markdown.Tests/TestCrossLinkResolver.cs
  tests/authoring/Framework/CrossLinkResolverAssertions.fs
  tests/authoring/Framework/TestCrossLinkResolver.fs
  tests/authoring/Inline/CrossLinkRedirectAnchors.fs
  tests/authoring/Inline/CrossLinks.fs
  tests/authoring/authoring.fsproj
Labels: feature

#1335 Reproducible IDs
  src/Elastic.Markdown/Helpers/IdExtensions.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/IO/Navigation/DocumentationGroup.cs
  src/Elastic.Markdown/Slices/Directives/_ViewModels.cs
  src/Elastic.Markdown/Slices/Layout/_PagesNav.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
Labels: enhancement

#1353 Refactor markdown and layout rendering by decoupling from `GlobalLayoutViewModel`. Streamline layout handling, enhance navigation item visibility logic, and rework documentation file structures for improved maintainability.
  src/Elastic.ApiExplorer/Endpoints/ApiEndpoint.cs
  src/Elastic.ApiExplorer/Endpoints/EndpointView.cshtml
  src/Elastic.ApiExplorer/Landing/LandingNavigationItem.cs
  src/Elastic.ApiExplorer/Landing/LandingView.cshtml
  src/Elastic.ApiExplorer/Operations/OperationNavigationItem.cs
  src/Elastic.ApiExplorer/Operations/OperationView.cshtml
  src/Elastic.Documentation.Configuration/TableOfContents/ITocItem.cs
  src/Elastic.Documentation.Site/Layout/_Head.cshtml
  src/Elastic.Documentation.Site/Layout/_SecondaryNav.cshtml
  src/Elastic.Documentation.Site/Navigation/INavigationItem.cs
  src/Elastic.Documentation.Site/Navigation/_TocTreeNav.cshtml
  src/Elastic.Documentation.Site/_GlobalLayout.cshtml
  src/Elastic.Documentation.Site/_ViewModels.cs
  src/Elastic.Markdown/IO/DocumentationFile.cs
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/IO/Navigation/DocumentationGroup.cs
  src/Elastic.Markdown/Links/CrossLinks/CrossLinkFetcher.cs
  src/Elastic.Markdown/Myst/FrontMatter/FrontMatterParser.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Index.cshtml
  src/Elastic.Markdown/Slices/IndexViewModel.cs
  src/Elastic.Markdown/Slices/Layout/_Archive.cshtml
  src/Elastic.Markdown/Slices/Layout/_Breadcrumbs.cshtml
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
  src/Elastic.Markdown/Slices/Layout/_NotFound.cshtml
  src/Elastic.Markdown/Slices/Layout/_PrevNextNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_TableOfContents.cshtml
  src/Elastic.Markdown/Slices/LayoutName.cs
  src/Elastic.Markdown/Slices/MarkdownLayoutViewModel.cs
  src/Elastic.Markdown/Slices/_Layout.cshtml
  src/Elastic.Markdown/Slices/_ViewImports.cshtml
  src/authoring/Elastic.Documentation.Refactor/Move.cs
  src/tooling/docs-assembler/AssembleSources.cs
  src/tooling/docs-assembler/Cli/RepositoryCommands.cs
  src/tooling/docs-assembler/Navigation/GlobalNavigation.cs
  src/tooling/docs-assembler/Navigation/GlobalNavigationFile.cs
  src/tooling/docs-assembler/Navigation/GlobalNavigationHtmlWriter.cs
  src/tooling/docs-assembler/navigation.yml
  src/tooling/docs-builder/Cli/Commands.cs
  src/tooling/docs-builder/Http/DocumentationWebHost.cs
  tests/docs-assembler.Tests/src/docs-assembler.Tests/GlobalNavigationTests.cs
Labels: chore

#1356 Revert "Refactor markdown and layout rendering by decoupling from `GlobalLayoutViewModel`. Streamline layout handling, enhance navigation item visibility logic, and rework documentation file structures for improved maintainability."
  src/Elastic.ApiExplorer/Endpoints/ApiEndpoint.cs
  src/Elastic.ApiExplorer/Endpoints/EndpointView.cshtml
  src/Elastic.ApiExplorer/Landing/LandingNavigationItem.cs
  src/Elastic.ApiExplorer/Landing/LandingView.cshtml
  src/Elastic.ApiExplorer/Operations/OperationNavigationItem.cs
  src/Elastic.ApiExplorer/Operations/OperationView.cshtml
  src/Elastic.Documentation.Configuration/TableOfContents/ITocItem.cs
  src/Elastic.Documentation.Site/Layout/_Archive.cshtml
  src/Elastic.Documentation.Site/Layout/_Head.cshtml
  src/Elastic.Documentation.Site/Layout/_LandingPage.cshtml
  src/Elastic.Documentation.Site/Layout/_NotFound.cshtml
  src/Elastic.Documentation.Site/Layout/_SecondaryNav.cshtml
  src/Elastic.Documentation.Site/LayoutName.cs
  src/Elastic.Documentation.Site/Navigation/INavigationItem.cs
  src/Elastic.Documentation.Site/Navigation/_TocTreeNav.cshtml
  src/Elastic.Documentation.Site/_GlobalLayout.cshtml
  src/Elastic.Documentation.Site/_ViewModels.cs
  src/Elastic.Markdown/IO/DocumentationFile.cs
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/IO/Navigation/DocumentationGroup.cs
  src/Elastic.Markdown/Links/CrossLinks/CrossLinkFetcher.cs
  src/Elastic.Markdown/Myst/FrontMatter/FrontMatterParser.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Index.cshtml
  src/Elastic.Markdown/Slices/IndexViewModel.cs
  src/Elastic.Markdown/Slices/Layout/_Breadcrumbs.cshtml
  src/Elastic.Markdown/Slices/Layout/_PrevNextNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_TableOfContents.cshtml
  src/Elastic.Markdown/Slices/MarkdownLayoutViewModel.cs
  src/Elastic.Markdown/Slices/_Layout.cshtml
  src/Elastic.Markdown/Slices/_ViewImports.cshtml
  src/authoring/Elastic.Documentation.Refactor/Move.cs
  src/tooling/docs-assembler/AssembleSources.cs
  src/tooling/docs-assembler/Cli/RepositoryCommands.cs
  src/tooling/docs-assembler/Navigation/GlobalNavigation.cs
  src/tooling/docs-assembler/Navigation/GlobalNavigationFile.cs
  src/tooling/docs-assembler/Navigation/GlobalNavigationHtmlWriter.cs
  src/tooling/docs-assembler/navigation.yml
  src/tooling/docs-builder/Cli/Commands.cs
  src/tooling/docs-builder/Http/DocumentationWebHost.cs
  tests/docs-assembler.Tests/src/docs-assembler.Tests/GlobalNavigationTests.cs
Labels: changelog:skip

#1346 Publish logstash docs from the 9.0 branch
  src/tooling/docs-assembler/assembler.yml
Labels: ci

#1359 Add new product to product list
  docs/syntax/frontmatter.md
  src/Elastic.Documentation.Configuration/Builder/Products.cs
Labels: enhancement

#1357 Refactor navigation further to be less reliant on markdown properties.
  src/Elastic.ApiExplorer/Endpoints/ApiEndpoint.cs
  src/Elastic.ApiExplorer/Endpoints/EndpointView.cshtml
  src/Elastic.ApiExplorer/Landing/LandingNavigationItem.cs
  src/Elastic.ApiExplorer/Landing/LandingView.cshtml
  src/Elastic.ApiExplorer/Operations/OperationNavigationItem.cs
  src/Elastic.ApiExplorer/Operations/OperationView.cshtml
  src/Elastic.Documentation.Configuration/TableOfContents/ITocItem.cs
  src/Elastic.Documentation.Site/Layout/_Head.cshtml
  src/Elastic.Documentation.Site/Layout/_SecondaryNav.cshtml
  src/Elastic.Documentation.Site/Navigation/INavigationItem.cs
  src/Elastic.Documentation.Site/Navigation/_TocTreeNav.cshtml
  src/Elastic.Documentation.Site/_GlobalLayout.cshtml
  src/Elastic.Documentation.Site/_ViewModels.cs
  src/Elastic.Markdown/IO/DocumentationFile.cs
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/IO/Navigation/DocumentationGroup.cs
  src/Elastic.Markdown/Links/CrossLinks/CrossLinkFetcher.cs
  src/Elastic.Markdown/Myst/FrontMatter/FrontMatterParser.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Index.cshtml
  src/Elastic.Markdown/Slices/IndexViewModel.cs
  src/Elastic.Markdown/Slices/Layout/_Archive.cshtml
  src/Elastic.Markdown/Slices/Layout/_Breadcrumbs.cshtml
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
  src/Elastic.Markdown/Slices/Layout/_NotFound.cshtml
  src/Elastic.Markdown/Slices/Layout/_PrevNextNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_TableOfContents.cshtml
  src/Elastic.Markdown/Slices/LayoutName.cs
  src/Elastic.Markdown/Slices/MarkdownLayoutViewModel.cs
  src/Elastic.Markdown/Slices/_Layout.cshtml
  src/Elastic.Markdown/Slices/_ViewImports.cshtml
  src/authoring/Elastic.Documentation.Refactor/Move.cs
  src/tooling/docs-assembler/AssembleSources.cs
  src/tooling/docs-assembler/Cli/RepositoryCommands.cs
  src/tooling/docs-assembler/Navigation/GlobalNavigation.cs
  src/tooling/docs-assembler/Navigation/GlobalNavigationFile.cs
  src/tooling/docs-assembler/Navigation/GlobalNavigationHtmlWriter.cs
  src/tooling/docs-assembler/navigation.yml
  src/tooling/docs-builder/Cli/Commands.cs
  src/tooling/docs-builder/Http/DocumentationWebHost.cs
  tests/authoring/Generator/LinkReferenceFile.fs
  tests/docs-assembler.Tests/src/docs-assembler.Tests/GlobalNavigationTests.cs
Labels: fix

#1361 Add new version drop down feature flag and enhance existing version dropdown
  src/Elastic.ApiExplorer/Endpoints/EndpointView.cshtml
  src/Elastic.ApiExplorer/Landing/LandingView.cshtml
  src/Elastic.ApiExplorer/Operations/OperationView.cshtml
  src/Elastic.Documentation.Configuration/Assembler/AssemblyConfiguration.cs
  src/Elastic.Documentation.Configuration/Assembler/VersionEntry.cs
  src/Elastic.Documentation.Configuration/Builder/FeatureFlags.cs
  src/Elastic.Documentation.Configuration/Serialization/YamlStaticContext.cs
  src/Elastic.Documentation.Site/Assets/main.ts
  src/Elastic.Documentation.Site/Assets/web-components/VersionDropdown.tsx
  src/Elastic.Documentation.Site/Htmx.cs
  src/Elastic.Documentation.Site/Layout/_SecondaryNav.cshtml
  src/Elastic.Documentation.Site/_ViewModels.cs
  src/Elastic.Documentation.Site/package-lock.json
  src/Elastic.Documentation.Site/package.json
  src/Elastic.Documentation/Legacy/ILegacyUrlMapper.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Index.cshtml
  src/Elastic.Markdown/Slices/IndexViewModel.cs
  src/Elastic.Markdown/Slices/Layout/_TableOfContents.cshtml
  src/Elastic.Markdown/Slices/MarkdownLayoutViewModel.cs
  src/tooling/docs-assembler/AssembleSources.cs
  src/tooling/docs-assembler/Legacy/PageLegacyUrlMapper.cs
  src/tooling/docs-assembler/assembler.yml
  src/tooling/docs-assembler/legacy-url-mappings.yml
  tests/Elastic.Markdown.Tests/Inline/AnchorLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/DirectiveBlockLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineAnchorTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineLinkTests.cs
Labels: enhancement

#1084 Adjust log emit level to Warning for image out of content scope
  src/Elastic.Markdown/Myst/Directives/ImageBlock.cs
Labels: fix

#1326 Update links.md to add reference-style links
  docs/syntax/links.md
Labels: documentation

#1090 Update images.md
  docs/syntax/images.md
Labels: documentation

#1365 Add cloud-enterprise legacy mapping
  src/tooling/docs-assembler/legacy-url-mappings.yml
Labels: fix

#1324 Adds cumulative docs contribution overview
  docs/contribute/index.md
Labels: documentation

#1383 Fix dropdown notice pt2
  src/tooling/docs-assembler/Legacy/PageLegacyUrlMapper.cs
Labels: fix

#1388 Add current version meta tag
  src/Elastic.Markdown/Slices/Index.cshtml
Labels: enhancement

#1401 New version dropdown: Change "View all versions" to "View other versions"
  src/Elastic.Documentation.Site/Assets/web-components/VersionDropdown.tsx
Labels: fix

#1402 Remove VersionDropdown feature flag, which enables it by default
  src/Elastic.Documentation.Configuration/Builder/FeatureFlags.cs
  src/Elastic.Documentation.Site/Htmx.cs
  src/Elastic.Markdown/Slices/Layout/_TableOfContents.cshtml
  src/tooling/docs-assembler/assembler.yml
  tests/Elastic.Markdown.Tests/Inline/AnchorLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/DirectiveBlockLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineAnchorTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineLinkTests.cs
Labels: feature

#1418 Update `NavigationPrefixChecker` to skip phantom paths during link resolution.
  src/tooling/docs-assembler/Links/NavigationPrefixChecker.cs
Labels: fix

#1420 Use `content_soure: current` for edge environment
  src/tooling/docs-assembler/assembler.yml
Labels: ci

#1424 NPM: Update and pin versions
  src/Elastic.Documentation.Site/package-lock.json
  src/Elastic.Documentation.Site/package.json
Labels: chore

#1425 Dependabot: Group EUI packages
  .github/dependabot.yml
Labels: chore

#1430 Update assertions to use new HTML assertions for improved legibility and error messages
  tests/Elastic.Markdown.Tests/CodeBlocks/CallOutTests.cs
  tests/Elastic.Markdown.Tests/FileInclusion/IncludeTests.cs
  tests/Elastic.Markdown.Tests/Inline/AnchorLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/CommentTest.cs
  tests/Elastic.Markdown.Tests/Inline/DirectiveBlockLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/HardBreakTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineAnchorTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineImageTest.cs
  tests/Elastic.Markdown.Tests/Inline/InlineLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/SubstitutionTest.cs
  tests/Elastic.Markdown.Tests/PrettyHtmlExtensions.cs
Labels: chore

#1432 Remove deprecated `legacy_versions` property
  src/Elastic.Documentation.Configuration/Assembler/VersionEntry.cs
Labels: chore

#1431 Remove mention of `discontinued` lifecycle
  docs/versions/content-patterns.md
Labels: documentation

#1439 Update DetectionRules title
  src/Elastic.Markdown/Extensions/DetectionRules/DetectionRuleFile.cs
Labels: fix

#1440 Fix typo in sitemap namespace declaration
  src/tooling/docs-assembler/Building/SitemapBuilder.cs
Labels: fix

#1442 Simplify version dropdown messaging for external users
  src/Elastic.Documentation.Site/Assets/web-components/VersionDropdown.tsx
Labels: bug

#1441 Include Documentation Group index urls in sitemap
  src/Elastic.Markdown/IO/Navigation/FileNavigationItem.cs
  src/tooling/docs-assembler/Building/SitemapBuilder.cs
Labels: fix

#1446 Fix `applies_to` docs syntax error in examples
  docs/syntax/applies.md
Labels: documentation

#1449 Update ApplicableToComponent.cshtml
  src/Elastic.Markdown/Myst/Components/ApplicableToComponent.cshtml
Labels: enhancement

#1447 Clarify links.md
  docs/syntax/links.md
Labels: documentation

#1452 Update legacy-url-mappings.yml
  src/tooling/docs-assembler/legacy-url-mappings.yml
Labels: fix

#1454 Ensure landing page, not found page and 2nd level nav links are not boosted
  src/Elastic.Documentation.Site/Layout/_SecondaryNav.cshtml
  src/Elastic.Markdown/Layout/_LandingPage.cshtml
  src/Elastic.Markdown/Layout/_NotFound.cshtml
Labels: fix

#1457 Disable HTMX on WrappedTables
  src/Elastic.Markdown/Myst/Renderers/WrappedTableRenderer.cs
Labels: fix

#1458 Fix crosslinks
  src/Elastic.Markdown/Myst/Renderers/HtmxLinkInlineRenderer.cs
  src/Elastic.Markdown/Myst/Renderers/WrappedTableRenderer.cs
  tests/Elastic.Markdown.Tests/Inline/InlineLinkTests.cs
Labels: fix

#1461 Fix `applies_to` rendering
  src/Elastic.Markdown/Myst/Components/ApplicableToComponent.cshtml
  tests/authoring/Inline/AppliesToRole.fs
Labels: fix

#1459 Darker admonition title color for higher contrast
  src/Elastic.Documentation.Site/Assets/markdown/admonition.css
Labels: fix

#1468 Update preview-build.yml
  .github/workflows/preview-build.yml
Labels: changelog:skip

#1463 Fix rendering of `DC.identifier` and `product_version` meta tag
  src/Elastic.Markdown/Page/Index.cshtml
Labels: fix

#1470 Update locally.md
  docs/contribute/locally.md
Labels: documentation

#1472 Add semantic headings to stepper component
  docs/syntax/stepper.md
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveHtmlRenderer.cs
  src/Elastic.Markdown/Myst/Directives/Stepper/StepView.cshtml
  src/Elastic.Markdown/Myst/Directives/Stepper/StepViewModel.cs
  src/Elastic.Markdown/Myst/Directives/Stepper/StepperBlock.cs
Labels: enhancement

#1471 Use `@elastic/highlightjs-esql` instead of custom implementation
  src/Elastic.Documentation.Site/Assets/hljs.ts
  src/Elastic.Documentation.Site/package-lock.json
  src/Elastic.Documentation.Site/package.json
Labels: chore

#1482 Update locally.md
  docs/contribute/locally.md
Labels: bug
