Repository elastic/docs-builder, pull requests merged in 2025-02, with the labels that each got.

#390 Add `./build.sh watch` to integrate all continuous builds.
  README.md
  build/CommandLine.fs
  build/Targets.fs
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Elastic.Markdown.csproj
  src/docs-builder/Http/DocumentationWebHost.cs
  src/docs-builder/Http/ParcelWatchService.cs
Labels: feature

#389 Set up parceljs
  .github/actions/bootstrap/action.yml
  .nvmrc
  README.md
  build/CommandLine.fs
  build/Targets.fs
  src/Elastic.Markdown/.gitignore
  src/Elastic.Markdown/Assets/legacy/atom-one-light.css
  src/Elastic.Markdown/Assets/legacy/copybutton.css
  src/Elastic.Markdown/Assets/legacy/custom.css
  src/Elastic.Markdown/Assets/legacy/mystnb.css
  src/Elastic.Markdown/Assets/legacy/pygments.css
  src/Elastic.Markdown/Assets/legacy/shibuya.css
  src/Elastic.Markdown/Assets/legacy/sphinx-design.min.css
  src/Elastic.Markdown/Assets/legacy/togglebutton.css
  src/Elastic.Markdown/Assets/main.js
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Elastic.Markdown.csproj
  src/Elastic.Markdown/Slices/Layout/_Head.cshtml
  src/Elastic.Markdown/Slices/Layout/_Scripts.cshtml
  src/Elastic.Markdown/package-lock.json
  src/Elastic.Markdown/package.json
  src/docs-builder/Http/DocumentationWebHost.cs
  src/docs-builder/Http/ParcelWatchService.cs
Labels: chore

#393 Add explicit continue-on-error input to the preview workflow
  .github/workflows/preview.yml
  actions/publish/action.yml
Labels: fix

#394 Also add error message to the workflow log
  .github/workflows/comment-on-asciidoc-changes.yml
Labels: enhancement

#392 Add redesign feature flag
  src/Elastic.Markdown/.postcssrc
  src/Elastic.Markdown/Assets/hljs-merge-html-plugin.js
  src/Elastic.Markdown/Assets/main.js
  src/Elastic.Markdown/Assets/markdown/typography.css
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Assets/theme.css
  src/Elastic.Markdown/Slices/Layout/_Head.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
  src/Elastic.Markdown/_static/atom-one-light.css
  src/Elastic.Markdown/_static/copybutton.css
  src/Elastic.Markdown/_static/custom.css
  src/Elastic.Markdown/_static/mystnb.css
  src/Elastic.Markdown/_static/pygments.css
  src/Elastic.Markdown/_static/shibuya.css
  src/Elastic.Markdown/_static/sphinx-design.min.css
  src/Elastic.Markdown/_static/togglebutton.css
  src/Elastic.Markdown/package-lock.json
  src/Elastic.Markdown/package.json
Labels: feature

#406 New "safe" preview deployment workflows
  .github/workflows/pr.yml
  .github/workflows/preview-build.yml
  .github/workflows/preview-cleanup.yml
  .github/workflows/preview-deploy.yml
Labels: feature

#407 Preview builds optimizations
  .github/workflows/preview-build.yml
  .github/workflows/preview-deploy.yml
Labels: enhancement

#408 Fix deploy preview workflow
  .github/workflows/preview-deploy.yml
Labels: fix

#398 Add support for image sizing via titles in markdown
  docs/syntax/images.md
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  tests/authoring/Inline/InlineImages.fs
Labels: feature

#410 Fix extra whitespace in code block
  src/Elastic.Markdown/Slices/Directives/Code.cshtml
Labels: fix

#414 Update syntax guide about comments
  docs/docset.yml
  docs/syntax/comments.md
  docs/syntax/sundries.md
Labels: documentation

#416 Migration and Syntax docs updates
  docs/contribute/move.md
  docs/docset.yml
  docs/migration/engineering.md
  docs/migration/guide/automated.md
  docs/migration/guide/bug-bash.md
  docs/migration/guide/file-structure.md
  docs/migration/guide/index.md
  docs/migration/guide/mapping.md
  docs/migration/guide/tooling.md
  docs/migration/guide/working-in-docs-content.md
  docs/migration/index.md
  docs/migration/versioning.md
  docs/syntax/admonitions.md
  docs/syntax/applies.md
  docs/syntax/code.md
  docs/syntax/comments.md
  docs/syntax/conditionals.md
  docs/syntax/dropdowns.md
  docs/syntax/example_blocks.md
  docs/syntax/frontmatter.md
  docs/syntax/index.md
  docs/syntax/md-extensions.md
  docs/syntax/passthrough.md
  docs/syntax/sidebars.md
  docs/syntax/sundries.md
  docs/syntax/tabs.md
  docs/syntax/tagged_regions.md
Labels: documentation

#421 Fix nested directives within a list
  src/Elastic.Markdown/Myst/Directives/DirectiveBlockParser.cs
  tests/Elastic.Markdown.Tests/Directives/AdmonitionTests.cs
  tests/Elastic.Markdown.Tests/Directives/DirectiveBaseTests.cs
Labels: fix

#422 Add path-pattern input to preview-build.yml workflow
  .github/workflows/preview-build.yml
  .github/workflows/preview-cleanup.yml
  .github/workflows/preview-deploy.yml
Labels: feature

#423 Add docs preview setup guide
  docs/docset.yml
  docs/migration/guide/how-to-set-up-docs-previews.md
  docs/migration/guide/img/docs-preview-deployment.png
  docs/migration/guide/img/docs-preview-required-status-check.png
Labels: documentation

#415 Update linking syntax page
  docs/syntax/links.md
  docs/syntax/titles.md
Labels: documentation

#429 Update substitutions.md
  docs/syntax/substitutions.md
Labels: documentation

#446 Make comment-on-asciidoc-changes.yml scarier
  .github/workflows/comment-on-asciidoc-changes.yml
Labels: enhancement

#455 Improve safety of callout handling in EnhancedCodeBlockParser.
  src/Elastic.Markdown/DocumentationGenerator.cs
  src/Elastic.Markdown/Myst/CodeBlocks/CallOutParser.cs
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockParser.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
Labels: fix

#454 Fix exception handling regression: fallback to ConsoleAppFramework
  src/docs-assembler/Cli/Filters.cs
  src/docs-builder/Cli/Filters.cs
Labels: fix

#435 Fix lists continuations.
  docs/syntax/applies.md
  src/Elastic.Markdown/Myst/Comments/CommentBlockParser.cs
  src/Elastic.Markdown/Myst/MarkdownParser.cs
  tests/Elastic.Markdown.Tests/Directives/AdmonitionTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineAnchorTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineLinkTests.cs
  tests/authoring/Blocks/Lists.fs
  tests/authoring/Container/DefinitionLists.fs
  tests/authoring/authoring.fsproj
Labels: fix

#442 Fix relative links
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  tests/Elastic.Markdown.Tests/Inline/AnchorLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/DirectiveBlockLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineAnchorTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineImageTest.cs
  tests/Elastic.Markdown.Tests/Inline/InlineLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlneBaseTests.cs
  tests/authoring/Inline/InlineImages.fs
Labels: fix

#436 redesign: Add header and breadcrumbs
  .github/release-drafter.yml
  .github/workflows/preview-build.yml
  .github/workflows/preview-deploy.yml
  src/Elastic.Markdown/.gitignore
  src/Elastic.Markdown/Assets/fonts.css
  src/Elastic.Markdown/Assets/fonts/MierB-Regular.woff2
  src/Elastic.Markdown/Assets/main.ts
  src/Elastic.Markdown/Assets/markdown/typography.css
  src/Elastic.Markdown/Assets/plugins.css
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Assets/theme.css
  src/Elastic.Markdown/Elastic.Markdown.csproj
  src/Elastic.Markdown/Slices/_Layout.cshtml
  src/Elastic.Markdown/_static/logo-elastic-horizontal-color-reverse.svg
  src/Elastic.Markdown/package-lock.json
  src/Elastic.Markdown/package.json
Labels: automation, redesign

#458 Support variables in table of contents.
  docs/testing/nested/index.md
  src/Elastic.Markdown/Helpers/Interpolation.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
Labels: fix

#460 Add ability to deploy from main
  .github/workflows/preview-build.yml
  .github/workflows/preview-deploy.yml
  docs/migration/guide/how-to-set-up-docs-previews.md
Labels: automation

#461 Fix PR preview
  .github/workflows/preview-build.yml
Labels: automation

#459 Support substitutions in directive titles (admonitions, tabs)
  docs/syntax/_snippets/reusable-snippet.md
  docs/testing/nested/index.md
  src/Elastic.Markdown/Helpers/Interpolation.cs
  src/Elastic.Markdown/Myst/Directives/AdmonitionBlock.cs
  src/Elastic.Markdown/Myst/Directives/TabSetBlock.cs
  src/Elastic.Markdown/Myst/ParserContext.cs
  src/Elastic.Markdown/Myst/Substitution/SubstitutionParser.cs
Labels: fix

#463 Ensure `authoring` test project reports properly on Github Actions
  tests/Elastic.Markdown.Tests/CodeBlocks/CallOutTests.cs
  tests/Elastic.Markdown.Tests/CodeBlocks/CodeTests.cs
  tests/Elastic.Markdown.Tests/Directives/AdmonitionTests.cs
  tests/Elastic.Markdown.Tests/Directives/AdmonitionUnsupportedTests.cs
  tests/Elastic.Markdown.Tests/Directives/AppliesBlockTests.cs
  tests/Elastic.Markdown.Tests/Directives/DirectiveBaseTests.cs
  tests/Elastic.Markdown.Tests/Directives/ImageTests.cs
  tests/Elastic.Markdown.Tests/Directives/MermaidTests.cs
  tests/Elastic.Markdown.Tests/Directives/TabTests.cs
  tests/Elastic.Markdown.Tests/Directives/UnsupportedTests.cs
  tests/Elastic.Markdown.Tests/Directives/VersionTests.cs
  tests/Elastic.Markdown.Tests/DocSet/BreadCrumbTests.cs
  tests/Elastic.Markdown.Tests/DocSet/LinkReferenceTests.cs
  tests/Elastic.Markdown.Tests/DocSet/NavigationTests.cs
  tests/Elastic.Markdown.Tests/DocSet/NavigationTestsBase.cs
  tests/Elastic.Markdown.Tests/DocSet/NestedTocTests.cs
  tests/Elastic.Markdown.Tests/Elastic.Markdown.Tests.csproj
  tests/Elastic.Markdown.Tests/FileInclusion/IncludeTests.cs
  tests/Elastic.Markdown.Tests/FileInclusion/LiteralIncludeTests.cs
  tests/Elastic.Markdown.Tests/FrontMatter/ProductConstraintTests.cs
  tests/Elastic.Markdown.Tests/FrontMatter/YamlFrontMatterTests.cs
  tests/Elastic.Markdown.Tests/Inline/AnchorLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/CommentTest.cs
  tests/Elastic.Markdown.Tests/Inline/DirectiveBlockLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/HardBreakTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineAnchorTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineImageTest.cs
  tests/Elastic.Markdown.Tests/Inline/InlineLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlneBaseTests.cs
  tests/Elastic.Markdown.Tests/Inline/SubstitutionTest.cs
  tests/Elastic.Markdown.Tests/Mover/MoverTests.cs
  tests/Elastic.Markdown.Tests/OutputDirectoryTests.cs
  tests/Elastic.Markdown.Tests/SettingsInclusion/IncludeTests.cs
  tests/Elastic.Markdown.Tests/TestDiagnosticsCollector.cs
  tests/Elastic.Markdown.Tests/TestLogger.cs
  tests/authoring/authoring.fsproj
Labels: chore

#274 Add support for extensionless URLs (pretty URLs)
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/docs-builder/Http/DocumentationWebHost.cs
  tests/Elastic.Markdown.Tests/Inline/AnchorLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/DirectiveBlockLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineAnchorTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineLinkTests.cs
Labels: feature

#464 Allow `mailto` scheme in inline links
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  tests/authoring/Framework/ErrorCollectorAssertions.fs
  tests/authoring/Framework/Setup.fs
  tests/authoring/Inline/InlineLinks.fs
  tests/authoring/authoring.fsproj
Labels: fix

#466 Remove docs-generator since we don't really use this tool
  README.md
  build/Targets.fs
  docs-builder.sln
  src/docs-generator/Cli/Commands.cs
  src/docs-generator/Domain/Determinism.cs
  src/docs-generator/Domain/Generators.cs
  src/docs-generator/Domain/MarkdownFile.cs
  src/docs-generator/Domain/Path.cs
  src/docs-generator/Domain/Section.cs
  src/docs-generator/Program.cs
  src/docs-generator/docs-generator.csproj
Labels: chore

#467 Rename docs-mover to Elastic.Markdown.Refactor
  docs-builder.sln
  src/Elastic.Markdown.Refactor/Elastic.Markdown.Refactor.csproj
  src/Elastic.Markdown.Refactor/Move.cs
  src/docs-builder/Cli/Commands.cs
  src/docs-builder/docs-builder.csproj
  src/docs-mover/docs-mover.csproj
  tests/Elastic.Markdown.Tests/Elastic.Markdown.Tests.csproj
  tests/Elastic.Markdown.Tests/Mover/MoverTests.cs
Labels: chore

#447 Add pages navigation
  docs/docset.yml
  docs/testing/deeply-nested/bar.md
  docs/testing/deeply-nested/baz/qux.md
  docs/testing/deeply-nested/foo.md
  docs/testing/deeply-nested/index.md
  src/Elastic.Markdown/Assets/fonts.css
  src/Elastic.Markdown/Assets/fonts/InterVariable.woff2
  src/Elastic.Markdown/Assets/fonts/MierB-Bold.woff2
  src/Elastic.Markdown/Assets/fonts/MierB-Demi.woff2
  src/Elastic.Markdown/Assets/hljs.ts
  src/Elastic.Markdown/Assets/main.ts
  src/Elastic.Markdown/Assets/pages-nav.ts
  src/Elastic.Markdown/Assets/plugins.css
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Helpers/BoolExtensions.cs
  src/Elastic.Markdown/IO/Navigation/DocumentationGroup.cs
  src/Elastic.Markdown/Slices/Layout/_Breadcrumbs.cshtml
  src/Elastic.Markdown/Slices/Layout/_Header.cshtml
  src/Elastic.Markdown/Slices/Layout/_PagesNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTree.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
  src/Elastic.Markdown/package-lock.json
  src/Elastic.Markdown/package.json
Labels: redesign

#468 Fix deployment cache invaldation
  .github/workflows/preview-deploy.yml
Labels: automation

#472 Rework preview deployment workflows
  .github/workflows/preview-build.yml
  .github/workflows/preview-cleanup.yml
  .github/workflows/preview-deploy.yml
  docs/migration/guide/how-to-set-up-docs-previews.md
Labels: automation

#476 Fix new compilation errors introduced in 9.0.200
  build/CommandLine.fs
  build/build.fsproj
  src/Elastic.Markdown/Diagnostics/DiagnosticsChannel.cs
  tests/authoring/Framework/ErrorCollectorAssertions.fs
Labels: chore

#478 Version docs
  docs/docset.yml
  docs/versions/_snippets/content-patterns-list.md
  docs/versions/content-patterns.md
  docs/versions/index.md
Labels: documentation

#479 Add more prose use cases
  docs/versions/_snippets/content-patterns-list.md
  docs/versions/content-patterns.md
Labels: documentation

#481 update contributor guide
  docs/contribute/index.md
  docs/contribute/locally.md
  docs/docset.yml
Labels: documentation

#480 Fix preview build workflow
  .github/workflows/preview-build.yml
Labels: automation

#477 redesign: Add table of contents
  src/Elastic.Markdown/Assets/main.ts
  src/Elastic.Markdown/Assets/markdown/list.css
  src/Elastic.Markdown/Assets/markdown/typography.css
  src/Elastic.Markdown/Assets/pages-nav.ts
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Assets/toc-nav.ts
  src/Elastic.Markdown/Elastic.Markdown.csproj
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/Slices/Index.cshtml
  src/Elastic.Markdown/Slices/Layout/_Breadcrumbs.cshtml
  src/Elastic.Markdown/Slices/Layout/_Footer.cshtml
  src/Elastic.Markdown/Slices/Layout/_Header.cshtml
  src/Elastic.Markdown/Slices/Layout/_PagesNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_TableOfContents.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTree.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
Labels: redesign

#487 Add previous/next button design
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Slices/Layout/_TableOfContents.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
  src/Elastic.Markdown/Slices/_ViewImports.cshtml
Labels: redesign

#474 update contributing on the web docs
  docs/contribute/on-the-web.md
  docs/docset.yml
Labels: documentation

#489 Add tabs
  docs/contribute/locally.md
  src/Elastic.Markdown/Assets/main.ts
  src/Elastic.Markdown/Assets/markdown/tabs.css
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Assets/tabs.ts
  src/Elastic.Markdown/Elastic.Markdown.csproj
  src/Elastic.Markdown/Myst/Directives/DirectiveHtmlRenderer.cs
  src/Elastic.Markdown/Slices/Directives/TabItem.cshtml
  src/Elastic.Markdown/Slices/Directives/TabSet.cshtml
  src/Elastic.Markdown/Slices/Directives/_ViewModels.cs
Labels: redesign

#491 Initial support for cross link resolving
  docs/docset.yml
  docs/testing/cross-links.md
  src/Elastic.Markdown/CrossLinks/CrossLinkResolver.cs
  src/Elastic.Markdown/Diagnostics/ProcessorDiagnosticExtensions.cs
  src/Elastic.Markdown/DocumentationGenerator.cs
  src/Elastic.Markdown/IO/Configuration/ConfigurationFile.cs
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/Elastic.Markdown/IO/State/LinkReference.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveHtmlRenderer.cs
  src/Elastic.Markdown/Myst/Directives/IncludeBlock.cs
  src/Elastic.Markdown/Myst/Directives/SettingsBlock.cs
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  src/Elastic.Markdown/Myst/MarkdownParser.cs
  src/Elastic.Markdown/Myst/ParserContext.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/docs-builder/Cli/Commands.cs
  src/docs-builder/Http/ReloadableGeneratorState.cs
  tests/Elastic.Markdown.Tests/Directives/DirectiveBaseTests.cs
  tests/Elastic.Markdown.Tests/DocSet/NavigationTestsBase.cs
  tests/Elastic.Markdown.Tests/Inline/InlineLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlneBaseTests.cs
  tests/Elastic.Markdown.Tests/MockFileSystemExtensions.cs
  tests/Elastic.Markdown.Tests/OutputDirectoryTests.cs
  tests/Elastic.Markdown.Tests/TestCrossLinkResolver.cs
  tests/authoring/Container/DefinitionLists.fs
  tests/authoring/Framework/Setup.fs
  tests/authoring/Framework/TestCrossLinkResolver.fs
  tests/authoring/Inline/CrossLinks.fs
  tests/authoring/authoring.fsproj
Labels: feature

#496 Only validate `docs-content` cross links for now
  src/Elastic.Markdown/CrossLinks/CrossLinkResolver.cs
  tests/Elastic.Markdown.Tests/TestCrossLinkResolver.cs
  tests/authoring/Framework/Setup.fs
  tests/authoring/Framework/TestCrossLinkResolver.fs
  tests/authoring/Inline/CrossLinks.fs
Labels: feature

#499 Add `links create-index` command to the assembler
  src/Elastic.Markdown/CrossLinks/CrossLinkResolver.cs
  src/Elastic.Markdown/SourceGenerationContext.cs
  src/docs-assembler/Cli/LinkCommands.cs
  src/docs-assembler/Program.cs
  src/docs-assembler/docs-assembler.csproj
Labels: feature

#498 Create CODEOWNERS
  .github/CODEOWNERS
Labels: chore

#501 Add Documentation Assembler GitHub Action
  actions/assembler/action.yml
  docs-builder.sln
  src/docs-assembler/Cli/LinkCommands.cs
  src/docs-assembler/Cli/RepositoryCommands.cs
  src/docs-assembler/Program.cs
Labels: feature

#504 Allow for both <scheme>:/<path> and <scheme://<path> style cross-link lookups
  src/Elastic.Markdown/CrossLinks/CrossLinkResolver.cs
  tests/authoring/Inline/CrossLinks.fs
Labels: fix

#512 Use task attribute to identify deployments
  .github/workflows/preview-build.yml
  .github/workflows/preview-cleanup.yml
Labels: automation

#509 Add codeblocks
  docs/contribute/move.md
  docs/migration/guide/how-to-set-up-docs-previews.md
  docs/syntax/code.md
  src/Elastic.Markdown/Assets/copybutton.css
  src/Elastic.Markdown/Assets/copybutton.ts
  src/Elastic.Markdown/Assets/main.ts
  src/Elastic.Markdown/Assets/markdown/code.css
  src/Elastic.Markdown/Assets/markdown/list.css
  src/Elastic.Markdown/Assets/markdown/tabs.css
  src/Elastic.Markdown/Assets/markdown/typography.css
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/package-lock.json
  src/Elastic.Markdown/package.json
Labels: redesign

#513 Add admonitions
  docs/syntax/admonitions.md
  src/Elastic.Markdown/Assets/markdown/admonition.css
  src/Elastic.Markdown/Assets/markdown/code.css
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Assets/theme.css
  src/Elastic.Markdown/Slices/Directives/Admonition.cshtml
  tests/Elastic.Markdown.Tests/Directives/AdmonitionTests.cs
  tests/authoring/Blocks/Admonitions.fs
  tests/authoring/Blocks/Lists.fs
  tests/authoring/Container/DefinitionLists.fs
  tests/authoring/authoring.fsproj
Labels: redesign

#515 Empty url in markdown links should result in an error not warning
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  tests/authoring/Inline/InlineLinks.fs
Labels: fix

#516 Enable new design by default
  src/Elastic.Markdown/Myst/SectionedHeadingRenderer.cs
  src/Elastic.Markdown/Slices/Layout/_Footer.cshtml
  src/Elastic.Markdown/Slices/Layout/_TableOfContents.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTree.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
  tests/Elastic.Markdown.Tests/Inline/InlineAnchorTests.cs
  tests/Elastic.Markdown.Tests/Inline/SubstitutionTest.cs
  tests/authoring/Blocks/Admonitions.fs
  tests/authoring/Generator/LinkReferenceFile.fs
Labels: feature

#517 Add rudimentary EQL syntax highlighting
  docs/docset.yml
  docs/testing/custom-highlighters.md
  src/Elastic.Markdown/Assets/hljs.ts
  src/Elastic.Markdown/Assets/toc-nav.ts
  src/Elastic.Markdown/Myst/CodeBlocks/SupportedLanguages.cs
  src/Elastic.Markdown/Slices/Layout/_Scripts.cshtml
  src/Elastic.Markdown/_static/custom.js
Labels: feature

#514 Remove ExternalLinkHosts validation
  docs/docset.yml
  src/Elastic.Markdown/IO/Configuration/ConfigurationFile.cs
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  tests/authoring/Inline/InlineLinks.fs
Labels: fix

#520 Move no url back to warning temporarily
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  tests/authoring/Inline/InlineLinks.fs
Labels: fix

#521 feature/painless language support
  docs/testing/custom-highlighters.md
  src/Elastic.Markdown/Assets/hljs.ts
  src/Elastic.Markdown/Assets/markdown/code.css
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockParser.cs
Labels: feature

#522 Remove label events from preview-build workflow
  .github/workflows/preview-build.yml
Labels: ci

#528 Fix pages navigation
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
Labels: fix

#519 Add ES|QL language support and move hl theme over to theme colors
  docs/testing/custom-highlighters.md
  src/Elastic.Markdown/Assets/hljs.ts
  src/Elastic.Markdown/Assets/markdown/code.css
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockParser.cs
  src/Elastic.Markdown/Myst/CodeBlocks/SupportedLanguages.cs
Labels: feature

#531 Add list styling
  docs/docset.yml
  docs/syntax/lists.md
  src/Elastic.Markdown/Assets/markdown/list.css
Labels: redesign

#532 Fix img src url
  src/Elastic.Markdown/Myst/Directives/DirectiveHtmlRenderer.cs
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
Labels: fix

#527 Rework applies blocks to applies_to with new semantics
  docs-builder.sln
  docs/syntax/applies.md
  docs/syntax/img/applies.png
  docs/syntax/index.md
  docs/versions/content-patterns.md
  src/Elastic.Markdown.Refactor/Elastic.Markdown.Refactor.csproj
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Elastic.Markdown.csproj
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlock.cs
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockHtmlRenderer.cs
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockParser.cs
  src/Elastic.Markdown/Myst/Directives/AppliesBlock.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveBlockParser.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveHtmlRenderer.cs
  src/Elastic.Markdown/Myst/FrontMatter/Applicability.cs
  src/Elastic.Markdown/Myst/FrontMatter/ApplicableTo.cs
  src/Elastic.Markdown/Myst/FrontMatter/Deployment.cs
  src/Elastic.Markdown/Myst/FrontMatter/FrontMatterParser.cs
  src/Elastic.Markdown/Myst/FrontMatter/ProductAvailability.cs
  src/Elastic.Markdown/Myst/Settings/StructuredSettings.cs
  src/Elastic.Markdown/Myst/YamlSerialization.cs
  src/Elastic.Markdown/Slices/Directives/ApplicableTo.cshtml
  src/Elastic.Markdown/Slices/Directives/Applies.cshtml
  src/Elastic.Markdown/Slices/Index.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
  src/docs-assembler/docs-assembler.csproj
  src/docs-builder/docs-builder.csproj
  tests/Elastic.Markdown.Tests/Directives/AppliesBlockTests.cs
  tests/Elastic.Markdown.Tests/FrontMatter/ProductConstraintTests.cs
  tests/authoring/Applicability/AppliesToDirective.fs
  tests/authoring/Applicability/AppliesToFrontMatter.fs
  tests/authoring/Blocks/CodeBlocks/CodeBlocks.fs
  tests/authoring/Framework/MarkdownDocumentAssertions.fs
  tests/authoring/authoring.fsproj
Labels: feature

#533 Load navigation javascript earlier
  src/Elastic.Markdown/.gitignore
  src/Elastic.Markdown/Assets/main.ts
  src/Elastic.Markdown/Assets/pages-nav.ts
  src/Elastic.Markdown/Slices/Layout/_PagesNav.cshtml
  src/Elastic.Markdown/package.json
Labels: enhancement

#535 Fix layout shift on page load
  src/Elastic.Markdown/Assets/styles.css
Labels: fix

#536 Fix ToC nav
  src/Elastic.Markdown/Assets/toc-nav.ts
Labels: fix

#537 Cache Navigation
  src/Elastic.Markdown/Assets/pages-nav.ts
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/IO/Navigation/DocumentationGroup.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Layout/_PagesNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
Labels: fix

#538 Fix csharp code analysis warnings
  src/Elastic.Markdown.Refactor/Move.cs
  src/Elastic.Markdown/Diagnostics/DiagnosticsChannel.cs
  src/Elastic.Markdown/Diagnostics/ProcessorDiagnosticExtensions.cs
  src/Elastic.Markdown/IO/Configuration/ConfigurationFile.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlock.cs
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockHtmlRenderer.cs
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockParser.cs
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeMarkdownExtensions.cs
  src/Elastic.Markdown/Myst/Comments/CommentBlockParser.cs
  src/Elastic.Markdown/Myst/Directives/AppliesBlock.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveBlock.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveHtmlRenderer.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveParagraphParser.cs
  src/Elastic.Markdown/Myst/Directives/TabSetBlock.cs
  src/Elastic.Markdown/Myst/FrontMatter/AllVersions.cs
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  src/Elastic.Markdown/Myst/InlineParsers/HeadingBlockWithSlugParser.cs
  src/Elastic.Markdown/Myst/InlineParsers/InlineAnchorParser.cs
  src/Elastic.Markdown/Myst/MarkdownParser.cs
  src/Elastic.Markdown/Myst/Substitution/SubstitutionParser.cs
  src/Elastic.Markdown/Slices/Directives/ApplicableTo.cshtml
  src/Elastic.Markdown/Slices/Directives/Settings.cshtml
  src/Elastic.Markdown/Slices/Directives/_ViewModels.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Layout/_Announcement.cshtml
  src/Elastic.Markdown/Slices/Layout/_Head.cshtml
  src/Elastic.Markdown/Slices/Layout/_HeadNav.cshtml
  src/Elastic.Markdown/SourceGenerationContext.cs
  src/docs-assembler/Cli/LinkCommands.cs
  src/docs-assembler/Cli/RepositoryCommands.cs
  src/docs-assembler/Program.cs
  src/docs-builder/Http/DocumentationWebHost.cs
  src/docs-builder/Program.cs
  tests/Elastic.Markdown.Tests/Directives/DirectiveBaseTests.cs
  tests/Elastic.Markdown.Tests/Directives/MermaidTests.cs
  tests/Elastic.Markdown.Tests/Directives/TabTests.cs
  tests/Elastic.Markdown.Tests/Directives/VersionTests.cs
  tests/Elastic.Markdown.Tests/DocSet/LinkReferenceTests.cs
  tests/Elastic.Markdown.Tests/DocSet/NavigationTestsBase.cs
  tests/Elastic.Markdown.Tests/Inline/InlneBaseTests.cs
  tests/Elastic.Markdown.Tests/OutputDirectoryTests.cs
  tests/Elastic.Markdown.Tests/TestLogger.cs
Labels: fix

#541 Update code block parser to handle YAML key warnings
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockParser.cs
  src/Elastic.Markdown/Myst/FrontMatter/ApplicableTo.cs
  tests/authoring/Applicability/AppliesToDirective.fs
Labels: fix

#542 Rename Elastic Cloud to Elastic Cloud Hosted for applies_to displayed values
  src/Elastic.Markdown/Slices/Directives/ApplicableTo.cshtml
Labels: fix

#543 Change one Security serverless "applies to" duplicate to missing Elasticsearch serverless
  src/Elastic.Markdown/Slices/Directives/ApplicableTo.cshtml
Labels: fix

#544 Update file_inclusion.md
  docs/syntax/file_inclusion.md
Labels: documentation

#547 Remove admonition
  docs/versions/index.md
Labels: documentation

#546 Update applies.md
  docs/syntax/applies.md
Labels: documentation

#523 Empty url in markdown links should result in an error not warning
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  tests/authoring/Inline/InlineLinks.fs
Labels: fix

#551 Address a few allocation issues
  Elastic.Documentation.Tooling/DocumentationTooling.cs
  src/Elastic.Markdown/Myst/CodeBlocks/SupportedLanguages.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveParagraphParser.cs
Labels: fix

#553 Ensure docs-builder serve shares the same service collection bootstrapping as the CLI tools
  Elastic.Documentation.Tooling/DocumentationTooling.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
  src/docs-builder/Http/DocumentationWebHost.cs
Labels: chore

#557 Always deploy
  .github/workflows/preview-build.yml
Labels: automation

#556 Add redirects.yml to publish renames/delations in links.json for dependent docsets.
  .editorconfig
  docs/_docset.yml
  docs/_redirects.yml
  docs/contribute/redirects.md
  docs/testing/redirects/5th-page.md
  docs/testing/redirects/first-page.md
  docs/testing/redirects/second-page.md
  docs/testing/redirects/third-page.md
  src/Elastic.Markdown/BuildContext.cs
  src/Elastic.Markdown/CrossLinks/CrossLinkResolver.cs
  src/Elastic.Markdown/IO/Configuration/ConfigurationFile.cs
  src/Elastic.Markdown/IO/Configuration/RedirectFile.cs
  src/Elastic.Markdown/IO/Configuration/YamlStreamReader.cs
  src/Elastic.Markdown/IO/DocumentationFile.cs
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/IO/State/LinkReference.cs
  src/docs-builder/Cli/Commands.cs
  src/docs-builder/Http/DocumentationWebHost.cs
  tests/Elastic.Markdown.Tests/Directives/DirectiveBaseTests.cs
  tests/Elastic.Markdown.Tests/DocSet/NavigationTests.cs
  tests/Elastic.Markdown.Tests/DocSet/NavigationTestsBase.cs
  tests/Elastic.Markdown.Tests/Inline/InlneBaseTests.cs
  tests/Elastic.Markdown.Tests/OutputDirectoryTests.cs
  tests/authoring/Framework/Setup.fs
  tests/authoring/Framework/TestCrossLinkResolver.fs
  tests/authoring/Generator/LinkReferenceFile.fs
  tests/authoring/Inline/CrossLinks.fs
  tests/authoring/Inline/CrossLinksRedirects.fs
  tests/authoring/authoring.fsproj
Labels: feature

#564 [DOCS] Update file_inclusion.md for linking to snippets with custom anchors
  docs/syntax/file_inclusion.md
Labels: documentation

#572 Add definition list
  docs/_docset.yml
  docs/syntax/definition-lists.md
  src/Elastic.Markdown/Assets/markdown/definition-list.css
  src/Elastic.Markdown/Assets/styles.css
Labels: redesign

#571 Fix fonts
  src/Elastic.Markdown/Assets/markdown/list.css
  src/Elastic.Markdown/Assets/markdown/typography.css
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Assets/theme.css
Labels: redesign

#570 Add table
  docs/syntax/index.md
  docs/syntax/tables.md
  src/Elastic.Markdown/Assets/markdown/table.css
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Myst/Directives/DirectiveMarkdownExtension.cs
  src/Elastic.Markdown/Myst/WrappedTableRenderer.cs
Labels: redesign

#545 Add htmx to dynamically load content
  src/Elastic.Markdown/Assets/copybutton.ts
  src/Elastic.Markdown/Assets/hljs.ts
  src/Elastic.Markdown/Assets/main.ts
  src/Elastic.Markdown/Assets/pages-nav.ts
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Assets/tabs.ts
  src/Elastic.Markdown/Myst/MarkdownParser.cs
  src/Elastic.Markdown/Myst/Renderers/HtmxLinkInlineRenderer.cs
  src/Elastic.Markdown/Slices/Layout/_PagesNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTree.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
  src/Elastic.Markdown/package-lock.json
  src/Elastic.Markdown/package.json
  tests/Elastic.Markdown.Tests/Inline/AnchorLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/DirectiveBlockLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineAnchorTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineLinkTests.cs
Labels: enhancement

#576 Add Free Disk Space to preview build workflow
  .github/workflows/preview-build.yml
Labels: ci

#574 pages-nav: Fix spacing shift when clicking on a group
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
Labels: fix

#573 tabs: Add slight border
  docs/syntax/tabs.md
  src/Elastic.Markdown/Assets/markdown/tabs.css
Labels: redesign

#575 Also add breadcrumbs to the hx-select-oob list
  src/Elastic.Markdown/Helpers/Htmx.cs
  src/Elastic.Markdown/Myst/Renderers/HtmxLinkInlineRenderer.cs
  src/Elastic.Markdown/Slices/Layout/_Breadcrumbs.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
  tests/Elastic.Markdown.Tests/Inline/AnchorLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/DirectiveBlockLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineAnchorTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineLinkTests.cs
Labels: fix

#584 Fix truncated text in code callout
  docs/testing/index.md
  src/Elastic.Markdown/Assets/markdown/code.css
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockParser.cs
Labels: fix

#583 Exclude navigation elements from browser search if collapsed
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
Labels: fix

#582 Fix inline code wrapping
  src/Elastic.Markdown/Assets/markdown/code.css
Labels: fix

#578 Fix tabs in list
  src/Elastic.Markdown/Assets/markdown/list.css
  src/Elastic.Markdown/Myst/Directives/TabSetBlock.cs
  src/Elastic.Markdown/Slices/Directives/TabItem.cshtml
  tests/Elastic.Markdown.Tests/Directives/TabTests.cs
Labels: fix

#579 Add hx attributes to breadcrumbs links
  src/Elastic.Markdown/Slices/Layout/_Breadcrumbs.cshtml
Labels: fix

#585 Support anchors and table of contents from included files
  src/Elastic.Markdown/DocumentationGenerator.cs
  src/Elastic.Markdown/IO/DocumentationFile.cs
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveHtmlRenderer.cs
  src/Elastic.Markdown/Myst/Directives/IncludeBlock.cs
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/_ViewModels.cs
  tests/authoring/Directives/IncludeBlocks.fs
  tests/authoring/Framework/HtmlAssertions.fs
  tests/authoring/Framework/MarkdownDocumentAssertions.fs
  tests/authoring/Framework/Setup.fs
  tests/authoring/Framework/TestValues.fs
  tests/authoring/Inline/RelativeLinks.fs
  tests/authoring/authoring.fsproj
Labels: fix

#587 Add inbound links validation
  .editorconfig
  Elastic.Documentation.Tooling/Diagnostics/Console/ConsoleDiagnosticsCollector.cs
  Elastic.Documentation.Tooling/Diagnostics/Console/ErrataFileSourceRepository.cs
  Elastic.Documentation.Tooling/Diagnostics/Console/GithubAnnotationOutput.cs
  Elastic.Documentation.Tooling/Diagnostics/Log.cs
  Elastic.Documentation.Tooling/Elastic.Documentation.Tooling.csproj
  actions/validate-inbound-local/action.yml
  docs-builder.sln
  src/Elastic.Markdown/CrossLinks/ConfigurationCrossLinkFetcher.cs
  src/Elastic.Markdown/CrossLinks/CrossLinkFetcher.cs
  src/Elastic.Markdown/CrossLinks/CrossLinkResolver.cs
  src/Elastic.Markdown/DocumentationGenerator.cs
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/Elastic.Markdown/IO/Paths.cs
  src/Elastic.Markdown/IO/State/LinkReference.cs
  src/docs-assembler/Cli/LinkCommands.cs
  src/docs-assembler/Links/LinkIndexCrossLinkFetcher.cs
  src/docs-assembler/Links/LinkIndexLinkChecker.cs
  src/docs-builder/Cli/CheckForUpdatesFilter.cs
  src/docs-builder/Cli/Commands.cs
  src/docs-builder/Diagnostics/LiveMode/LiveModeDiagnosticsCollector.cs
  src/docs-builder/docs-builder.csproj
  tests/Elastic.Markdown.Tests/TestCrossLinkResolver.cs
  tests/authoring/Framework/TestCrossLinkResolver.fs
Labels: feature

#589 Add local inbound links validation to the shared preview workflow
  .github/workflows/preview-build.yml
Labels: feature

#588 Fix htmx link in markdown content
  src/Elastic.Markdown/Myst/Renderers/HtmxLinkInlineRenderer.cs
  tests/Elastic.Markdown.Tests/Inline/AnchorLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/DirectiveBlockLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineAnchorTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineLinkTests.cs
  tests/authoring/Framework/HtmlAssertions.fs
Labels: fix

#593 Support `merge_group` event for preview builds
  .github/workflows/preview-build.yml
Labels: automation

#591 Fix "Edit this page" links to docs-content repo
  tests/Elastic.Markdown.Tests/TestCrossLinkResolver.cs
  tests/authoring/Framework/TestCrossLinkResolver.fs
Labels: fix

#592 Remove erroneous warning for link text generation on missing page
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  tests/Elastic.Markdown.Tests/Inline/InlineLinkTests.cs
Labels: fix

#596 validate-inbound-local call docker image directly
  .github/workflows/preview-build.yml
  src/Elastic.Markdown/IO/Discovery/GitCheckoutInformation.cs
  src/docs-assembler/Program.cs
Labels: fix

#598 Also trigger preview build on deleted files
  .github/workflows/preview-build.yml
Labels: automation

#600 Clean up legacy frontend resources
  src/Elastic.Markdown/Slices/Layout/_Footer.cshtml
  src/Elastic.Markdown/Slices/Layout/_Head.cshtml
  src/Elastic.Markdown/Slices/Layout/_HeadNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_PrevNextNav.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
  src/Elastic.Markdown/_static/atom-one-light.css
  src/Elastic.Markdown/_static/clipboard.min.js
  src/Elastic.Markdown/_static/copybutton.css
  src/Elastic.Markdown/_static/copybutton.js
  src/Elastic.Markdown/_static/custom.css
  src/Elastic.Markdown/_static/design-tabs.js
  src/Elastic.Markdown/_static/doctools.js
  src/Elastic.Markdown/_static/documentation_options.js
  src/Elastic.Markdown/_static/hljs.js
  src/Elastic.Markdown/_static/mystnb.css
  src/Elastic.Markdown/_static/print.css
  src/Elastic.Markdown/_static/pygments.css
  src/Elastic.Markdown/_static/shibuya.css
  src/Elastic.Markdown/_static/shibuya.js
  src/Elastic.Markdown/_static/sphinx-design.min.css
  src/Elastic.Markdown/_static/sphinx_highlight.js
  src/Elastic.Markdown/_static/togglebutton.css
  src/Elastic.Markdown/_static/togglebutton.js
Labels: chore

#602 link validate-inbound-local's resolver was using a stale copy
  src/Elastic.Markdown/CrossLinks/CrossLinkResolver.cs
  src/docs-assembler/Links/LinkIndexLinkChecker.cs
Labels: fix

#603 Draft runbook for moving reference content
  docs/_docset.yml
  docs/images/great-drawing-of-new-structure.png
  docs/migration/guide/move-ref-docs.md
Labels: documentation

#608 BREAKING: The preview build input `continue-on-error` is now `false` by default
  .github/workflows/preview-build.yml
Labels: automation

#607 Add path-pattern to docs
  docs/migration/guide/move-ref-docs.md
Labels: documentation

#612 more updates to ref docs
  docs/migration/guide/move-ref-docs.md
Labels: documentation

#606 Fix link to docs-builder docs
  src/docs-builder/Cli/CheckForUpdatesFilter.cs
Labels: fix

#613 Relocate Elastic.Documentation.Tooling to src directory.
  docs-builder.sln
  src/Elastic.Documentation.Tooling/Diagnostics/Console/ConsoleDiagnosticsCollector.cs
  src/Elastic.Documentation.Tooling/Diagnostics/Console/ErrataFileSourceRepository.cs
  src/Elastic.Documentation.Tooling/Diagnostics/Console/GithubAnnotationOutput.cs
  src/Elastic.Documentation.Tooling/Diagnostics/Log.cs
  src/Elastic.Documentation.Tooling/DocumentationTooling.cs
  src/Elastic.Documentation.Tooling/Elastic.Documentation.Tooling.csproj
  src/Elastic.Documentation.Tooling/Filters/CatchExceptionFilter.cs
  src/Elastic.Documentation.Tooling/Filters/StopwatchFilter.cs
  src/Elastic.Documentation.Tooling/Logging/CondensedConsoleLogger.cs
  src/Elastic.Documentation.Tooling/README.md
  src/docs-assembler/docs-assembler.csproj
  src/docs-builder/docs-builder.csproj
Labels: chore

#605 POC: Get currentl url to link renderer
  .editorconfig
  src/Elastic.Markdown.Refactor/Move.cs
  src/Elastic.Markdown/BuildContext.cs
  src/Elastic.Markdown/Diagnostics/ProcessorDiagnosticExtensions.cs
  src/Elastic.Markdown/DocumentationGenerator.cs
  src/Elastic.Markdown/IO/Configuration/ConfigurationFile.cs
  src/Elastic.Markdown/IO/Configuration/RedirectFile.cs
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/IO/State/LinkReference.cs
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlock.cs
  src/Elastic.Markdown/Myst/CodeBlocks/EnhancedCodeBlockParser.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveBlock.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveHtmlRenderer.cs
  src/Elastic.Markdown/Myst/Directives/ImageBlock.cs
  src/Elastic.Markdown/Myst/Directives/IncludeBlock.cs
  src/Elastic.Markdown/Myst/Directives/SettingsBlock.cs
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  src/Elastic.Markdown/Myst/MarkdownParser.cs
  src/Elastic.Markdown/Myst/ParserContext.cs
  src/Elastic.Markdown/Myst/Renderers/HtmxLinkInlineRenderer.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/docs-assembler/Links/LinkIndexLinkChecker.cs
  src/docs-builder/Http/DocumentationWebHost.cs
  src/docs-builder/Http/ReloadGeneratorService.cs
  tests/Elastic.Markdown.Tests/Directives/DirectiveBaseTests.cs
  tests/Elastic.Markdown.Tests/Directives/TabTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlneBaseTests.cs
  tests/Elastic.Markdown.Tests/OutputDirectoryTests.cs
Labels: chore

#614 Add `free-disk-space` input
  .github/workflows/preview-build.yml
Labels: automation

#616 Simply if check on Free Disk Space
  .github/workflows/preview-build.yml
Labels: ci

#618 Default CurrentUrlPath to empty string while we investigate further
  src/Elastic.Markdown/IO/DocumentationFile.cs
  src/Elastic.Markdown/Myst/ParserContext.cs
Labels: fix

#617 Fix `free-disk-space` input attempt 2
  .github/workflows/preview-build.yml
Labels: automation

#619 Just compare with repository name for now
  .github/workflows/preview-build.yml
Labels: automation

#623 Update links-index.json whenever a PR get's closed
  .github/workflows/preview-cleanup.yml
Labels: ci

#624 Update links-index.json whenever we push a links.json
  .github/workflows/preview-build.yml
Labels: ci

#627 Continue-on-error temporarily for validate-inbound-links
  .github/workflows/preview-build.yml
Labels: ci

#628 docs-preview: Use `since_last_remote_commit: true` for changed-files …
  .github/workflows/preview-build.yml
Labels: fix

#630 On ci skip if /docs folder has no docset.yml silently
  action.yml
  src/docs-builder/Cli/Commands.cs
Labels: ci

#629 Revert "docs-preview: Use `since_last_remote_commit: true` for changed-files …"
  .github/workflows/preview-build.yml
Labels: fix

#631 Feature: allow the docs-build action to hint to subsequent steps to skip
  .github/workflows/preview-build.yml
Labels: ci

#632 Set correct deployment status on skipped builds
  .github/workflows/preview-build.yml
Labels: automation

#633 Optimize preview build to avoid checkout on pull_request* events
  .github/workflows/preview-build.yml
Labels: enhancement

#604 Add `PrimaryNav` feature
  docs/_docset.yml
  src/Elastic.Markdown/Assets/pages-nav.ts
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Helpers/Htmx.cs
  src/Elastic.Markdown/IO/Configuration/ConfigurationFile.cs
  src/Elastic.Markdown/IO/Configuration/FeatureFlags.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveHtmlRenderer.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveMarkdownExtension.cs
  src/Elastic.Markdown/Myst/MarkdownParser.cs
  src/Elastic.Markdown/Myst/Renderers/HtmxLinkInlineRenderer.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Index.cshtml
  src/Elastic.Markdown/Slices/Layout/_Breadcrumbs.cshtml
  src/Elastic.Markdown/Slices/Layout/_Header.cshtml
  src/Elastic.Markdown/Slices/Layout/_PagesNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_PrevNextNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_PrimaryNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_PrimaryNavDropdownItem.cshtml
  src/Elastic.Markdown/Slices/Layout/_TableOfContents.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTree.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
  src/Elastic.Markdown/_static/elasticsearch-logo-color-64px.svg
  src/Elastic.Markdown/_static/logo-elastic-horizontal-color.svg
  src/Elastic.Markdown/_static/observability-logo-color-64px.svg
  src/Elastic.Markdown/_static/security-logo-color-64px.svg
  src/docs-builder/Cli/Commands.cs
  src/docs-builder/Http/DocumentationWebHost.cs
  tests/Elastic.Markdown.Tests/Directives/DirectiveBaseTests.cs
  tests/Elastic.Markdown.Tests/Inline/AnchorLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/DirectiveBlockLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineAnchorTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlneBaseTests.cs
Labels: feature

#635 Revert "Add `PrimaryNav` feature"
  docs/_docset.yml
  src/Elastic.Markdown/Assets/pages-nav.ts
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Helpers/Htmx.cs
  src/Elastic.Markdown/IO/Configuration/ConfigurationFile.cs
  src/Elastic.Markdown/IO/Configuration/FeatureFlags.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveHtmlRenderer.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveMarkdownExtension.cs
  src/Elastic.Markdown/Myst/MarkdownParser.cs
  src/Elastic.Markdown/Myst/Renderers/HtmxLinkInlineRenderer.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Index.cshtml
  src/Elastic.Markdown/Slices/Layout/_Breadcrumbs.cshtml
  src/Elastic.Markdown/Slices/Layout/_Header.cshtml
  src/Elastic.Markdown/Slices/Layout/_PagesNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_PrevNextNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_PrimaryNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_PrimaryNavDropdownItem.cshtml
  src/Elastic.Markdown/Slices/Layout/_TableOfContents.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTree.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
  src/Elastic.Markdown/_static/elasticsearch-logo-color-64px.svg
  src/Elastic.Markdown/_static/logo-elastic-horizontal-color.svg
  src/Elastic.Markdown/_static/observability-logo-color-64px.svg
  src/Elastic.Markdown/_static/security-logo-color-64px.svg
  src/docs-builder/Cli/Commands.cs
  src/docs-builder/Http/DocumentationWebHost.cs
  tests/Elastic.Markdown.Tests/Directives/DirectiveBaseTests.cs
  tests/Elastic.Markdown.Tests/Inline/AnchorLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/DirectiveBlockLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineAnchorTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlineLinkTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlneBaseTests.cs
Labels: fix

#643 Inbound link checking, fully validate if found in links-index
  src/Elastic.Documentation.Tooling/Diagnostics/Log.cs
  src/Elastic.Markdown/CrossLinks/CrossLinkResolver.cs
  src/docs-assembler/Links/LinkIndexLinkChecker.cs
Labels: fix

#642 Add `landing-page-path` output and use it in preview workflow
  .github/workflows/preview-build.yml
  .github/workflows/smoke-test.yml
  action.yml
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/docs-builder/Cli/Commands.cs
Labels: automation

#644 Fix preview-build.yml
  .github/workflows/preview-build.yml
Labels: fix

#646 Remove unused workflows
  .github/workflows/preview-deploy.yml
  .github/workflows/preview.yml
Labels: chore

#648 Add validate command for single published repository
  actions/validate-inbound-local/action.yml
  build/Targets.fs
  src/docs-assembler/Cli/InboundLinkCommands.cs
  src/docs-assembler/Links/LinkIndexLinkChecker.cs
  src/docs-assembler/Program.cs
Labels: fix

#649 Refactor link index command into dedicated LinkRegistry module
  src/docs-assembler/Cli/InboundLinkCommands.cs
  src/docs-assembler/Cli/LinkRegistryCommands.cs
  src/docs-assembler/Program.cs
Labels: fix

#651 Better error messages for cross_link errors (From `docs-builder` and `docs-assembler`)
  src/Elastic.Markdown/CrossLinks/ConfigurationCrossLinkFetcher.cs
  src/Elastic.Markdown/CrossLinks/CrossLinkFetcher.cs
  src/Elastic.Markdown/CrossLinks/CrossLinkResolver.cs
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  src/docs-assembler/Cli/InboundLinkCommands.cs
  src/docs-assembler/Links/LinkIndexCrossLinkFetcher.cs
  src/docs-assembler/Links/LinkIndexLinkChecker.cs
  tests/Elastic.Markdown.Tests/TestCrossLinkResolver.cs
  tests/authoring/Framework/TestCrossLinkResolver.fs
Labels: fix

#652 Add logging to git remote resolving
  src/Elastic.Markdown/IO/Discovery/GitCheckoutInformation.cs
  src/docs-assembler/Cli/InboundLinkCommands.cs
  tests/Elastic.Markdown.Tests/DocSet/LinkReferenceTests.cs
Labels: fix

#654 Update cross-repo links syntax info
  docs/syntax/links.md
Labels: documentation

#655 If GITHUB_REPOSITORY is set use it verbatim
  src/Elastic.Markdown/IO/Discovery/GitCheckoutInformation.cs
Labels: fix

#658 Fix `environment_url` in preview deployment
  .github/workflows/preview-build.yml
Labels: automation

#659 Adjust links and wording in primary and secondary navigation
  src/Elastic.Markdown/Slices/Layout/_Header.cshtml
Labels: fix
