Repository elastic/docs-builder, pull requests merged in 2025-07, with the labels that each got.

#1487 New `applies_to` tags styling
  docs/syntax/applies.md
  docs/testing/req.md
  src/Elastic.Documentation.Site/Assets/markdown/applies-to.css
  src/Elastic.Documentation.Site/Assets/theme.css
  src/Elastic.Markdown/Myst/Components/ApplicableToComponent.cshtml
  src/Elastic.Markdown/Myst/Directives/AppliesTo/AppliesToView.cshtml
  src/Elastic.Markdown/Myst/FrontMatter/Applicability.cs
  src/Elastic.Markdown/Myst/Roles/AppliesTo/ApplicableToRole.cshtml
  src/Elastic.Markdown/Page/Index.cshtml
  tests/authoring/Inline/AppliesToRole.fs
Labels: enhancement

#1489 Fix injecting VersionsConfiguration in docs-assembler
  docs/testing/req.md
  src/tooling/docs-assembler/AssembleContext.cs
  src/tooling/docs-assembler/Cli/RepositoryCommands.cs
  src/tooling/docs-assembler/Program.cs
Labels: fix

#1490 Pass the instantiated VersionConfiguration to AssemblerDocumentationSet
  src/tooling/docs-assembler/AssembleSources.cs
  src/tooling/docs-assembler/Cli/RepositoryCommands.cs
  src/tooling/docs-assembler/Navigation/AssemblerDocumentationSet.cs
  tests/docs-assembler.Tests/src/docs-assembler.Tests/GlobalNavigationTests.cs
Labels: fix

#1479 dependabot: Group eslint packages
  .github/dependabot.yml
Labels: chore

#1445 Branching strategy selection, cumulative authoring, ++
  docs/_docset.yml
  docs/configure/content-sources.md
  docs/contribute/_snippets/docs-intro.md
  docs/contribute/_snippets/guide-intro.md
  docs/contribute/_snippets/tag-processing.md
  docs/contribute/_snippets/tagged-warning.md
  docs/contribute/_snippets/two-systems.md
  docs/contribute/add-repo.md
  docs/contribute/branching-strategy.md
  docs/contribute/cumulative-docs.md
  docs/contribute/index.md
  docs/contribute/locally.md
  docs/contribute/on-the-web.md
  docs/migration/guide/working-in-docs-content.md
  docs/migration/versioning.md
  docs/syntax/_snippets/line-level-applies-example.md
  docs/syntax/_snippets/multiple-lifecycle-states.md
  docs/syntax/_snippets/page-level-applies-examples.md
  docs/syntax/_snippets/section-level-applies-examples.md
  docs/syntax/_snippets/stack-serverless-lifecycle-example.md
  docs/syntax/_snippets/unversioned-lifecycle.md
  docs/syntax/_snippets/versioned-lifecycle.md
  docs/syntax/applies.md
  docs/syntax/quick-ref.md
  docs/versions/content-patterns.md
  docs/versions/index.md
Labels: documentation

#1508 Fix feature flag name
  src/Elastic.Documentation.Configuration/Builder/FeatureFlags.cs
Labels: automation

#1512 Cleanup unused versions config in assembler config
  src/Elastic.Documentation.Configuration/Assembler/AssemblyConfiguration.cs
  src/Elastic.Documentation.Configuration/Assembler/VersionEntry.cs
  src/Elastic.Documentation.Configuration/Serialization/YamlStaticContext.cs
Labels: chore

#1513 Add EDOT Collector to versions.yml
  docs/syntax/applies.md
  src/Elastic.Documentation.Configuration/Versions/Version.cs
  src/Elastic.Documentation.Configuration/versions.yml
  src/Elastic.Markdown/Myst/Components/ApplicableToComponent.cshtml
  src/Elastic.Markdown/Myst/FrontMatter/ApplicableTo.cs
Labels: enhancement

#1516 Apply hx-disable to the injected Elastic navbar
  src/Elastic.Documentation.Site/Layout/_Header.cshtml
Labels: fix

#1511 add ECCTL to release notes nav
  src/tooling/docs-assembler/assembler.yml
  src/tooling/docs-assembler/legacy-url-mappings.yml
  src/tooling/docs-assembler/navigation.yml
Labels: fix

#1524 Update stepper.md
  docs/syntax/stepper.md
Labels: bug

#1526 Optimize preview build permissions
  .github/workflows/preview-build.yml
Labels: automation

#1528 Optimize JS
  src/Elastic.Documentation.Site/Assets/custom-elements.ts
  src/Elastic.Documentation.Site/Assets/main.ts
  src/Elastic.Documentation.Site/Layout/_Footer.cshtml
  src/Elastic.Documentation.Site/Layout/_Head.cshtml
  src/Elastic.Documentation.Site/Layout/_Scripts.cshtml
  src/Elastic.Documentation.Site/package-lock.json
  src/Elastic.Documentation.Site/package.json
Labels: chore

#1531 Fix preview comment
  .github/workflows/preview-build.yml
Labels: automation

#1525 Load elastic nav asynchronously
  src/Elastic.Documentation.Site/Layout/_Header.cshtml
Labels: enhancement

#1536 Fix RoleParser
  docs/testing/req.md
  src/Elastic.Markdown/Myst/Roles/RoleParser.cs
Labels: fix

#1539 Allow dangling toc definitions in navigation.yml
  src/tooling/docs-assembler/Navigation/GlobalNavigationHtmlWriter.cs
Labels: fix

#1542 Set explicit height on footer logo
  src/Elastic.Documentation.Site/Layout/_Footer.cshtml
Labels: fix

#1548 Force allow the root page to be indexed
  src/Elastic.Markdown/HtmlWriter.cs
Labels: fix

#1560 Add support for version context variables
  docs/_docset.yml
  docs/syntax/substitutions.md
  docs/syntax/version-variables.md
  src/Elastic.Documentation.Configuration/BuildContext.cs
  src/Elastic.Documentation.Configuration/Builder/ConfigurationFile.cs
  src/Elastic.Documentation.Configuration/Versions/Version.cs
  src/Elastic.Markdown/Diagnostics/ProcessorDiagnosticExtensions.cs
  src/Elastic.Markdown/DocumentationGenerator.cs
  src/Elastic.Markdown/Myst/Components/ApplicableToComponent.cshtml
  src/Elastic.Markdown/Myst/InlineParsers/Substitution/SubstitutionParser.cs
  tests/authoring/Framework/Setup.fs
  tests/authoring/Inline/SubstitutionMutations.fs
  tests/authoring/Inline/Substitutions.fs
  tests/authoring/authoring.fsproj
Labels: feature

#1557 feature/api landing page
  src/Elastic.ApiExplorer/Landing/LandingNavigationItem.cs
  src/Elastic.ApiExplorer/Landing/LandingView.cshtml
  src/Elastic.ApiExplorer/Operations/OperationView.cshtml
  src/Elastic.Documentation.Site/Assets/api-docs.css
  src/Elastic.Documentation.Site/Navigation/_TocTree.cshtml
  src/tooling/docs-builder/Http/DocumentationWebHost.cs
  src/tooling/docs-builder/Http/ReloadableGeneratorState.cs
Labels: fix

#1537 Add kbd element
  docs/_docset.yml
  docs/syntax/kbd.md
  src/Elastic.Documentation.Site/Assets/markdown/kbd.css
  src/Elastic.Documentation.Site/Assets/styles.css
  src/Elastic.Markdown/Myst/MarkdownParser.cs
  src/Elastic.Markdown/Myst/Roles/Kbd/Kbd.cs
  src/Elastic.Markdown/Myst/Roles/Kbd/KbdParser.cs
  src/Elastic.Markdown/Myst/Roles/Kbd/KbdRole.cs
  src/Elastic.Markdown/Myst/Roles/Kbd/KbdRoleRenderer.cs
  tests/authoring/Inline/KbdRole.fs
  tests/authoring/authoring.fsproj
Labels: feature

#1567 Adds an xref to the subs syntax
  docs/syntax/code.md
Labels: documentation

#1396 Adding support to the docs for an image carousel
  docs/syntax/images.md
  src/Elastic.Documentation.Site/Assets/image-carousel.ts
  src/Elastic.Documentation.Site/Assets/main.ts
  src/Elastic.Documentation.Site/Assets/markdown/image-carousel.css
  src/Elastic.Documentation.Site/Assets/styles.css
  src/Elastic.Markdown/Myst/Directives/DirectiveBlockParser.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveHtmlRenderer.cs
  src/Elastic.Markdown/Myst/Directives/Image/ImageCarouselBlock.cs
  src/Elastic.Markdown/Myst/Directives/Image/ImageCarouselView.cshtml
  src/Elastic.Markdown/Myst/Directives/Image/ImageCarouselViewModel.cs
  tests/Elastic.Markdown.Tests/Directives/ImageCarouselTests.cs
Labels: feature

#1579 Ensure edge is defined for repositories on master
  config/assembler.yml
Labels: fix

#1596 Better approach to set the title on directives in LLM markdown output
  src/Elastic.Markdown/Myst/Directives/Admonition/AdmonitionBlock.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveBlock.cs
  src/Elastic.Markdown/Myst/Directives/Stepper/StepperBlock.cs
  src/Elastic.Markdown/Myst/Directives/Tabs/TabSetBlock.cs
  src/Elastic.Markdown/Myst/Renderers/LlmMarkdown/LlmBlockRenderers.cs
Labels: fix

#1603 Update stepper.md
  docs/syntax/stepper.md
Labels: documentation

#1581 Update `current` for the ecs repo
  config/assembler.yml
Labels: ci

#1610 An attempt to document all of the config files
  config/legacy-url-mappings.yml
  config/navigation.yml
  docs/_docset.yml
  docs/configure/content-sources.md
  docs/configure/site/content.md
  docs/configure/site/index.md
  docs/configure/site/landing-page.md
  docs/configure/site/legacy-url-mappings.md
  docs/configure/site/navigation.md
  docs/configure/site/redirects.md
  docs/configure/site/versions.md
  docs/contribute/add-repo.md
  docs/contribute/redirects.md
  docs/contribute/release-new-version.md
  docs/syntax-docs-builder.zip
Labels: documentation

#1619 Revert "Bump stack version to 9.1.0"
  config/assembler.yml
  config/versions.yml
Labels: fix

#1620 Add docs-tech-leads to config code owners
  .github/CODEOWNERS
Labels: chore

#1618 Search or Ask AI beta webcompontent
  Directory.Packages.props
  src/Elastic.Documentation.Site/Assets/custom-elements.ts
  src/Elastic.Documentation.Site/Assets/eui-icons-cache.ts
  src/Elastic.Documentation.Site/Assets/main.ts
  src/Elastic.Documentation.Site/Assets/markdown/code.css
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/AskAiAnswer.tsx
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/AskAiSuggestions.tsx
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/SearchOrAskAi.tsx
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/SearchOrAskAiButton.tsx
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/SearchOrAskAiModal.tsx
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/SearchSuggestions.tsx
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/Suggestions.tsx
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/modal.store.ts
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/search.store.ts
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/useFetchEventSource.ts
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/useLlmGateway.ts
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/useMessageThrottling.ts
  src/Elastic.Documentation.Site/Assets/web-components/VersionDropdown.tsx
  src/Elastic.Documentation.Site/Layout/_Header.cshtml
  src/Elastic.Documentation.Site/package-lock.json
  src/Elastic.Documentation.Site/package.json
  src/Elastic.Markdown/_Layout.cshtml
  src/tooling/docs-builder/Http/DocumentationWebHost.cs
  src/tooling/docs-builder/Http/GcpIdTokenGenerator.cs
Labels: feature

#1625 Lazyload `SearchOrAskAiModal`
  src/Elastic.Documentation.Site/.gitignore
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/SearchOrAskAiButton.tsx
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/SearchOrAskAiModal.tsx
Labels: enhancement

#1612 Fix "Contribute and extend" link
  src/Elastic.Markdown/Layout/_LandingPage.cshtml
Labels: documentation

#1602 UpdateCLI scripts for versions.yml
  .github/workflows/updatecli.yml
  updatecli/updatecli.d/versions.yml
  updatecli/values.d/scm.yml
Labels: enhancement

#1633 Run prettier
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/SearchOrAskAiModal.tsx
Labels: chore

#1634 Modify versionfilter for apm-agent-node
  updatecli/updatecli.d/versions.yml
Labels: bug

#1636 UpdateCLI fix for RUM versions
  updatecli/updatecli.d/versions.yml
Labels: bug

#1640 Define better label for UpdateCLI and comment out stack
  config/versions.yml
  updatecli/updatecli.d/versions.yml
Labels: enhancement

#1643 Add docs-engineering as codeowners for all paths
  .github/CODEOWNERS
Labels: chore

#1621 Reference multiple OpenAPI specifications
  Directory.Packages.props
  docs/_docset.yml
  src/Elastic.ApiExplorer/OpenApiGenerator.cs
  src/Elastic.ApiExplorer/Operations/OperationNavigationItem.cs
  src/Elastic.ApiExplorer/Operations/OperationView.cshtml
  src/Elastic.Documentation.Configuration/Builder/ConfigurationFile.cs
  src/tooling/Directory.Build.props
  src/tooling/docs-builder/Http/DocumentationWebHost.cs
  src/tooling/docs-builder/Http/LiveReload.cs
  src/tooling/docs-builder/Http/ReloadGeneratorService.cs
  tests/Elastic.ApiExplorer.Tests/ReaderTests.cs
Labels: feature

#1580 feature/config folder arg
  config/assembler.yml
  src/Elastic.Documentation.Configuration/Assembler/Repository.cs
  src/Elastic.Documentation.Configuration/ConfigurationFileProvider.cs
  src/tooling/Elastic.Documentation.Tooling/Filters/InfoLoggerFilter.cs
  src/tooling/docs-assembler/Cli/RepositoryCommands.cs
  src/tooling/docs-assembler/Program.cs
  src/tooling/docs-assembler/Sourcing/GitFacade.cs
  src/tooling/docs-assembler/Sourcing/RepositorySourcesFetcher.cs
  src/tooling/docs-builder/Program.cs
Labels: feature

#1649 Fix RootNavigation on MarkdownFile
  src/tooling/docs-assembler/Cli/RepositoryCommands.cs
  src/tooling/docs-assembler/Navigation/GlobalNavigation.cs
  src/tooling/docs-assembler/Navigation/GlobalNavigationHtmlWriter.cs
Labels: fix

#1654 Update legacy-url-mappings.yml for ECK versions dropdown
  config/legacy-url-mappings.yml
Labels: documentation

#1651 Adding an allowlist for EPR links for the image directive
  src/Elastic.Markdown/Myst/Directives/Image/ImageBlock.cs
Labels: fix

#1645 Only hide the github edit link
  src/Elastic.Documentation.Site/Assets/main.ts
  src/Elastic.Markdown/HtmlWriter.cs
  src/Elastic.Markdown/Layout/_TableOfContents.cshtml
  src/Elastic.Markdown/MarkdownLayoutViewModel.cs
  src/Elastic.Markdown/Page/Index.cshtml
  src/Elastic.Markdown/Page/IndexViewModel.cs
Labels: enhancement

#1662 Set up api
  .editorconfig
  .github/workflows/build-api-lambda.yml
  .github/workflows/ci.yml
  Directory.Packages.props
  docs-builder.sln
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/useLlmGateway.ts
  src/api/Elastic.Documentation.Api.Core/AskAi/AskAiUsecase.cs
  src/api/Elastic.Documentation.Api.Core/AskAi/IAskAiGateway.cs
  src/api/Elastic.Documentation.Api.Core/Elastic.Documentation.Api.Core.csproj
  src/api/Elastic.Documentation.Api.Core/SerializationContext.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Adapters/AskAi/LlmGatewayAskAiGateway.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Aws/IParameterProvider.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Aws/LambdaExtensionParameterProvider.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Aws/LocalParameterProvider.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Elastic.Documentation.Api.Infrastructure.csproj
  src/api/Elastic.Documentation.Api.Infrastructure/Gcp/GcpIdTokenProvider.cs
  src/api/Elastic.Documentation.Api.Infrastructure/MappingsExstension.cs
  src/api/Elastic.Documentation.Api.Infrastructure/ServicesExtension.cs
  src/api/Elastic.Documentation.Api.Lambda/Dockerfile
  src/api/Elastic.Documentation.Api.Lambda/Elastic.Documentation.Api.Lambda.csproj
  src/api/Elastic.Documentation.Api.Lambda/Program.cs
  src/api/Elastic.Documentation.Api.Lambda/Properties/launchSettings.json
  src/api/Elastic.Documentation.Api.Lambda/appsettings.Development.json
  src/api/Elastic.Documentation.Api.Lambda/appsettings.json
  src/tooling/docs-builder/Http/DocumentationWebHost.cs
  src/tooling/docs-builder/docs-builder.csproj
Labels: feature

#1665 9.x adjustments to the landing page
  src/Elastic.Documentation.Site/Assets/dismissible-banner.ts
  src/Elastic.Documentation.Site/Assets/main.ts
  src/Elastic.Documentation.Site/Assets/styles.css
  src/Elastic.Markdown/Layout/_LandingPage.cshtml
  src/Elastic.Markdown/Page/Index.cshtml
  src/Elastic.Markdown/_Layout.cshtml
Labels: enhancement
