Repository elastic/docs-builder, pull requests merged in 2025-10, with the labels that each got.

#1977 Revert applies_to in directives design for recognition value
  src/Elastic.Documentation.Site/Assets/markdown/applies-switch.css
  src/Elastic.Documentation.Site/Assets/markdown/applies-to.css
  src/Elastic.Documentation.Site/Assets/markdown/dropdown.css
  src/Elastic.Markdown/Myst/Components/ApplicableToViewModel.cs
  tests/authoring/Applicability/ApplicableToComponent.fs
Labels: fix

#1982 Add Collector back to applicability badges
  src/Elastic.Documentation/AppliesTo/ApplicableToYamlConverter.cs
Labels: bug

#1985 Fix preview links in comment
  .github/workflows/preview-build.yml
  docs/testing/index.md
Labels: automation

#1990 Fix cross-link validation
  src/Elastic.Documentation.Links/CrossLinks/CrossLinkResolver.cs
  tests/authoring/Inline/CrossLinks.fs
Labels: fix

#1994 Fix --local argument to config init (checking out to config/config)
  src/services/Elastic.Documentation.Assembler/Configuration/ConfigurationCloneService.cs
Labels: fix

#1989 Set up elastic synthetics
  .github/workflows/ci.yml
  .gitignore
  src/Elastic.Documentation.Site/package-lock.json
  src/Elastic.Documentation.Site/package.json
  src/Elastic.Documentation.Site/synthetics/journeys/navigation-test.journey.ts
  src/Elastic.Documentation.Site/synthetics/synthetics.config.ts
Labels: ci

#2008 Add highlighted body text to search results
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/Search/SearchResults.tsx
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/Search/useSearchQuery.ts
  src/Elastic.Documentation.Site/Assets/web-components/SearchOrAskAi/SearchOrAskAiModal.tsx
  src/Elastic.Documentation.Site/package-lock.json
  src/Elastic.Documentation.Site/package.json
  src/Elastic.Documentation/Search/DocumentationDocument.cs
  src/Elastic.Markdown/Exporters/ElasticsearchMarkdownExporter.cs
  src/Elastic.Markdown/Exporters/IMarkdownExporter.cs
  src/Elastic.Markdown/Exporters/LlmMarkdownExporter.cs
  src/api/Elastic.Documentation.Api.Core/Search/SearchUsecase.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Adapters/Search/ElasticsearchGateway.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Aws/LocalParameterProvider.cs
  src/api/Elastic.Documentation.Api.Infrastructure/Elastic.Documentation.Api.Infrastructure.csproj
Labels: feature
