Repository elastic/docs-builder, pull requests merged in 2025-04, with the labels that each got.

#887 Fix CurrentUrlPath being empty on deeply nested snippets
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/IO/Navigation/DocumentationGroup.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveHtmlRenderer.cs
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  src/Elastic.Markdown/Myst/ParserContext.cs
  tests/Elastic.Markdown.Tests/Directives/DirectiveBaseTests.cs
  tests/Elastic.Markdown.Tests/Inline/InlneBaseTests.cs
Labels: fix

#886 Provides syntax for subscript & superscript examples
  docs/syntax/sundries.md
Labels: documentation

#892 Add 'archive' layout
  docs/_docset.yml
  docs/testing/archive.md
  docs/testing/landing-page.md
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Assets/theme.css
  src/Elastic.Markdown/Myst/FrontMatter/FrontMatterParser.cs
  src/Elastic.Markdown/Slices/Layout/_Archive.cshtml
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
  src/Elastic.Markdown/_static/delorean-bg.png
  src/Elastic.Markdown/_static/delorean.png
Labels: feature

#894 Add content_source (current/next) to assembler
  src/Elastic.Markdown/Elastic.Markdown.csproj
  src/Elastic.Markdown/Myst/YamlSerialization.cs
  src/docs-assembler/AssembleContext.cs
  src/docs-assembler/Cli/RepositoryCommands.cs
  src/docs-assembler/Configuration/AssemblyConfiguration.cs
  src/docs-assembler/Configuration/Repository.cs
  src/docs-assembler/Navigation/AssemblerDocumentationSet.cs
  src/docs-assembler/Sourcing/RepositorySourcesFetcher.cs
  src/docs-assembler/YamlStaticContext.cs
  src/docs-assembler/assembler.yml
  src/docs-assembler/docs-assembler.csproj
  tests/docs-assembler.Tests/src/docs-assembler.Tests/AssemblerConfigurationTests.cs
Labels: feature

#896 Add archive easter egg
  src/Elastic.Markdown/Assets/archive.css
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Slices/Layout/_Archive.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
Labels: enhancement

#893 Add nuget and github-actions to dependabot config
  .github/dependabot.yml
Labels: chore

#914 Update dependabot.yml
  .github/dependabot.yml
Labels: chore

#934 Ensure lambda build can attach to release
  .github/workflows/release.yml
Labels: ci

#942 Downgrade xUnit v3 to 1.1.0
  tests/Elastic.Markdown.Tests/Elastic.Markdown.Tests.csproj
  tests/authoring/authoring.fsproj
  tests/docs-assembler.Tests/src/docs-assembler.Tests/GlobalNavigationTests.cs
  tests/docs-assembler.Tests/src/docs-assembler.Tests/docs-assembler.Tests.csproj
Labels: chore

#941 Resolve links in link parser using MarkdownFile.Url if available
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  src/docs-assembler/AssembleContext.cs
  src/docs-assembler/Sourcing/RepositorySourcesFetcher.cs
Labels: fix

#945 Add prettier sort import plugin
  src/Elastic.Markdown/.prettierrc
  src/Elastic.Markdown/Assets/copybutton.ts
  src/Elastic.Markdown/Assets/hljs.ts
  src/Elastic.Markdown/Assets/main.ts
  src/Elastic.Markdown/Assets/open-details-with-anchor.ts
  src/Elastic.Markdown/eslint.config.mjs
  src/Elastic.Markdown/package-lock.json
  src/Elastic.Markdown/package.json
Labels: chore

#947 Update link registry listings to include git reference
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/BuildContext.cs
  src/Elastic.Markdown/Elastic.Markdown.csproj
  src/Elastic.Markdown/IO/State/ContentSource.cs
  src/Elastic.Markdown/IO/State/LinkReference.cs
  src/Elastic.Markdown/Links/CrossLinks/ConfigurationCrossLinkFetcher.cs
  src/Elastic.Markdown/Links/CrossLinks/CrossLinkFetcher.cs
  src/Elastic.Markdown/Links/CrossLinks/CrossLinkResolver.cs
  src/Elastic.Markdown/Links/InboundLinks/LinkIndexCrossLinkFetcher.cs
  src/Elastic.Markdown/SourceGenerationContext.cs
  src/docs-assembler/AssembleContext.cs
  src/docs-assembler/AssembleSources.cs
  src/docs-assembler/Building/AssemblerCrossLinkFetcher.cs
  src/docs-assembler/Configuration/AssemblyConfiguration.cs
  src/docs-assembler/Sourcing/RepositorySourcesFetcher.cs
  src/docs-assembler/YamlStaticContext.cs
  src/docs-assembler/docs-assembler.csproj
  src/infra/docs-lambda-index-publisher/Program.cs
  tests/Elastic.Markdown.Tests/DocSet/LinkReferenceTests.cs
  tests/Elastic.Markdown.Tests/TestCrossLinkResolver.cs
  tests/authoring/Framework/TestCrossLinkResolver.fs
  tests/docs-assembler.Tests/src/docs-assembler.Tests/AssemblerConfigurationTests.cs
Labels: feature

#951 All L1 navigation links are now collapsed by default
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
Labels: enhancement

#956 Redirect to first markdownfile on serve command in case index.md doesn't exist
  src/docs-builder/Http/DocumentationWebHost.cs
Labels: enhancement

#960 Use github.event.release.tag_name explicitly during release workflow to upload artifacts
  .github/workflows/release.yml
Labels: fix

#958 Fix table header appearance when a cell is empty
  src/Elastic.Markdown/Assets/markdown/table.css
Labels: fix

#940 Add support for multiple line comments
  docs/syntax/comments.md
  src/Elastic.Markdown/Myst/Comments/CommentMarkdownExtension.cs
  src/Elastic.Markdown/Myst/Comments/MultipleLineCommentBlockParser.cs
  tests/Elastic.Markdown.Tests/Inline/CommentTest.cs
Labels: feature

#961 Use CrtChecksums explicitly to download S3 objects inside lambda function
  src/infra/docs-lambda-index-publisher/Program.cs
  src/infra/docs-lambda-index-publisher/aws-lambda-tools-defaults.json
Labels: fix

#962 Use lamdba hosting as entry not our test code
  src/infra/docs-lambda-index-publisher/Program.cs
Labels: fix

#966 Fix misplaced guard for checking for updates on CI
  src/docs-builder/Cli/CheckForUpdatesFilter.cs
Labels: fix

#967 Use temporary folder for output in update-all-link-reference command
  src/docs-assembler/Cli/RepositoryCommands.cs
Labels: fix

#969 Use SHA256 checksum algorithm while uploading link reference
  actions/update-link-index/action.yml
Labels: fix

#970 Revert to original implementation with s3client
  src/infra/docs-lambda-index-publisher/Program.cs
Labels: fix

#972 Add Elasticsearch Rust to assembler
  src/docs-assembler/assembler.yml
  src/docs-assembler/navigation.yml
Labels: automation

#973 Updates landing page text
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
Labels: changelog:skip

#939 Move to Central Nuget Packagement
  Directory.Build.props
  Directory.Packages.props
  build/build.fsproj
  src/Directory.Build.props
  src/Elastic.Documentation.Tooling/Elastic.Documentation.Tooling.csproj
  src/Elastic.Markdown.Refactor/Elastic.Markdown.Refactor.csproj
  src/Elastic.Markdown/Elastic.Markdown.csproj
  src/docs-assembler/docs-assembler.csproj
  src/docs-builder/docs-builder.csproj
  src/infra/docs-lambda-index-publisher/docs-lambda-index-publisher.csproj
  tests/Elastic.Markdown.Tests/Elastic.Markdown.Tests.csproj
  tests/authoring/authoring.fsproj
  tests/docs-assembler.Tests/src/docs-assembler.Tests/docs-assembler.Tests.csproj
Labels: chore

#1020 Use root folder for nuget package-ecosystem
  .github/dependabot.yml
Labels: automation

#1030 Ensure ordering of navigation items by adding children after the parent's own items
  src/docs-assembler/Navigation/GlobalNavigation.cs
Labels: fix

#1031 ignore cloud's saas folder when exporting images
  src/docs-assembler/Navigation/GlobalNavigationPathProvider.cs
Labels: fix

#834 Add syntax quick ref
  docs/_docset.yml
  docs/syntax/img/annotations.png
  docs/syntax/img/bear.png
  docs/syntax/img/headings.png
  docs/syntax/img/nav-title.png
  docs/syntax/quick-ref.md
Labels: documentation

#952 Update archive links
  src/Elastic.Markdown/Slices/Layout/_Archive.cshtml
Labels: fix

#950 Update release notes nav
  src/docs-assembler/navigation.yml
Labels: fix, TOC

#1032 Update assembler.yml
  src/docs-assembler/assembler.yml
Labels: automation

#1039 Use boosted and inherited HTMX attributes for side navigation
  src/Elastic.Markdown/Assets/pages-nav.ts
  src/Elastic.Markdown/Helpers/Htmx.cs
  src/Elastic.Markdown/Slices/Layout/_TocTree.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
Labels: fix

#1040 Ensure current = next for elasticsearch in navigation.yml
  Directory.Packages.props
  src/docs-assembler/assembler.yml
  tests/docs-assembler.Tests/src/docs-assembler.Tests/AssemblerConfigurationTests.cs
Labels: fix

#1041 Cursor pointer on dismissible-button
  src/Elastic.Markdown/Assets/styles.css
Labels: fix

#1042 Register scroll as passive
  src/Elastic.Markdown/Assets/toc-nav.ts
Labels: fix

#1043 Make minor edits to syntax quick ref
  docs/syntax/quick-ref.md
Labels: documentation

#1048 Ensure we always do a --force build on CI
  src/docs-builder/Cli/Commands.cs
Labels: ci

#1050 Don't follow symlinks while s3 sync
  .github/workflows/preview-build.yml
Labels: automation

#1049 Ensure force always deletes output folder on CI regardless of generationstate
  src/Elastic.Markdown/DocumentationGenerator.cs
  src/docs-builder/Cli/Commands.cs
Labels: ci

#1051 Ensure force always deletes output folder on CI regardless of generationstate
  src/Elastic.Markdown/DocumentationGenerator.cs
Labels: ci

#1052 Set `persist-credentials` to false in `actions/checkout`
  .github/workflows/preview-build.yml
Labels: automation

#1053 Swap #main-container if TopLevelGroup differs
  src/Elastic.Markdown/Helpers/Htmx.cs
  tests/Elastic.Markdown.Tests/Inline/InlineLinkTests.cs
Labels: fix

#1055 Banner adjustments
  src/Elastic.Markdown/Slices/_Layout.cshtml
Labels: fix

#1063 Fix typo in how-to-set-up-docs-previews.md
  docs/migration/guide/how-to-set-up-docs-previews.md
Labels: documentation

#1065 Left pages nav design changes
  src/Elastic.Markdown/Slices/Layout/_TocTree.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
Labels: enhancement

#1064 Add system path tip to local contribution guide
  docs/contribute/locally.md
Labels: documentation

#1070 Display dropdown content in an overlay
  src/Elastic.Markdown/Slices/Layout/_PagesNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_TocTree.cshtml
Labels: enhancement

#1069 Use text-wrap pretty more
  src/Elastic.Markdown/Assets/markdown/typography.css
  src/Elastic.Markdown/Assets/styles.css
Labels: enhancement

#1071 Fix clean output directory in generate command, not generateall method
  src/Elastic.Markdown/DocumentationGenerator.cs
  src/docs-builder/Cli/Commands.cs
Labels: fix

#1078 Action buttons redesign
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Slices/Layout/_TableOfContents.cshtml
Labels: fix

#1080 Landing page changes
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
  src/Elastic.Markdown/_static/web-documentation-hero-illustration.svg
Labels: fix

#1076 Fix truncated text in "On this page" nav
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Slices/Layout/_TableOfContents.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
Labels: fix

#1087 Fix dropdown on safari
  src/Elastic.Markdown/Assets/pages-nav.ts
  src/Elastic.Markdown/Slices/Layout/_TocTree.cshtml
Labels: fix

#1088 Fix left nav indentation
  src/Elastic.Markdown/Slices/Layout/_TocTreeNav.cshtml
Labels: fix

#1085 Add elastic-stack to `historymapping.yml`
  src/docs-assembler/historymapping.yml
Labels: enhancement

#1092 Add stepper directive
  docs/_docset.yml
  docs/syntax/stepper.md
  src/Elastic.Markdown/Assets/markdown/stepper.css
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Myst/Directives/DirectiveBlockParser.cs
  src/Elastic.Markdown/Myst/Directives/DirectiveHtmlRenderer.cs
  src/Elastic.Markdown/Myst/Directives/StepperBlock.cs
  src/Elastic.Markdown/Slices/Directives/Step.cshtml
  src/Elastic.Markdown/Slices/Directives/Stepper.cshtml
  src/Elastic.Markdown/Slices/Directives/_ViewModels.cs
Labels: feature

#1095 Use global navigation to compute prev/next
  src/Elastic.Markdown/DocumentationGenerator.cs
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/docs-assembler/Building/AssemblerBuilder.cs
  src/docs-assembler/Cli/RepositoryCommands.cs
  src/docs-assembler/Navigation/GlobalNavigation.cs
Labels: fix

#1097 Adjust banner coloring and contents
  src/Elastic.Markdown/Slices/_Layout.cshtml
Labels: fix

#1094 Fix anchors in "On this page" nav
  src/Elastic.Markdown/IO/MarkdownFile.cs
Labels: fix

#1091 Update landing page based on feedback
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
Labels: fix

#1098 Remove search section and move down search UI
  src/docs-assembler/navigation.yml
Labels: fix, TOC

#1096 Add external link indicator
  src/Elastic.Markdown/Assets/markdown/typography.css
Labels: enhancement

#1100 Update archive heading and tests
  docs/testing/archive.md
  src/Elastic.Markdown/Slices/Layout/_Archive.cshtml
Labels: fix

#1104 Update link to previous versions
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
Labels: fix

#1105 Use git ref instead of local ref
  .github/workflows/preview-build.yml
Labels: automation

#1106 Use target attribute to identify external link
  src/Elastic.Markdown/Assets/markdown/typography.css
Labels: fix

#1108 fix inclussion path for bootstrap action
  .github/workflows/preview-build.yml
Labels: fix

#1102 Present doc page version selection in a dropdown
  src/Elastic.Markdown/Assets/pages-nav.ts
  src/Elastic.Markdown/IO/HistoryMapping/HistoryMapper.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Index.cshtml
  src/Elastic.Markdown/Slices/Layout/_TableOfContents.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
  src/docs-assembler/Mapping/PageHistoryMapper.cs
Labels: feature

#1113 Fix parent breadcrumbs in assembler build
  src/Elastic.Markdown/IO/Configuration/ConfigurationFile.cs
  src/Elastic.Markdown/IO/DocumentationFile.cs
  src/Elastic.Markdown/IO/DocumentationSet.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/IO/Navigation/DocumentationGroup.cs
  src/Elastic.Markdown/Myst/Renderers/HtmxLinkInlineRenderer.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Index.cshtml
  src/Elastic.Markdown/Slices/Layout/_Breadcrumbs.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
  src/docs-assembler/Navigation/GlobalNavigation.cs
  src/docs-assembler/Navigation/GlobalNavigationHtmlWriter.cs
  tests/Elastic.Markdown.Tests/DocSet/BreadCrumbTests.cs
  tests/Elastic.Markdown.Tests/DocSet/NestedTocTests.cs
  tests/docs-assembler.Tests/src/docs-assembler.Tests/GlobalNavigationTests.cs
Labels: fix

#1116 Add Elastic Cloud Serverless to the banner
  src/Elastic.Markdown/Slices/_Layout.cshtml
Labels: fix

#1117 Add assembler binaries to releases
  .github/workflows/release.yml
  build/Targets.fs
Labels: ci

#1120 Fix landing page links
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
Labels: fix

#1124 Add lastmod and ensure we also add DocumentationGroup navigation items
  src/docs-assembler/Building/SitemapBuilder.cs
Labels: fix

#1126 Fix secondary links
  src/Elastic.Markdown/Slices/Layout/_SecondaryNav.cshtml
Labels: fix

#1131 Update index.md
  docs/configure/site/index.md
Labels: enhancement

#1132 Ensure detection rules while hidden still allow indexing if the env allows it
  src/Elastic.Markdown/Slices/HtmlWriter.cs
Labels: fix

#1133 Ensure canonicals do not end with forward slash to match links
  src/Elastic.Markdown/Slices/_ViewModels.cs
Labels: fix

#1135 Fix scroll top when clicking on htmx link
  src/Elastic.Markdown/Assets/main.ts
Labels: fix

#1136 Add artifact attestation
  .github/workflows/release.yml
Labels: ci

#1137 Fix release workflow
  .github/workflows/release.yml
Labels: automation

#1138 Fix release workflow pt2
  .github/workflows/release.yml
Labels: automation

#1140 Allow images from the elastic-severless-forwarder repo
  src/docs-assembler/Navigation/GlobalNavigationPathProvider.cs
Labels: fix

#1141 Fix --version and new version update announcements
  Directory.Build.props
  Directory.Packages.props
  docs-builder.sln
  src/docs-builder/Cli/CheckForUpdatesFilter.cs
Labels: fix

#1149 Update historymapping.yml
  src/docs-assembler/historymapping.yml
Labels: fix

#1166 Add ECS release notes to assembler
  src/docs-assembler/navigation.yml
Labels: ci

#1144 Fix syntax error
  docs/syntax/substitutions.md
Labels: documentation

#1175 Fix release workflow
  .github/workflows/release.yml
Labels: automation

#1169 Change link-index-updater lambda to react on SQS events
  Directory.Packages.props
  src/Elastic.Markdown/Links/CrossLinks/CrossLinkResolver.cs
  src/infra/docs-lambda-index-publisher/LinkIndexProvider.cs
  src/infra/docs-lambda-index-publisher/LinkReferenceProvider.cs
  src/infra/docs-lambda-index-publisher/Program.cs
  src/infra/docs-lambda-index-publisher/README.md
  src/infra/docs-lambda-index-publisher/SerializerContext.cs
  src/infra/docs-lambda-index-publisher/docs-lambda-index-publisher.csproj
Labels: enhancement

#1177 Disable 'Update Reference Index' action
  actions/update-reference-index/action.yml
Labels: fix

#1188 Create dependabot group for System.IO.Abstractions
  .github/dependabot.yml
Labels: automation

#1178 Fix release workflow permissions
  .github/workflows/release.yml
Labels: automation

#1185 Add link-index-updater AWS lambda deployment steps
  .github/workflows/release.yml
Labels: automation

#1186 Cleanup: Remove update-reference-index action
  .github/workflows/preview-cleanup.yml
  actions/update-reference-index/action.yml
  docs-builder.sln
Labels: chore

#1194 Remove deprecated step
  .github/workflows/preview-build.yml
Labels: fix

#1195 Change curator history mapping to 7.0
  src/docs-assembler/historymapping.yml
Labels: fix

#1183 Max width layout
  src/Elastic.Markdown/Assets/markdown/code.css
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Assets/theme.css
  src/Elastic.Markdown/Slices/Layout/_Footer.cshtml
  src/Elastic.Markdown/Slices/Layout/_Header.cshtml
  src/Elastic.Markdown/Slices/Layout/_PrevNextNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_SecondaryNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_TableOfContents.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
Labels: enhancement

#1199 Fix link-index-updater lambda deployment
  .github/workflows/release.yml
Labels: automation

#1198 Slight on this page margin adjustments
  src/Elastic.Markdown/Slices/Layout/_TableOfContents.cshtml
Labels: fix

#1201 feature/limited width layout 4
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Slices/Layout/_Footer.cshtml
  src/Elastic.Markdown/Slices/Layout/_Header.cshtml
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
  src/Elastic.Markdown/Slices/Layout/_PagesNav.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
Labels: fix
