Repository elastic/docs-builder, pull requests merged in 2025-05, with the labels that each got.

#1205 Upgrade AWS packages
  Directory.Packages.props
  src/infra/docs-lambda-index-publisher/docs-lambda-index-publisher.csproj
Labels: ci

#1204 Make sure release-drafter runs for the current commit
  .github/workflows/release.yml
Labels: automation

#1197 Dynamic max-width based on 90ch width for the content
  src/Elastic.Markdown/Assets/styles.css
  src/Elastic.Markdown/Slices/Layout/_Footer.cshtml
  src/Elastic.Markdown/Slices/Layout/_Header.cshtml
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
  src/Elastic.Markdown/Slices/Layout/_PagesNav.cshtml
  src/Elastic.Markdown/Slices/Layout/_TableOfContents.cshtml
  src/Elastic.Markdown/Slices/_Layout.cshtml
Labels: feature

#1162 Update syntax image examples to use `images` path
  docs/development/index.md
  docs/syntax/applies.md
  docs/syntax/images.md
  docs/syntax/images/alerts.svg
  docs/syntax/images/annotations.png
  docs/syntax/images/apm.png
  docs/syntax/images/applies.png
  docs/syntax/images/bear.png
  docs/syntax/images/headings.png
  docs/syntax/images/nav-title.png
  docs/syntax/images/observability.png
  docs/syntax/images/serverless-capabilities.svg
  docs/syntax/images/timeslider.gif
  docs/syntax/lists.md
  docs/syntax/quick-ref.md
Labels: documentation

#1079 Remove leniency downloading links.json files
  src/Elastic.Markdown/Links/CrossLinks/ConfigurationCrossLinkFetcher.cs
Labels: fix

#1215 link-index-updater: Optimize and add more logging
  src/infra/docs-lambda-index-publisher/LinkIndexProvider.cs
  src/infra/docs-lambda-index-publisher/Program.cs
Labels: enhancement

#1217 Add link-index-updater lambda build job
  .github/workflows/build-link-index-updater-lambda.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  src/infra/docs-lambda-index-publisher/LinkIndexProvider.cs
Labels: automation

#1207 Collect all redirects during assemble builds
  src/Elastic.Markdown/BuildContext.cs
  src/Elastic.Markdown/DocumentationGenerator.cs
  src/tooling/docs-assembler/AssembleContext.cs
  src/tooling/docs-assembler/Building/AssemblerBuilder.cs
  src/tooling/docs-assembler/Building/PublishEnvironmentUriResolver.cs
  src/tooling/docs-assembler/Cli/RepositoryCommands.cs
  src/tooling/docs-assembler/Navigation/AssemblerDocumentationSet.cs
  src/tooling/docs-builder/Cli/Commands.cs
  tests/authoring/Framework/TestValues.fs
Labels: feature

#1220 Use planned instead of coming in applies_to tags
  docs/syntax/applies.md
  src/Elastic.Markdown/Myst/FrontMatter/Applicability.cs
  src/Elastic.Markdown/Myst/FrontMatter/ProductLifecycle.cs
  tests/authoring/Applicability/AppliesToFrontMatter.fs
Labels: fix

#1219 Refactor ImageBlock URL handling and file resolution logic.
  src/Elastic.Markdown/Myst/Directives/DirectiveHtmlRenderer.cs
  src/Elastic.Markdown/Myst/Directives/ImageBlock.cs
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
  tests/Elastic.Markdown.Tests/Directives/ImageTests.cs
  tests/authoring/Blocks/ImageBlocks.fs
  tests/authoring/Container/DefinitionLists.fs
  tests/authoring/Framework/Setup.fs
  tests/authoring/authoring.fsproj
Labels: fix

#1218 Fix lambda release
  .github/workflows/build-link-index-updater-lambda.yml
  .github/workflows/release.yml
Labels: automation

#1222 Make assembler build explicit on BuildContext
  docs/_docset.yml
  src/Elastic.Markdown/BuildContext.cs
  src/Elastic.Markdown/DocumentationGenerator.cs
  src/tooling/docs-assembler/Navigation/AssemblerDocumentationSet.cs
Labels: fix

#1224 Ensure clone-all starts error collection
  src/tooling/docs-assembler/Cli/NavigationCommands.cs
  src/tooling/docs-assembler/Cli/RepositoryCommands.cs
  tests/docs-assembler.Tests/src/docs-assembler.Tests/GlobalNavigationTests.cs
Labels: fix

#1225 Only emit one error if capturing stdout goes wrong during assembler checkout
  src/tooling/docs-assembler/Sourcing/RepositorySourcesFetcher.cs
Labels: fix

#1221 Update definition-lists.md
  docs/syntax/definition-lists.md
Labels: documentation

#1226 Add `products` frontmatter
  Directory.Packages.props
  docs/syntax/frontmatter.md
  src/Elastic.Markdown/Elastic.Markdown.csproj
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/Myst/FrontMatter/FrontMatterParser.cs
  src/Elastic.Markdown/Myst/FrontMatter/Layout.cs
  src/Elastic.Markdown/Myst/FrontMatter/Products.cs
  src/Elastic.Markdown/Myst/YamlSerialization.cs
  src/Elastic.Markdown/Slices/Index.cshtml
  src/Elastic.Markdown/Slices/Layout/_Head.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
  src/Elastic.Markdown/Suggestions/Suggestions.cs
  tests/Elastic.Markdown.Tests/FrontMatter/YamlFrontMatterTests.cs
Labels: feature

#1232 Add install scripts
  .github/workflows/release.yml
  docs/contribute/locally.md
  install.ps1
  install.sh
Labels: feature

#1235 Fix non-interactive scenario
  install.sh
Labels: fix

#1237 Refactor products frontmatter
  Directory.Packages.props
  src/Elastic.Markdown/Elastic.Markdown.csproj
  src/Elastic.Markdown/Myst/FrontMatter/Products.cs
  src/Elastic.Markdown/Slices/Index.cshtml
  tests/Elastic.Markdown.Tests/FrontMatter/YamlFrontMatterTests.cs
Labels: chore

#1240 Add random query string
  src/Elastic.Markdown/Slices/Layout/_LandingPage.cshtml
Labels: fix

#1241 Ensure docs-builder builds to `.artifacts/assembly/<content-source>` and support a flag on serve-static to choose
  src/tooling/docs-assembler/AssembleContext.cs
  src/tooling/docs-builder/Cli/Commands.cs
  src/tooling/docs-builder/Http/StaticWebHost.cs
Labels: fix

#1242 Fix assuming _snippets files only live one folder deep when resolving relative image links inside of them
  src/Elastic.Markdown/Myst/Directives/ImageBlock.cs
  src/Elastic.Markdown/Myst/InlineParsers/DiagnosticLinkInlineParser.cs
Labels: fix

#1239 Add docset `products` attribute
  docs/_docset.yml
  docs/syntax/code.md
  src/Elastic.Documentation.Configuration/Builder/ConfigurationFile.cs
  src/Elastic.Documentation.Configuration/Builder/Products.cs
  src/Elastic.Documentation.Configuration/Suggestions/Suggestions.cs
  src/Elastic.Markdown/Myst/FrontMatter/FrontMatterParser.cs
  src/Elastic.Markdown/Myst/FrontMatter/Products.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/Elastic.Markdown/Slices/Index.cshtml
  src/Elastic.Markdown/Slices/_ViewModels.cs
Labels: feature

#1238 Add `id` attribute to `products` list frontmatter
  docs/_docset.yml
  docs/syntax/code.md
  docs/syntax/frontmatter.md
  src/Elastic.Documentation.Configuration/Builder/ConfigurationFile.cs
  src/Elastic.Markdown/Myst/FrontMatter/Products.cs
  tests/Elastic.Markdown.Tests/FrontMatter/YamlFrontMatterTests.cs
Labels: chore

#1243 Revert default assemble output path back to .artifacts/assembly
  src/tooling/docs-assembler/AssembleContext.cs
  src/tooling/docs-builder/Cli/Commands.cs
  src/tooling/docs-builder/Http/StaticWebHost.cs
Labels: fix

#1236 Remove tab from install docs
  docs/contribute/locally.md
Labels: fix

#1259 Suppress FS3261 error
  tests/authoring/Framework/HtmlAssertions.fs
Labels: chore

#1256 Update product list, alphabetize
  docs/syntax/frontmatter.md
  src/Elastic.Documentation.Configuration/Builder/Products.cs
  tests/Elastic.Markdown.Tests/FrontMatter/YamlFrontMatterTests.cs
Labels: feature

#1231 Update assembler.yml to add EDOT docs
  src/tooling/docs-assembler/assembler.yml
  src/tooling/docs-assembler/navigation.yml
Labels: feature

#1244 Add shortened links to install commands
  docs/contribute/locally.md
Labels: enhancement

#1255 Make install script more robust
  docs/contribute/locally.md
  install.sh
Labels: enhancement

#1273 Complete locally.md docs and add macros
  docs/contribute/locally.md
Labels: enhancement

#1262 Test for irregular whitespaces
  src/Elastic.Markdown/Myst/Linters/WhiteSpaceNormalizer.cs
  src/Elastic.Markdown/Myst/MarkdownParser.cs
  tests/authoring/Framework/ErrorCollectorAssertions.fs
  tests/authoring/Framework/TestValues.fs
  tests/authoring/Inline/Comments.fs
  tests/authoring/Linters/WhiteSpaceNormalizers.fs
  tests/authoring/authoring.fsproj
Labels: enhancement

#1245 Throw warning when applies_to is empty
  docs/syntax/applies.md
  src/Elastic.Markdown/Myst/FrontMatter/ApplicableTo.cs
  tests/authoring/Applicability/AppliesToFrontMatter.fs
Labels: enhancement

#1283 Refactor logging and fix variable usage in Match method
  src/tooling/docs-assembler/Cli/ContentSourceCommands.cs
Labels: chore

#1284 Asssembler content-source matching should not have exit code 1 when it does not match
  src/tooling/docs-assembler/Cli/ContentSourceCommands.cs
Labels: chore

#1279 Add a new job to handle push event matching
  .github/workflows/preview-build.yml
  docs-builder.sln
  src/tooling/docs-assembler/AssembleSources.cs
  src/tooling/docs-assembler/Sourcing/RepositorySourcesFetcher.cs
  src/tooling/docs-assembler/assembler.yml
Labels: chore

#1285 Assembler match: log level from Error to Information for missing config
  src/Elastic.Documentation/Serialization/SourceGenerationContext.cs
  src/tooling/docs-assembler/Cli/ContentSourceCommands.cs
Labels: fix

#1286 Assembler match: print each content source explicitly
  actions/assembler-match/action.yml
  src/Elastic.Documentation.Configuration/Assembler/AssemblyConfiguration.cs
  src/tooling/docs-assembler/Cli/ContentSourceCommands.cs
Labels: fix

#1287 Assembler match: update preview workflow to use new outputs
  .github/workflows/preview-build.yml
Labels: chore

#1288 Assembler match: remove name output
  actions/assembler-match/action.yml
  src/tooling/docs-assembler/Cli/ContentSourceCommands.cs
Labels: chore

#1289 Use match job in docs-preview build
  .github/workflows/preview-build.yml
Labels: ci

#1290 Temporarily mark docs-builder's current branch to 9.0
  src/tooling/docs-assembler/assembler.yml
Labels: ci

#1292 test/doc changes on 90
  docs/testing/archive.md
  src/tooling/docs-assembler/assembler.yml
Labels: ci

#1294 Fix NRE in LinkIndexProvider while adding a new branch to existing repository
  src/infra/docs-lambda-index-publisher/LinkIndexProvider.cs
Labels: fix

#1297 Add handling for speculative matches in content source logic
  .github/workflows/preview-build.yml
  actions/assembler-match/action.yml
  src/Elastic.Documentation.Configuration/Assembler/AssemblyConfiguration.cs
  src/Elastic.Documentation/SemVersion.cs
  src/Elastic.Markdown/Myst/Directives/VersionBlock.cs
  src/Elastic.Markdown/Myst/FrontMatter/AllVersions.cs
  src/Elastic.Markdown/Myst/FrontMatter/Applicability.cs
  src/Elastic.Markdown/Myst/Roles/AppliesTo/AppliesToRole.cs
  src/tooling/docs-assembler/Cli/ContentSourceCommands.cs
  src/tooling/docs-builder/Cli/CheckForUpdatesFilter.cs
  tests/Elastic.Markdown.Tests/Directives/VersionTests.cs
Labels: ci

#1299 Add support for 'content-source-speculative' in preview builds.`
  .github/workflows/preview-build.yml
Labels: ci

#1301 Validate assembler content source configs as part of our PR builds
  .github/workflows/pr.yml
Labels: ci

#1180 Publish ECS 9.0.0 documentation
  src/tooling/docs-assembler/assembler.yml
Labels: automation

#1306 Create dependabot tailwindcss group
  .github/dependabot.yml
Labels: chore

#1303 Update versioning docs with deployment models and CI details
  docs/migration/guide/how-to-set-up-docs-previews.md
  docs/migration/guide/move-ref-docs.md
  docs/migration/versioning.md
Labels: documentation

#1307 Fix `npm run watch`
  .nvmrc
  build/Targets.fs
  src/Elastic.Markdown/package-lock.json
  src/Elastic.Markdown/package.json
Labels: chore

#1309 Also run PR checks on main
  .github/workflows/ci.yml
  README.md
Labels: ci

#1311 Assembler: clone-all from link-index registry
  src/Elastic.Documentation.Configuration/Assembler/Repository.cs
  src/tooling/docs-assembler/Cli/RepositoryCommands.cs
  src/tooling/docs-assembler/Sourcing/RepositorySourcesFetcher.cs
Labels: enhancement

#1317 fix(install): update x64 download link in install script
  install.sh
Labels: bug

#1323 Add new ESQL keywords/commands to highlighter
  src/Elastic.Markdown/Assets/hljs.ts
Labels: fix

#1320 Add exporter options to assembler
  Directory.Packages.props
  src/Elastic.Documentation.Search/Elastic.Documentation.Search.csproj
  src/Elastic.Documentation/Diagnostics/IDiagnosticsCollector.cs
  src/Elastic.Documentation/Search/DocumentationDocument.cs
  src/Elastic.Documentation/Serialization/SourceGenerationContext.cs
  src/Elastic.Markdown/DocumentationGenerator.cs
  src/Elastic.Markdown/Exporters/DocumentationFileExporter.cs
  src/Elastic.Markdown/Exporters/IMarkdownExporter.cs
  src/Elastic.Markdown/Exporters/NoopDocumentationFileExporter.cs
  src/Elastic.Markdown/Extensions/DetectionRules/RuleDocumentationFileExporter.cs
  src/Elastic.Markdown/IO/MarkdownFile.cs
  src/Elastic.Markdown/Myst/MarkdownParser.cs
  src/Elastic.Markdown/Slices/HtmlWriter.cs
  src/tooling/Elastic.Documentation.Tooling/Diagnostics/Console/ErrataFileSourceRepository.cs
  src/tooling/docs-assembler/Building/AssemblerBuilder.cs
  src/tooling/docs-assembler/Cli/RepositoryCommands.cs
  src/tooling/docs-assembler/Exporters/ElasticsearchMarkdownExporter.cs
  src/tooling/docs-assembler/Exporters/LLMTextExporter.cs
  src/tooling/docs-assembler/docs-assembler.csproj
  src/tooling/docs-builder/Cli/Commands.cs
  tests/authoring/Framework/Setup.fs
Labels: feature
